### ISSUE TITLE
Localhost :  webrtc-sendrecv.c configuration.

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#10]
Hi, i'm also trying this demo on localhost.

I have a node server serving JS+HTML file and a signalling server "simple-server.py" 

My signalling server is on port : 8443 
My node.js server is on port : 8000

I want to use the webrtc-sendrecv.c to send a gstreamer stream.

I have changed the : 

static const gchar *server_url = "wss://webrtc.nirbheek.in:8443";

into

static const gchar *server_url = "wss://localhost:8443";

But when i run in a shell : ./webrtc-sendrecv --peer-id=3937

I get an error :

Connecting to server...
< HTTP/1.1 6 Unacceptable TLS certificate
< Soup-Debug-Timestamp: 1522404866
< Soup-Debug: SoupMessage 0 (0x25bc0b0)
  
The server did not accept the WebSocket handshake.

Can't figure out what's my mistake ! 

Sorry for my "bad english" 

Thank a lot for reading this thread

**Comment by nirbheek** [comment]
1. You don't need to edit the file to set the server; the `--server` argument works fine.
2. Find the line `session = soup_session_new_with_options (SOUP_SESSION_SSL_STRICT, TRUE,` and change it to `FALSE`, that should fix it.
3. I have also uploaded a change that does (2) automatically when `--server` points to localhost, so you can just do a git pull, recompile, and try again.

**Comment by nirbheek** [comment]
Closing, please reopen if this doesn't fix it for you.
