### ISSUE TITLE
Establishing video stream fails sporadically

### ISSUE THREAD

**Issue by jakob-d** [centricular/gstwebrtc-demos#100]
The C-version of the webrtc-sendrecv demo sometimes fails to handle the "web-to-gstreamer" video stream. The terminal then only shows 
<pre>
Trying to handle stream with audioconvert ! autoaudiosink
</pre>
but 
<pre>
Trying to handle stream with videoconvert ! autovideosink
</pre>
is missing. At the same time, the "gstreamer-to-web" stream works fine and the website shows the ball-pattern.

It appears to me this could be some kind of race condition, since I only encounter this issue sporadically on my very slow notebook (roughly once out of five tries) and I almost never hit it on my faster desktop machine, except when debugging with GDB (then also roughly once every five tries).

I'm not very skilled at reading the GST logs but it seems there is some problem with NiceSrc:
<pre>
139197:0:00:05.272590829  8275 0x7fffcc08c850 WARN                 basesrc gstbasesrc.c:3072:gst_base_src_loop:<nicesrc0> error: Internal data stream error.
139207:0:00:05.272629501  8275 0x7fffcc08c850 WARN                 basesrc gstbasesrc.c:3072:gst_base_src_loop:<nicesrc0> error: streaming stopped, reason not-linked (-1)
139273:0:00:05.272689984  8275 0x7fffcc08c850 INFO        GST_ERROR_SYSTEM gstelement.c:2141:gst_element_message_full_with_details:<nicesrc0> posting message: Internal data stream error.
139282:0:00:05.272993048  8275 0x7fffcc08c850 LOG              GST_MESSAGE gstmessage.c:305:gst_message_new_custom: source nicesrc0: creating new message 0x7fffcc0a7700 error
139283:0:00:05.273019819  8275 0x7fffcc08c800 ERROR         queue_dataflow gstqueue.c:1483:gst_queue_push_one:<queue4> exit because we have no item in the queue
</pre>

Sometimes, there is also a warning about a queue in the webrtc-sendrecv demo terminal output:
<pre>
** (webrtc-sendrecv:8275): WARNING **: 11:19:12.570: Unexpected item 0x7fffa4006320 dequeued from queue queue4 (refcounting problem?)
</pre>
or a BUS error message:
<pre>
Quitting main loop, BUS received error: ;nicesrc0;Internal data stream error.;../libs/gst/base/gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstWebRTCBin:sendrecv/TransportReceiveBin:transportreceivebin0/GstNiceSrc:nicesrc0:
streaming stopped, reason not-linked (-1)
</pre>
but I noticed that these outputs do not always show up in the terminal when I encounter the bug, so there might be multiple issues.

I attached the GST-debug log with level 6:
[gst-debug-6.log.zip](https://github.com/centricular/gstwebrtc-demos/files/3072742/gst-debug-6.log.zip)

the terminal output of the webrtc-sendrecv C-demo:
[webrtc-sendrecv-gdb.log](https://github.com/centricular/gstwebrtc-demos/files/3072650/webrtc-sendrecv-gdb.log)

the terminal output of the simple server:
[simple-server.log](https://github.com/centricular/gstwebrtc-demos/files/3072648/simple-server.log)

and the log of the javascript console:
[web-index.log](https://github.com/centricular/gstwebrtc-demos/files/3072649/web-index.log)

I encountered the problem on Ubuntu 16.04 and 18.04 with GStreamer 1.15.2 built with Cerbero.

**Comment by neilyoung** [comment]
Java version too

**Comment by jakob-d** [comment]
#109 seems to fix the issue for me!
