### ISSUE TITLE
Q: Why is there such a high latency?

### ISSUE THREAD

**Issue by neilyoung** [centricular/gstwebrtc-demos#102]
I'm running the Java sample and the JS sample on the same machine and wondering about the incredibly high latency of the received video. Usually local WebRTC connections don't have any remarkable delay. But here I have a delay of about 1s. Where is that coming from? Can it be minimised?

As is webrtcbin is not a real competitor. Even a headless browser run from a Java app, feeding the received video as MJPEG to the Java app has a lower latency.

**Comment by nirbheek** [comment]
200ms of that latency is coming from the fixed-size jitterbuffer inside rtpbin (which is an element inside webrtcbin). You can set that to a lower value such as 10ms if you're on a link-local network. Not sure where the rest of the latency is coming from for you. The last time I tested it, the latency was quite low.

**Comment by neilyoung** [comment]
Thanks. Would you mind to share how I can set that value of 10 ms?
Really, I'm used to see latencies far below 100ms in local WebRTC situations, like from browser to browser. Here it is from browser to Java and 1 s is ways too much.

**Comment by tp-m** [comment]
> Really, I'm used to see latencies far below 100ms in local WebRTC situations, like from browser to browser. Here it is from browser to Java and 1 s is ways too much.

I don't think anyone disagrees with that. webrtcbin has been used in low-latency situations just fine. Someone just needs to figure out why it's so bad in your case :)

**Comment by neilyoung** [comment]
I'm really keen to find that out :)

OK, how can I lower the latency? @nirbheek was talking about setting some value to 10 ms. Does anybody know, how?

**Comment by alexlapa** [comment]
@neilyoung , @nirbheek,

I confirm pretty high latency of ~1.2s. If i remember correctly, disabling audio-video sync allowed to drop video latency significantly.

**Comment by neilyoung** [comment]
@alexlapa Thanks for confirmation. How could "disabling audio-video sync" be done using the Java API?

**Comment by alexlapa** [comment]
@neilyoung ,

Im not familiar with Java API. Set `sync` property to `false` on sink elements (`autoaudiosink`, `autovideosink`).

**Comment by neilyoung** [comment]
@alexlapa Wow... Not only significantly better, it is a difference like day and night

 `autovideosink.set("sync", false);`

Same for audio. Not sure what that means for lip-sync, but I just need video.

**Comment by polhaghverdian** [comment]
> 
> 
> 200ms of that latency is coming from the fixed-size jitterbuffer inside rtpbin (which is an element inside webrtcbin). You can set that to a lower value such as 10ms if you're on a link-local network. Not sure where the rest of the latency is coming from for you. The last time I tested it, the latency was quite low.

How do you decrease the latency by lowering the jitter-buffer from rtpbin?

**Comment by polhaghverdian** [comment]
I added **rtpjitterbuffer latency=0** inside the gst_parse_launch, but have no way to measure if it really had an effect. Can someone confirm this is the right place to have it?

`gst_parse_launch("webrtcbin bundle-policy=max-bundle name=sendrecv " STUN_SERVER
			"gdiscreencapsrc cursor=true ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "
			"queue ! " RTP_CAPS_VP8 "96 ! rtpjitterbuffer latency=0 ! sendrecv. "`

**Comment by sdroege** [comment]
You have to set the latency on the rtpjitterbuffer inside rtpbin inside webrtcbin, not by adding a new jitterbuffer in addition. Also 0 is too low, you need some non-zero value that corresponds to your actual network jitter.

**Comment by polhaghverdian** [comment]
> You have to set the latency on the rtpjitterbuffer inside rtpbin inside webrtcbin, not by adding a new jitterbuffer in addition. Also 0 is too low, you need some non-zero value that corresponds to your actual network jitter.


Thanks for the reply. 

I will try 🙂

**Comment by miguelwon** [comment]
> You have to set the latency on the rtpjitterbuffer inside rtpbin inside webrtcbin, not by adding a new jitterbuffer in addition. Also 0 is too low, you need some non-zero value that corresponds to your actual network jitter.

@sdroege , how can "set the latency on the rtpjitterbuffer inside rtpbin inside webrtcbin"? s it through the pipeline?  Can you show a simple example?  I

**Comment by thaytan** [comment]
This should do it (to set 40ms latency):
rtpbin = gst_bin_get_by_name (webrtcbin, "rtpbin");
g_object_set (rtpbin, "latency", 40, NULL);
gst_object_unref (rtpbin);

Do that right after creating the webrtcbin, before starting the pipeline.

**Comment by miguelwon** [comment]
Ok, thanks @thaytan! Even so, not sure if it is working. I now have this:

```
  pipe1 =
      gst_parse_launch ("webrtcbin  bundle-policy=max-bundle name=sendrecv " STUN_SERVER
      "v4l2src ! videorate ! video/x-raw,width=640,height=480,framerate=30/1 ! "
      "videoconvert ! queue max-size-buffers=1 ! x264enc bitrate=600 speed-preset=ultrafast tune=zerolatency key-int-max=15 !"
      "rtph264pay config-interval=-1 name=payloader ! "
      "application/x-rtp,media=video,encoding-name=H264,payload=96 ! sendrecv.",
      &error);

  rtpbin = gst_bin_get_by_name(GST_BIN (pipe1),"rtpbin");
  g_object_set(rtpbin,"latency",40,NULL);
  g_object_unref(rtpbin);
```


that was adapted from the [sendrecv example](https://github.com/centricular/gstwebrtc-demos/blob/master/sendrecv/gst/webrtc-sendrecv.c). But I still have 200ms of latency in the local network. I also tried to set the latency to 5000ms just to check if it is working, but it continues to perform with 200ms.

**Comment by thaytan** [comment]
You need to get rtpbin from inside the webrtcbin, not from the top-level pipeline object.

In the sendrecv example, a few lines after the code you pasted, it does:
 webrtc1 = gst_bin_get_by_name (GST_BIN (pipe1), "sendrecv");
and webrtc1 is the object you want to get the rtpbin out of.

**Comment by miguelwon** [comment]
Sorry @thaytan , is like the code I show bellow? It runs but I still have the 200ms. When I set to 4000ms I don't have the delay as well.

```
  pipe1 =
      gst_parse_launch ("webrtcbin  bundle-policy=max-bundle name=sendrecv " STUN_SERVER
      "v4l2src ! videorate ! video/x-raw,width=640,height=480,framerate=30/1 ! "
      "videoconvert ! queue max-size-buffers=1 ! x264enc bitrate=600 speed-preset=ultrafast tune=zerolatency key-int-max=15 !"
      "rtph264pay config-interval=-1 name=payloader ! "
      "application/x-rtp,media=video,encoding-name=H264,payload=96 ! sendrecv.",
      &error);

  if (error) {
    g_printerr ("Failed to parse launch: %s\n", error->message);
    g_error_free (error);
    goto err;
  }

  webrtc1 = gst_bin_get_by_name (GST_BIN (pipe1), "sendrecv");
  g_assert_nonnull (webrtc1);

  rtpbin = gst_bin_get_by_name(GST_BIN(webrtc1),"rtpbin");
  g_object_set(rtpbin,"latency",4000,NULL);
  g_object_unref(rtpbin);
```

**Comment by miguelwon** [comment]
Perhaps an alternative option would be to change the [default value](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtpbin.html#GstRtpBin--latency) permanently. Any idea how?

**Comment by thaytan** [comment]
Are you still having problems with this, or did you figure something out in the meantime?

If you are, capturing some debug logs so we can see what's happening with the pipeline latency configuration would be useful.

**Comment by miguelwon** [comment]
No, but I was not able to change the latency. I'm now working with the python version and tried to set the property with:

`
.get_by_name('rtpbin').set_property("latency_ms",4000)
`

But didn't work either.

**Comment by thaytan** [comment]
the property you need to set is "latency". There's no "latency_ms" property on rtpbin. The units of the latency property are milliseconds though. You can use 'gst-inspect-1.0 rtpbin' to see the properties it has.

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
