### ISSUE TITLE
Reuse pipeline - Waiting for connections

### ISSUE THREAD

**Issue by roberto497** [centricular/gstwebrtc-demos#104]
They have asked this question here, but they have not posted the solution, I am using the example in C, and I made an adaptation in it and in the webcocket so that it connects and is waiting for a call, but an error occurs when I finish a call and try to do another , to make sure I need to close and open the program again

**Comment by ystreet** [comment]
webrtcbin has not been tested for connection reuse and it probably does not work.  If it works, great.
