### ISSUE TITLE
What is the way to receive video only?

### ISSUE THREAD

**Issue by neilyoung** [centricular/gstwebrtc-demos#106]
Trying to modify the Java sample to enable the code to receive video only. The caller should NOT send any audio nor video nor receive audio. How can this be achieved?

Pointers appreciated.

**Comment by turtlebond** [comment]
You could look into this.
https://github.com/centricular/gstwebrtc-demos/compare/master...a-morales:figure-out-transceivers?expand=1
Remove the audio part to not receive audio.

**Comment by neilyoung** [comment]
Thanks, but I was referring to the gst-java branch.

Currently there is this:


```
        Bin video = Gst.parseBinFromDescription(VIDEO_BIN_DESCRIPTION, true);
        Bin audio = Gst.parseBinFromDescription(AUDIO_BIN_DESCRIPTION, true);

        pipe = new Pipeline();

        pipe.addMany(webRTCBin, video, audio);
        video.link(webRTCBin);
        audio.link(webRTCBin);
        setupPipeLogging(pipe);

```

I thought I could easily omit all the audio things, but that doesn't work.

**Comment by neilyoung** [comment]
To be more specific: 

 `webRTCBin.createOffer(onOfferCreated);`

onOfferCreated is never called if there is no audio bin

**Comment by neilyoung** [comment]
Again: If I remove just the audio stuff by changing

```
        pipe.addMany(webRTCBin, video, audio);
        video.link(webRTCBin);
        audio.link(webRTCBin);
```

to

```
        pipe.addMany(webRTCBin, video);
        video.link(webRTCBin);
```

it works on Ubuntu. It doesn't work on macOS. Windows not tested. What can this be?

On macOS the call to `webRTCBin.createOffer(onOfferCreated);` does not lead to a callback `onOfferCreated`.

**Comment by a-morales** [comment]
@neilyoung you will need to add a transceiver instead of linking a source. I have a fork of [ gst1-java-core](https://github.com/ai-foundation/gst1-java-core/tree/webrtc-datachannels) that has basic support for transceivers. With that you can do something like

```java
Caps transceiverCaps = Caps.fromString("application/x-rtp,media=video,encoding-name=VP8,payload=96");

webRTCBin.addTransceiver(WebRTCTransceiverDirection.RECVONLY, transceiverCaps);
```

**Comment by neilyoung** [comment]
@a-morales Thanks, will have a look into. The strange ist: The other way works on Ubuntu...

**Comment by neilyoung** [comment]
@a-morales Yes, that works, but while testing it I came across a strange issue with native counterparts (e.g. an iOS app, which provides the screen capture via WebRTC and an Android app, which provides the drone's video via WebRTC). Both native apps are based upon Google's WebRTC core and work great with a WebApp as partner app.

With the java demo (either the original or the patched) there is about 10 - 20 seconds of good video, until it all goes down in scrambled colours (artefacts). I don't know, how to overcome this right now. 

In all cases it is a VP8 codec used at source side.

**Comment by a-morales** [comment]
@neilyoung you may need to request keyframes from upstream to fix the artifacts.

https://github.com/centricular/gstwebrtc-demos/issues/61 has more information about it, but going off my fork it would be something like

```java
Structure struct = new Structure("GstForceKeyUnit", "all-headers", GType.BOOLEAN, Boolean.valueOf(true));
Event keyframeEvent = new Event(EventType.CUSTOM_UPSTREAM, eventStructure);

pad.sendEvent(keyframeEvent);
```

The `pad` would be the pad added by `WebRTCBin` containing the video stream. Depending on what you are doing you may need to periodically send keyframe request events.

**Comment by neilyoung** [comment]
@a-morales Really? Why am I not forced to do anything like this with the same JAR running against a web app? It only happens if I work agains the native clients...

**Comment by neilyoung** [comment]
BTW If the artefacts happen I see this in the console (enabled GST trace level 3)


```
0:00:44.610127000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()
0:00:44.610182000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()
0:00:44.610199000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()
0:00:44.610215000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()
0:00:44.610231000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()
0:00:44.610307000  6280 0x7fc6fe85ed40 FIXME           videodecoder gstvideodecoder.c:933:GstFlowReturn gst_video_decoder_drain_out(GstVideoDecoder *, gboolean):<vp8dec0> Sub-class should implement drain()


```

**Comment by neilyoung** [comment]
@a-morales I applied your key frame patch, but this doesn't solve the problem by the root. Say you set the key frame request rate to 10s then you have to deal with the garbage for 10 s max. That doesn't work well.

**Comment by a-morales** [comment]
Yeah, Not exactly sure exactly what is going on. I've been getting the same artifact issues on iOS, but not in the browser. There is another issue open for pixelated video https://github.com/centricular/gstwebrtc-demos/issues/31, which looks like it may still be an ongoing issue.

**Comment by neilyoung** [comment]
@a-morales Same on iOS here. But not if the Chrome browser communicates with the gst-java. I have also seen https://github.com/centricular/gstwebrtc-demos/issues/31.

**Comment by ystreet** [comment]
Please use upstream GStreamer for issues with webrtcbin itself.  Support requests should be directed at the GStreamer mailing list or IRC channel.
