### ISSUE TITLE
Video corruption when using getDisplayMedia or mediaSource: "screen"

### ISSUE THREAD

**Issue by dicej** [centricular/gstwebrtc-demos#107]
I suspect this may have the same root cause as https://github.com/centricular/gstwebrtc-demos/issues/31, but the scenario is different.  I've modified webrtc.js as follows to use the screen as the source rather than the camera:

```diff
-    if (navigator.mediaDevices.getUserMedia) {
-        return navigator.mediaDevices.getUserMedia(constraints);
+    if (navigator.getDisplayMedia) {
+        return navigator.getDisplayMedia(constraints);
+    } else if (navigator.mediaDevices.getDisplayMedia) {
+      return navigator.mediaDevices.getDisplayMedia(constraints);
+    } else if (navigator.mediaDevices.getUserMedia) {
+      return navigator.mediaDevices.getUserMedia({video: {mediaSource: 'screen'}});
```

With that patch applied, when I connect to Firefox or Chrome using either the C or Rust demo app, everything looks fine at first, but after a few minutes the video becomes a mess of macroblock noise.  Everything's running on the same machine using the loopback network interface.  It's a Core i7-8650U laptop running Ubuntu 18.04 with a 1920x1080 display.  The problem happens more quickly if I add a second monitor and thereby increase the effective resolution.

I suspect this issue is due to one or more lost key frames, and that the probability of such loss increases with video resolution and/or network congestion.  Assuming that's correct, what is the intended behavior of gstwebrtc when key frames are lost?  Is there already code in place to handle this, or does something need to be added to GStreamer to support it properly? 

See also: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/799

**Comment by neilyoung** [comment]
@dicej I'm having that in a completely different scenario. The video is garbage after a while. No help so far

**Comment by ystreet** [comment]
webrtcbin only send and receives what you give it.  It cannot construct lost data or ask for new frames unless you tell it to using GstForceKeyUnit events: https://gstreamer.freedesktop.org/documentation/design/keyframe-force.html#upstream
