### ISSUE TITLE
Unable to stream camera in 720p resolution and above .

### ISSUE THREAD

**Issue by riteshkrmehta1** [centricular/gstwebrtc-demos#11]
I connected USB camera in PC browser side and opening https://webrtc.nirbheek.in  .
Using peer-id in other system trying  sendrecv demo app and able to stream . but the streaming received from browser side is always VGA (640x480).
How I can send 720p (1280x720) from https://webrtc.nirbheek.in browser based app ?
I also check in webrtc.js file where constraints = {video: true, audio: true}; there is no any width height settings . 
Please try to help how to solve this issue .

**Comment by nirbheek** [comment]
Which OS are you using? What browser are you using? Does your webcam support 720p? Is your browser capable of streaming 720p from your webcam?

**Comment by riteshkrmehta1** [comment]
Thanks for your valuable comments .
Os - linux
browser - google-chrome
Yes my webcam support 720p@30fps .
I confirm that my browser also support 720p streaming .
I use https://appr.tc/ and this browser app stream in 720p with my webcam.
I also check that in above appr.tc website 
mediaConstraints: {"audio": true, "video": {"optional": [{"minWidth": "1280"}, {"minHeight": "720"}], "mandatory": {}}}
but in ur webrtc.nirbheek.in website only constraints = {video: true, audio: true}; 
I am not sure that this is the actual problem but if u have any idea or suggestion please help.

**Comment by nirbheek** [comment]
Hmm, interesting, seems like browsers default to 640x480 unless you specify a different constraint. I tested that here: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#Result

So the best thing to do would be to allow people to override the default constraints. Adding this is non-trivial because currently we call getUserMedia() on page load, and I found it to be buggy if it was called "lazily" when an incoming call was detected.

**Comment by riteshkrmehta1** [comment]
Thanks for review . 
So, Can I expect update on website for 720p resolution support or I need to check some other ways .
@nirbheek By the way nice work on gstwebrtc .

**Comment by nirbheek** [comment]
I can't guarantee that I will have time to work on it, but you can try it out yourself by cloning the repository, editing webrtc.js, and opening index.html in your browser. You will also need to run the signalling server on your computer, or you can edit the WebSocket server url in `websocketServerConnect()` to make it point to webrtc.nirbheek.in unconditionally.

**Comment by riteshkrmehta1** [comment]
Ok , I will check by myself and I hope that will work for me .
thanks again .
