### ISSUE TITLE
cannot compile on vs 2017 missing include soup.h json-glib.h

### ISSUE THREAD

**Issue by DanielRourke** [centricular/gstwebrtc-demos#114]
i have tried to use the demos and...
#include <libsoup/soup.h>
#include <json-glib/json-glib.h>
 includes cannot find theses files and not listed in external dependencies

I am running windows 10, visual studio 2017 and gstreamer version 1.16.0

my steps so far
download and install
gstreamer-1.0-devel-mingw-x86-1.16.0.msi
gstreamer-1.0-mingw-x86-1.16.0.msi

new project consle app visualC++
view/Other Windows/Property Manager
right click solution
add existin property sheet
C:\gstreamer\1.0\x86\share\vs\2010\libs\gstreamer-1.0.props

go back to solution viewer
right click project
Properties
Debugging
Change working directory to
$(GSTREAMER_1_0_ROOT_X86)/bin

**Comment by PATO-SOFT** [comment]
I have the same problem but in Gstreamer `1.14.0`.
I'm trying to compile webrtc demo using `x86` libraries.
I checked folder `./x86/bin` and `./x86/lib`. 
Libraries that seems to be missing in visualstudio exists in correct folders.

**Comment by PATO-SOFT** [comment]
Well, as I suspected, the problem is related to visual studio configuration.
You have to include some directories to make it compilable. To fix it goto: 
`Project Properties -> C\C++ -> General -> Additional Include Directories`.

Click `Edit -> New Line ` and add paths similar to listed below:
```
C:\gstreamer\1.0\x86\include\json-glib-1.0
C:\gstreamer\1.0\x86\include\libsoup-2.4
```
Includes should to find specyfied files now.

**Comment by DanielRourke** [comment]
Including the files worked however i got alot of 
LNK2019 errors for json and soup functions

Is there an additional step i am missing to link the files ?

**Comment by PATO-SOFT** [comment]
Please, make sure that your solution configuration settings match with used library (x64/x86).

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
