### ISSUE TITLE
Testing C demo with Janus: a=ssrc and bundling streams

### ISSUE THREAD

**Issue by lminiero** [centricular/gstwebrtc-demos#119]
Hi all,

I tried playing with the C demo in order to get it working with Janus, so as a quick hack I replaced the existing WS signalling in `webrtc-sendrecv.c` to use the Janus API instead, and have it "call" the EchoTest plugin to test the incoming/outgoing media.

I was happy to see that ICE and DTLS seemed to work nicely (I remember someone reporting DTLS issues in the past, so I guess those were solved), but I found a few issues, and wanted to figure out if it was me doing something wrong:

1. It looks like `webrtcbin` isn't bundling the streams, and still tries to use different ports for audio and video. I thought that's what the `max-bundle` policy was supposed to enforce, but that didn't seem to help. I noticed the same happens when talking to browsers as well. Unfortunately, we removed support for non-bundled sessions in Janus long ago, which means that this currently only works for the first m-line, while not for the others. If this isn't supported in `webrtcbin` at the moment, then people interested in getting it to work with Janus will need separate PeerConnections for audio and video.
2. There's no `a=ssrc` line in the generated SDP, even when I specify one in `rtpopuspay` and `rtpvp8pay`. I guess this may be related to the point above: if you always assume audio and video go on separate connections, then the peer is supposed to use the ICE streams/components to demultiplex. Again, unfortunately this doesn't work for Janus, as we bundle everything (there's a single ICE stream and a single ICE component), and so can't demultiplex traffic if we don't know the SSRC and if the peer doesn't include the `mid` RTP extension (which it doesn't look like `webrtcbin` is adding). As a hack, I munged the SDP string myself before sending it to add some manual `a=ssrc` lines with the SSRCs I was enforcing, and that got it working, even though only for the first m-line as explained above.

Apart from these constraints, I found the API very clean and easy to use, so kudos to you guys for that!

**Comment by sdroege** [comment]
Which version of GStreamer are you testing with? Here's an example SDP from a WebRTC session with Chrome. This is the offer sent by GStreamer to Chrome. Is GStreamer or Janus creating the offer in your case?

```sdp
v=0
o=- 4815259276897865324 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 97 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:dnUFg8ifDB4jGbpU+tgTRnHcvmIh04RO
a=ice-pwd:3NuOu/pcVcln0JVRZbsCy2u/PZhEKyT3
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=framerate:30
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=97
a=ssrc-group:FID 50510378 2026053593
a=ssrc:50510378 msid:user1536429144@host-75a6cc39 webrtctransceiver0
a=ssrc:50510378 cname:user1536429144@host-75a6cc39
a=ssrc:2026053593 msid:user1536429144@host-75a6cc39 webrtctransceiver0
a=ssrc:2026053593 cname:user1536429144@host-75a6cc39
a=mid:video0
a=fingerprint:sha-256 BF:B3:52:12:54:5B:9C:59:F2:52:36:F4:E2:E6:E8:E9:38:C1:0A:8E:49:27:1B:1C:1C:8F:FB:8A:FA:3A:EE:FA
```

**Comment by sdroege** [comment]
Ah the `ssrc` lines are currently only added when RTX is enabled, or if we don't have a `recvonly` transceiver but the examples are only creating `recvonly` transceivers.

**Comment by lminiero** [comment]
I'm adapting the sendrecv demo so it's gstreamer that offers.

I wasn't aware of the RTX property, that's indeed helpful, thanks! What about bundling on the gstreamer send side instead? Is that indeed not supported yet?

**Comment by lminiero** [comment]
As to the gstreamer version, I was using the one available in the Fedora 28 repos: `gstreamer1-1.14.1-2.fc28`. I guess there may be more recent ones available, but I'd have to update the distro first to get those updates, as FC28 isn't updated anymore now.

**Comment by sdroege** [comment]
Independent of that, I can confirm that with the Rust example at least the `a=group:BUNDLE video0 audio1` line is added to the SDP if `policy` is set to `max-bundle` and there's always the `mid` attribute too.

Can you share a testcase to reproduce your problem, or share the SDPs that are exchanged at least?

@ystreet @MathieuDuponchelle How is this supposed to work exactly with the `ssrc` attribute, shouldn't those lines be added to the SDP in any case?

**Comment by sdroege** [comment]
> As to the gstreamer version, I was using the one available in the Fedora 28 repos: `gstreamer1-1.14.1-2.fc28`. I guess there may be more recent ones available, but I'd have to update the distro first to get those updates, as FC28 isn't updated anymore now.

I'd recommend re-testing with 1.16, bundle was not supported in any useful way in 1.14 if I remember correctly.

**Comment by lminiero** [comment]
> Independent of that, I can confirm that with the Rust example at least the `a=group:BUNDLE video0 audio1` line is added to the SDP if `policy` is set to `max-bundle` and there's always the `mid` attribute too.

The lines are there, but separate ports are still used for audio and video on the gstreamer side.

> I'd recommend re-testing with 1.16, bundle was not supported in any useful way in 1.14 if I remember correctly.

That's probably it then, thanks! I'll try again as soon as I update my distro. I'll close for now (I probably won't be abe to update before a couple of weeks), and reopen if it's still an issue there. Thanks again for the help!

**Comment by MathieuDuponchelle** [comment]
> I'd recommend re-testing with 1.16, bundle was not supported in any useful way in 1.14 if I remember correctly.

confirmed

**Comment by lminiero** [comment]
I finally managed to find time to update my distro, and gstreamer as a consequence. I can confirm that with gstreamer `1.16.0` (the version available in Fedora 30), bundling seems to be working as expected!

There still seems to be a bug, though. When bundling, it looks like `webrtcbin` sets the port for the second m-line to `0`. This results in that m-line to be rejected, or set to inactive. If I manually "munge" the SDP to set that port to, e.g., `9`, then everything works as expected. Is there a reason why the port is sert to `0` in that case? Please let me know if you want me to open a new issue for this, or if it is indeed a known issue and addressed already.

**Comment by ystreet** [comment]
If you're specifying 'max-bundle' that's the expected behaviour according to the specification.

https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54 (referenced from https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26) Section 7.2:

> If the offerer wants to request that the answerer accepts a given bundled "m=" section only if the answerer keeps the "m=" section within the negotiated BUNDLE group, the offerer MUST:
>    o  Include an SDP 'bundle-only' attribute [Section 7.2.1] in the "m=" section; and
>    o  Assign a zero port value to the "m=" section

Secion 7.3 (answers) also contains a bullet point:
>    o  Include an SDP 'bundle-only' attribute in, and assign a zero port value to, every other bundled "m=" section within the BUNDLE group; and

**Comment by lminiero** [comment]
Got it. I thought that property was needed to ensure gstreamer would bundle media, but removing it got it to work without munging. Sorry for the noise.

**Comment by lminiero** [comment]
It still feels weird that the specification mandates setting a port to 0 for m-lines in any scenario, though, especially considering the way WebRTC transceivers work on the client side now...

**Comment by sdroege** [comment]
On 30 July 2019 11:41:17 EEST, Lorenzo Miniero <notifications@github.com> wrote:
>It still feels weird that the specification mandates setting a port to
>0 for m-lines in any scenario, though, especially considering the way
>WebRTC transceivers work on the client side now...

I wouldn't be surprised if the spec and the implementation diverged, and the spec stays behind. The joys of "standards" where basically everybody works on the same, single implementation.

Someone will need to compare what chrome actually does nowadays with the spec.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
