### ISSUE TITLE
Not working in Android Mobile google-chrome browser 

### ISSUE THREAD

**Issue by riteshkrmehta1** [centricular/gstwebrtc-demos#12]
Can u please tell me whether  webrtc.nirbheek.in  is tested in Android mobile chrome browser ?
I tried with Android mobile chrome browser .
PROBLEMS :-   Able to send streaming to other device but not able to receive from other device to the mobile.
Please suggest any ways to solve this .

**Comment by nirbheek** [comment]
It works fine for me (both directions) with Google Chrome on Android 8.1.0. 

You can try opening `chrome://webrtc-internals` in another tab while this is going on, it should give some hints as to what's going wrong. The equivalent in Firefox is `about:webrtc`.

**Comment by riteshkrmehta1** [comment]
Thanks for update .
Can u confirm that which CODEC is used in your mobile to device streaming . 
Is it VP8 or VP9 ??
Because I am trying with H264 Codec and its not working with android mobile google-chrome browser .
Error log in browser :- 
Status: OperationError: Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..

**Comment by nirbheek** [comment]
I used the demo as-is, so it used vp8.

**Comment by riteshkrmehta1** [comment]
Thanks for info. Yes , This is problems with H264 encoding and decoding  with android mobile browser.
But i have a doubt we can get information in browser using chrome://webrtc-internals . But when I start https://webrtc.nirbheek.in/ and connect to other device its shows only sending information in webrtc-internals 
like :- ssrc_3843419078_send (ssrc)
ssrc_840248426_send (ssrc)
But if I start a different web app https://appr.tc/?vrc=h264&debug=loopback&vsc=h264 and join its shows all information sending and receiving as well. like :- 
ssrc_2473571747_send (ssrc)
ssrc_1845550198_send (ssrc)
ssrc_2473571747_recv (ssrc)
ssrc_1845550198_recv (ssrc)
so, can you tell we why this type of behaviour in your web browser app. because both web app doing same thing sending and receiving . are you missing anything in your browser please let me know .
Above query help me to debug why H264 encoding and decoding not working in  my android mobile browser .

**Comment by ystreet** [comment]
There's probably a H.264 profile/level mismatch between what the Android browser supports and what is being sent.  Have you tried forcing the baseline H.264 profile?

In any case, this is a result of a modification of the sample -> closing.
