### ISSUE TITLE
gst-rust can't connect to WebSocket

### ISSUE THREAD

**Issue by zizhengtai** [centricular/gstwebrtc-demos#120]
I'm on macOS 10.14.5 and have installed all the GStreamer plugins via Homebrew. I cloned this repo, went into the `sendrecv/gst-rust` directory and compiled it successfully with `cargo build`. However, when I tried to do `cargo run -- --peer-id=x` where `x` is the ID I got from https://webrtc.nirbheek.in/, the program failed with the following output:
```
Connecting to server wss://webrtc.nirbheek.in:8443
Error: WebSocketError(IoError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))
```

The Python example works fine though, so I doubt it's a Firewall issue. Could you provide some insights on what might be the cause here? Let me know if you need more debug info.

**Comment by sdroege** [comment]
Can you check with wireshark what it actually tries to do there and attach the capture as pcap/pcapng file? Only the communication with `webrtc.nirbheek.in` / 176.58.110.251 / 2a01:7e00::f03c:91ff:feae:244 is of interest here.

**Comment by zizhengtai** [comment]
I attached two captures below. It seems there are some connection reset thing going on, but I'm really not familiar with this area so I'll leave it to you to take a look. Thanks!

[gst-rust-pcapng.zip](https://github.com/centricular/gstwebrtc-demos/files/3391802/gst-rust-pcapng.zip)

**Comment by sdroege** [comment]
It's trying to connect to the IPv6 address and that gives "Connection refused". @nirbheek that's one for you :)

Why the `ws` crate does not try to connect to the IPv4 address afterwards is a good question though. I've forwarded the issue [there](https://github.com/housleyjk/ws-rs/issues/281), let's see what they say. Thanks for reporting.

**Comment by zizhengtai** [comment]
@sdroege, doesn't the example code use [`websocket`](https://github.com/websockets-rs/rust-websocket) instead of `ws`?

**Comment by sdroege** [comment]
:man_facepalming: Yes. See https://github.com/websockets-rs/rust-websocket/issues/237

**Comment by nirbheek** [comment]
The server now listens on ipv4 and ipv6. I've pushed a commit that makes this the default: https://github.com/centricular/gstwebrtc-demos/commit/da27e5940b53c16dbb6687a07de5998d08adca63
