### ISSUE TITLE
check_if_negotiation_is_needed: assertion failed:

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#126]
Hi,

I am using the Java-Api.

During the createAnswer and setting the localDescription. I am receiving the message below:

`ERROR:gstwebrtcbin.c:1150:_check_if_negotiation_is_needed: assertion failed: (trans->mline < gst_sdp_message_medias_len (webrtc->current_local_description->sdp))`

```
	public static int gotMessageFromServer(String message) {
		
		//String offer = obj.getAsJsonObject("sdp").get("type").getAsString();
		JsonObject obj = new JsonParser().parse(message).getAsJsonObject();
				
		if(obj.get("uuid").getAsString().contentEquals(uuid)) {
			System.out.println("We got our message broadcasted");
			return 0;
		}
		
		if(obj.getAsJsonObject("sdp") != null ) {
			System.out.println("Its SDP");
			String type = obj.getAsJsonObject("sdp").get("type").getAsString();
			if(type.contentEquals("offer")) {
				
				  String sdpStr = obj.get("sdp").toString();
				  SDPMessage sdpMessage = new SDPMessage();
	              sdpMessage.parseBuffer(sdpStr);	        
	              //WebRTCSessionDescription description = new WebRTCSessionDescription(WebRTCSDPType.OFFER, sdpMessage);
	              webRTCBin.setRemoteDescription(new WebRTCSessionDescription(WebRTCSDPType.OFFER, sdpMessage));
	              webRTCBin.createAnswer(onAnswerCreated);
			}
		}
		
		if(obj.getAsJsonObject("ice") != null) {
			System.out.println("its ICE");
			String iceCandidate = obj.getAsJsonObject("ice").get("candidate").getAsString();
			int sdpMLineIndex = obj.getAsJsonObject("ice").get("sdpMLineIndex").getAsInt();
			webRTCBin.addIceCandidate(sdpMLineIndex, iceCandidate);
		}
		
		return 1;
	}
	
	
    private static CREATE_ANSWER onAnswerCreated = Answer ->{
    	webRTCBin.setLocalDescription(Answer);
    };
```

**Comment by ghost** [comment]
Syntax is correct. Would be great to see the content of  

```
SDPMessage sdpMessage = new SDPMessage();
```

or even `sdpStr`. There must be a problem.

**Comment by ghost** [comment]
Maybe you provide `Answer` as well...

**Comment by polhaghverdian** [comment]
> Syntax is correct. Would be great to see the content of
> 
> ```
> SDPMessage sdpMessage = new SDPMessage();
> ```
> 
> or even `sdpStr`. There must be a problem.

SDP-STRING: below is 'sdpStr'

{"type":"offer","sdp":"v=0\r\no=mozilla...THIS_IS_SDPARTA-68.0.1 3556043801947181689 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 6B:DF:57:8F:86:75:86:95:7E:BE:4E:72:44:28:2B:C8:33:BB:71:9D:78:62:11:31:62:52:D5:BA:99:ED:1D:BA\r\na=group:BUNDLE 0 1 2\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101\r\nc=IN IP4 0.0.0.0\r\na=recvonly\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:101 0-15\r\na=ice-pwd:215615c98e7192970371f49be72662b0\r\na=ice-ufrag:58fe266c\r\na=mid:0\r\na=rtcp-mux\r\na=rtpmap:109 opus/48000/2\r\na=rtpmap:9 G722/8000/1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:101 telephone-event/8000\r\na=setup:actpass\r\na=ssrc:3349707625 cname:{dedb7488-455b-4f20-b054-50f3012a5850}\r\nm=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97\r\nc=IN IP4 0.0.0.0\r\na=recvonly\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:toffset\r\na=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1\r\na=fmtp:120 max-fs=12288;max-fr=60\r\na=fmtp:121 max-fs=12288;max-fr=60\r\na=ice-pwd:215615c98e7192970371f49be72662b0\r\na=ice-ufrag:58fe266c\r\na=mid:1\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120 ccm fir\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 goog-remb\r\na=rtcp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:126 goog-remb\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-mux\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:121 VP9/90000\r\na=rtpmap:126 H264/90000\r\na=rtpmap:97 H264/90000\r\na=setup:actpass\r\na=ssrc:2212479484 cname:{dedb7488-455b-4f20-b054-50f3012a5850}\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:215615c98e7192970371f49be72662b0\r\na=ice-ufrag:58fe266c\r\na=mid:2\r\na=setup:actpass\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n"}

SDP-MESSAGE: t=0 0

String sdpStr = obj.get("sdp").toString();
SDPMessage sdpMessage = new SDPMessage();
sdpMessage.parseBuffer(sdpStr);
System.out.println("SDP-STRING: " + sdpStr);
System.out.println("SDP-MESSAGE: " +sdpMessage );

**Comment by polhaghverdian** [comment]
Something wrong with the; sdpMessage.parseBuffer(sdpStr); because this was the only output after the parseBuffer ( t=0 0 )

**Comment by ghost** [comment]
Well, not sure if it makes a difference, but this is my code and it works well:

```
  private void handleMessage(String data) {
    
        try {
            JSONObject message = new JSONObject(data);

            if (message.has("sdp")) {
                String sdpStr = ((JSONObject) message.get("sdp")).getString("sdp");
                String type = ((JSONObject) message.get("sdp")).getString("type");
                if (type.equalsIgnoreCase("answer")) {
                    SDPMessage sdpMessage = new SDPMessage();
                    sdpMessage.parseBuffer(sdpStr);
                    WebRTCSessionDescription description = new WebRTCSessionDescription(WebRTCSDPType.ANSWER, sdpMessage);
                    webRTCBin.setRemoteDescription(description);
                } else {
                    if (type.equalsIgnoreCase("offer")) {
                        SDPMessage sdpMessage = new SDPMessage();
                        sdpMessage.parseBuffer(sdpStr);
                        WebRTCSessionDescription description = new WebRTCSessionDescription(WebRTCSDPType.OFFER, sdpMessage);
                        webRTCBin.setRemoteDescription(description);
                        webRTCBin.createAnswer(onAnswerCreated);
                    } 
                }
            } else if (message.has("ice")) {
                String candidate = ((JSONObject) message.get("ice")).getString("candidate");
                int sdpMLineIndex = ((JSONObject) message.get("ice")).getInt("sdpMLineIndex");
                webRTCBin.addIceCandidate(sdpMLineIndex, candidate);
           }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
 }


```


```
private WebRTCBin.CREATE_ANSWER onAnswerCreated = answer -> {
        webRTCBin.setLocalDescription(answer);
        // following code to forward the answer to remote via signalling server
};

```

**Comment by polhaghverdian** [comment]
@accuware Thank you!🙂

**Comment by sdroege** [comment]
This can be closed then? What was the actual problem in the end?
