### ISSUE TITLE
Create an outgoing stream?

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#127]
Hi,

Looking at the java code example, it seems to be only for receiving a stream. Any guidance to how i suppose to create an outgoing stream? 

I want to stream in this direction: gst -> browser,

i am using the same VIDEO_BIN_DESCRIPTION as the example:

`videotestsrc ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! queue ! capsfilter caps=application/x-rtp,media=video,encoding-name=VP8,payload=97`

```
            logger.info("onIncomingDecodebinStream video");
            Element queue = ElementFactory.make("queue", "my-videoqueue");
            Element videoconvert = ElementFactory.make("videoconvert", "my-videoconvert");
            Element autovideosink = ElementFactory.make("autovideosink", "my-autovideosink");
            pipe.addMany(queue, videoconvert, autovideosink);
            queue.syncStateWithParent();
            videoconvert.syncStateWithParent();
            autovideosink.syncStateWithParent();
            pad.link(queue.getStaticPad("sink"));
            queue.link(videoconvert);
            videoconvert.link(autovideosink);
``` 

Any help would be appreciated.

**Comment by yvvarun** [comment]
Hi,

I have a similar requirement. I am trying to use GStreamer for acting as a WebRTC server which will receiver offers from multiple browser clients and -
1. Create answers to the offers.
2. Push video/audio to the clients. 
Were you trying to do something similar? If so, could you help me out with how you went about doing it?

Thank you.

**Comment by polhaghverdian** [comment]
> Hi,
> 
> I have a similar requirement. I am trying to use GStreamer for acting as a WebRTC server which will receiver offers from multiple browser clients and -
> 
> 1. Create answers to the offers.
> 2. Push video/audio to the clients.
>    Were you trying to do something similar? If so, could you help me out with how you went about doing it?
> 
> Thank you.

I changed from java to C. And realized that it’s better to create offer as the “server”, than creating offer from the browser.

**Comment by yvvarun** [comment]
Okay. When does the server decide to create offer?

**Comment by polhaghverdian** [comment]
> Okay. When does the server decide to create offer?

It depends on the application. I am starting the stream from my webapplication, through websocket.

WebApplication sends start to --> Gstreamer
Gstreamer creates the offer and sends the offer through the server to the webbrowser

Also as far i know, its hard to adjust the offer on the browser side. For example if you want create an offer with H264, you have to manipulate the SDP-Offer before you send it to Gstreamer.

**Comment by yvvarun** [comment]
Got it. And would this work when there are multiple browsers trying to connect to the same GStreamer application?

**Comment by polhaghverdian** [comment]
Yes it will work, but you would need to create a new stream for each browser.

**Comment by easonyang** [comment]
you can try multi-gst in the demo




| |
xpyang
邮箱：xpyang2016@163.com
|

Signature is customized by Netease Mail Master

On 11/19/2019 23:28, Pol Haghverdian wrote:

Yes it will work, but you would need to create a new stream for each browser.

**Comment by yvvarun** [comment]
Oh okay, I'll try multi-gst.
Thanks for the help!
