### ISSUE TITLE
nice_agent_parse_remote_candidate_sdp: assertion 'sdp != NULL' failed

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#128]
I am getting following message bellow, during reconnection.
`
(gst1-java-core:14304): libnice-CRITICAL **: 23:19:29.965: nice_agent_parse_remote_candidate_sdp: assertion 'sdp != NULL' failed`

Is this because i dont check if the sdp-message is null when arriving from the signal-server?

**Comment by tankienleong** [comment]
@polhaghverdian  I also faced the same problem. May I know did you able to solve it?
