### ISSUE TITLE
h264 issue with native webrtc(Android, iOS)

### ISSUE THREAD

**Issue by owpqwo** [centricular/gstwebrtc-demos#130]
I created webrtc offer sdp for connecting with other webrtc clients(chrome, android, iOS).
with chrome client, it works fine. I can see the video on chrome browser without any errors.
but when I try to connecting with android or iOS which is implemented by using native webrtc.
I got errors that "No video codec supported(this is because of H264)".
I found some different about h264 between gstreamer sdp and android sdp for creating offer sdp.

gstreamer sdp offer:
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=fmtp:96 packetization-mode=1;profile-level-id=42801f;sprop-parameter-sets=Z01AHqaAoD2mwEA=,aO48gA==

native webrtc and chrome sdp offer:
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

I don't know about attributes (level-asymmetry-allowed, profile-level-id, sprop-parameter-sets).  I'm not sure but, i think because of this I'm getting error.

is there anybody tested gstreamer webrtc(h264) connecting with android or ios???

**Comment by 1happyboy** [comment]
hello
       I also encountered the same problem. The communication on the wen end is normal, but the h264 does not match when communicating with android and ios. Do you have a solution? Can you tell me something?

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
