### ISSUE TITLE
Video freeze after a few seconds on Raspbian

### ISSUE THREAD

**Issue by emreturkay** [centricular/gstwebrtc-demos#131]
I am running the signalling server & browser on macos and webrtc-sendrecv on raspberry pi, the video plays for a few seconds and then freeze. The audio & video on the browser keeps playing and the audio on the raspberry pi is also playing; only the video on the raspberry pi is frozen.

For some reason "autovideosink" breaks the X on raspberry pi therefore I have changed it with "ximagesink" (and also with "glimagesink" in a separate test -- both have the freeze problem), i.e.,

sendrecv/gst/webrtc-sendrecv.c:
  --    handle_media_stream (pad, pipe, "videoconvert", "autovideosink");
  ++    handle_media_stream (pad, pipe, "videoconvert", "ximagesink");

Executing the simple-server with --disable-ssl option;
$ ./simple-server.py --disable-ssl

The JS is served via;
$ python -m SimpleHTTPServer 8080

And in the JS code I have replaced "wss://" with "ws://", i.e.,
sendrecv/js/webrtc.js:
  --    var ws_url = 'wss://' + ws_server + ':' + ws_port
  ++    var ws_url = 'ws://' + ws_server + ':' + ws_port

I am launching the webrtc-sendrecv as below:
$ ./webrtc-sendrecv --disable-ssl --server=ws://192.168.20.2:8443 --peer-id=6390

GStreamer version on Raspberry Pi is 1.15.2 (compiled manually).

Any comments?

A part of the error log of webrtc-sendrecv which might be interesting;

0:00:10.013022686  1017  0x1604b20 ERROR            omxvideodec gstomxvideodec.c:1735:gst_omx_video_dec_loop:<omxvp8dec-omxvp8dec0> No corresponding frame found
0:00:10.013111384  1017  0x1604b20 DEBUG         GST_SCHEDULING gstpad.c:4324:gst_pad_chain_data_unchecked:<src_0:proxypad35> calling chainfunction &gst_proxy_pad_chain_default with buffer buffer: 0x71026848, pts 99:99:99.999999999, dts 99:99:99.999999999, dur 99:99:99.999999999, size 115200, offset none, offset_end none, flags 0x0
0:00:10.013178623  1017  0x1604b20 DEBUG               GST_PADS gstpad.c:3814:do_probe_callbacks:<decodebin1:src_0> data is passed
0:00:10.012985498  1017 0x7021f200 DEBUG        rtpjitterbuffer gstrtpjitterbuffer.c:2521:calculate_packet_spacing:<rtpjitterbuffer0> new packet spacing 0:00:00.019998283 old packet spacing 0:00:00.019996225 combined to 0:00:00.019997768
0:00:10.013258103  1017  0x1604b20 DEBUG         GST_SCHEDULING gstpad.c:4324:gst_pad_chain_data_unchecked:<queue8:sink> calling chainfunction &gst_queue_chain with buffer buffer: 0x71026848, pts 99:99:99.999999999, dts 99:99:99.999999999, dur 99:99:99.999999999, size 115200, offset none, offset_end none, flags 0x0
0:00:10.013348363  1017  0x1604b20 DEBUG         GST_SCHEDULING gstpad.c:4330:gst_pad_chain_data_unchecked:<queue8:sink> called chainfunction &gst_queue_chain with buffer 0x71026848, returned ok
0:00:10.013363259  1017 0x71a0de00 DEBUG         queue_dataflow gstqueue.c:1528:gst_queue_loop:<queue8> queue is not empty
0:00:10.012304560  1017  0x16b8e90 DEBUG              GST_CLOCK gstclock.c:1092:gst_clock_get_internal_time:<GstSystemClock> internal time 0:18:39.119959901
0:00:10.013469405  1017 0x71a0de00 DEBUG         GST_SCHEDULING gstpad.c:4324:gst_pad_chain_data_unchecked:<videoconvert1:sink> calling chainfunction &gst_base_transform_chain with buffer buffer: 0x71026848, pts 99:99:99.999999999, dts 99:99:99.999999999, dur 99:99:99.999999999, size 115200, offset none, offset_end none, flags 0x0
0:00:10.013515447  1017  0x16b8e90 DEBUG              GST_CLOCK gstclock.c:1137:gst_clock_get_time:<GstSystemClock> adjusted time 0:18:39.119959901
0:00:10.013527217  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:1999:default_submit_input_buffer:<videoconvert1> handling buffer 0x71026848 of size 115200, PTS 99:99:99.999999999 and offset NONE
0:00:10.013557947  1017  0x1604b20 DEBUG         GST_SCHEDULING gstpad.c:4330:gst_pad_chain_data_unchecked:<src_0:proxypad35> called chainfunction &gst_proxy_pad_chain_default with buffer 0x71026848, returned ok
0:00:10.013623259  1017 0x71a0de00 DEBUG                default gstsegment.c:737:gst_segment_to_running_time_full: invalid position (-1)
0:00:10.013678832  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:2111:default_generate_output:<videoconvert1> calling prepare buffer
0:00:10.013707582  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:1614:default_prepare_output_buffer:<videoconvert1> using pool alloc
0:00:10.013743311  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:1754:default_copy_metadata:<videoconvert1> copying metadata
0:00:10.013709770  1017  0x1604b20 DEBUG            omxvideodec gstomxvideodec.c:1842:gst_omx_video_dec_loop:<omxvp8dec-omxvp8dec0> Finished frame: ok
0:00:10.013790030  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:1721:foreach_metadata:<videoconvert1> not copying memory specific metadata GstVideoMetaAPI
0:00:10.013827999  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:2118:default_generate_output:<videoconvert1> using allocated buffer in 0x71026848, out 0x730cc2b8
0:00:10.013853936  1017 0x71a0de00 DEBUG          basetransform gstbasetransform.c:2138:default_generate_output:<videoconvert1> doing non-inplace transform
0:00:10.013745134  1017  0x16b8e90 DEBUG              GST_CLOCK gstsystemclock.c:714:gst_system_clock_id_wait_jitter_unlocked: entry 0x71a08540 time 0:18:33.936847359 now 0:18:39.119959901 diff (time-now) -5183112542
0:00:10.013909978  1017 0x71a0de00 DEBUG        GST_PERFORMANCE gstvideoconvert.c:712:gst_video_convert_transform_frame:<videoconvert1> doing colorspace conversion from I420 -> to BGRx
0:00:10.013966228  1017  0x1604b20 DEBUG                    omx gstomx.c:1607:gst_omx_port_acquire_buffer:<omxvp8dec-omxvp8dec0> Acquiring video_decode buffer from port 131
0:00:10.014057374  1017  0x1604b20 DEBUG                    omx gstomx.c:1735:gst_omx_port_acquire_buffer:<omxvp8dec-omxvp8dec0> video_decode port 131 has pending buffers
0:00:10.014128676  1017  0x1604b20 DEBUG                    omx gstomx.c:1749:gst_omx_port_acquire_buffer:<omxvp8dec-omxvp8dec0> Acquired buffer 0x511390b8 (0x6c7be450) from video_decode port 131: 0
0:00:10.014280864  1017  0x1604b20 DEBUG               GST_CAPS gstpad.c:2705:gst_pad_has_current_caps:<omxvp8dec-omxvp8dec0:src> check current pad caps video/x-raw, format=(string)I420, width=(int)320, height=(int)240, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)0/1
0:00:10.014358468  1017  0x1604b20 DEBUG                    omx gstomx.c:1985:gst_omx_port_is_flushing:<omxvp8dec-omxvp8dec0> video_decode port 131 is flushing: 0
0:00:10.014418364  1017  0x1604b20 DEBUG            omxvideodec gstomxvideodec.c:1713:gst_omx_video_dec_loop:<omxvp8dec-omxvp8dec0> Handling buffer: 0x00000010 (end-of-frame) 8875600
0:00:10.014501124  1017  0x1604b20 ERROR            omxvideodec gstomxvideodec.c:1735:gst_omx_video_dec_loop:<omxvp8dec-omxvp8dec0> No corresponding frame found

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
