### ISSUE TITLE
localhost: Too many connection attempts, aborting. Refresh page to try again

### ISSUE THREAD

**Issue by jagernicolas** [centricular/gstwebrtc-demos#135]
Hi,
I build the docker image,
```
$ docker build -t nginx_webrtc .
```
and run a container,
```
$ docker run --name docker-nginx -p 8443:8443 -p 80:80 nginx_webrtc
```
but when I try to connect from my browser (firefox), I got:
```
Status: Too many connection attempts, aborting. Refresh page to try again
```
I tried to connect using ``http://localhost/`` ``http://127.0.0.1/`` ``http://172.17.0.2/`` (last one is container ip over docker network)
I tried using the host machine and another on my local network
everytime I got the same error.

![DeepinScreenshot_20190929110451](https://user-images.githubusercontent.com/15674244/65834443-ecfe9080-e2a8-11e9-9466-01a53530becc.png)

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
