### ISSUE TITLE
https://webrtc.nirbheek.in/ : Too many connection attempts, aborting. Refresh page to try again

### ISSUE THREAD

**Issue by jagernicolas** [centricular/gstwebrtc-demos#137]
Hi guys,
two weeks ago I was using https://webrtc.nirbheek.in/ for my tests, now it just don' t work anymore...

should be related to issue: https://github.com/centricular/gstwebrtc-demos/issues/135

am I the only one who got that issue ? because I tried from several laptops at home and from my cellphone using my LTE...

![DeepinScreenshot_20191009195332](https://user-images.githubusercontent.com/15674244/66528570-5f077e80-eace-11e9-9cd5-af5b8c3e970b.png)

**Comment by thaytan** [comment]
I've only seen that when doing repeated calls without reloading the web-page. Eventually it runs out of connection attempts. Your problem might be related to not being able to establish the call properly over LTE or through a firewall?

**Comment by jagernicolas** [comment]
have you even just try by yourself ?  https://webrtc.nirbheek.in/

as said, it was working two weeks ago. that said, I wasn't talking about call. This issue concern only connecting the signaling server. Both of my test LTE/WiFi gives the same error when I connect,

and now, at work using my professional laptop, I got the same error...

**Comment by thaytan** [comment]
Ah I see - yes, it looks like one of the LetsEncrypt certs needs renewing. It expired on the 29th Sep

**Comment by thaytan** [comment]
Nirbheek fixed the cert. Thanks for pointing it out.

**Comment by menmitsu** [comment]
@thaytan : Looks like the same error is back. Might be a minor cert issue?

**Comment by nirbheek** [comment]
Someone has been DoSing the server (intentionally or unintentionally) by opening thousands of connections to it. I've restored it and I'm working on a more permanent fix.
