### ISSUE TITLE
Windows - VAAPI & NVENC

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#138]
Hi,

Is there a reason for not including intel-vaapi and nvenc plugins for windows? How do i install those plugins?
 
Any help will be appreciated.

Am using 
- gstreamer-1.0-devel-mingw-x86_64-1.16.0

- gstreamer-1.0-mingw-x86_64-1.16.0

**Comment by sdroege** [comment]
This is not a support forum and also not the project providing the GStreamer binaries. You want to ask at https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel

(VAAPI is Linux-only, nvenc can't be easily included with 1.16 but will likely be included with 1.18)
