### ISSUE TITLE
Not really an issue : Little hint to handle multiple stream from gstreamer on a single webpage

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#14]
Hi again, 

I have been able to use your demo with my webcam on a localnetwork everything is working fine, thank to you.

I'm now looking to enhance your demo.

My goal is to handle multiple gstreamer "stream" in a single webpage. But i'm not sure this is actually "possible".

I have though that i can handle multiple gstream "stream" if i can make a list of them. Each entry of my list could have a "video element" linked to the stream.

Let's say i have 3 stream

Each one would have a video element that "read" the stream.

I'm don't know if this could be achived by webRTC and your demo. 

At least thank you guys your work is awesome 

Sypsô

**Comment by nirbheek** [comment]
Multiple streams on a single page require you to have multiple PeerConnection instances. One for each stream.

There is nothing gstreamer-specific involved on the browser end.

**Comment by nirbheek** [comment]
Closing, please reopen if you have other questions regarding this.
