### ISSUE TITLE
_connect_rtpfunnel: assertion failed: (stream)

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#141]
Hi,

when using Firefox for receiving video VP8, i get below error:

`_connect_rtpfunnel: assertion failed: (stream)`

With Debug level 6 for webrtc i also get: 
`16924 00000205F33F2280 INFO               webrtcbin gstwebrtcbin.c:3532:_set_description_task:<sendrecv> Attempting to set local answer in the have-remote-offer state`

But using Chrome browser works. 

Any idea why Chrome works and not with firefox?

**Comment by polhaghverdian** [comment]
I changed my implementation, i was creating the offer from the client (browser) . Now i redid so that the gstreamer makes the offer and the browser answer instead. Solved alot problems.

**Comment by D1plo1d** [comment]
I am using your demo as a reference and ran into this issue creating offers from the client (browser). This is my first time using gst. Do you have any ideas why this is happening/where to start with debugging?
