### ISSUE TITLE
Can't get sound on iOS on Safari

### ISSUE THREAD

**Issue by Jackovic** [centricular/gstwebrtc-demos#143]
Hello,
I use Gstreamer and webrtcbin element to get an audio stream on different browsers. It is OK to receive the stream on :
- Ubuntu 18.04 with Firefox, Chromium and Chrome
- Android 8.1.0 with Firefox and Chrome

But, impossible to get it on iOS with Safari.

Is there anything specific to do for this system to make it work ?
Thanks.
++

Jack

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
