### ISSUE TITLE
Change SDP: from sendrecv to sendonly?

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#144]
Is it possible to change the sdp from sendrecv to sendonly?

below is my current SDP: 

Sending offer:
```
v=0
o=- 6286354800210458220 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1 application2
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:3fnnzKQLcvADstjKVkzIozZ8ef4hXGlh
a=ice-pwd:4v7Jlar4UFC33RIB+45H13HsUqSranHQ
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:30
a=fmtp:96 packetization-mode=1;profile-level-id=42c028;sprop-parameter-sets=Z0LAKNwHgCJ+XAWoCAgKAAADAAIAAAMAeR4wZw==,aM48gA==
a=ssrc:3542043503 msid:user3616844700@host-77112646 webrtctransceiver0
a=ssrc:3542043503 cname:user3616844700@host-77112646
a=mid:video0
a=fingerprint:sha-256 1A:4B:71:D6:0A:FA:02:E4:50:4C:53:D0:34:E6:14:CC:8B:5E:46:62:CC:23:25:41:4F:91:AC:B2:63:92:0D:E4
m=audio 0 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:3fnnzKQLcvADstjKVkzIozZ8ef4hXGlh
a=ice-pwd:4v7Jlar4UFC33RIB+45H13HsUqSranHQ
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:97 OPUS/48000/2
a=rtcp-fb:97 nack pli
a=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0
a=ssrc:2774551217 msid:user3616844700@host-77112646 webrtctransceiver1
a=ssrc:2774551217 cname:user3616844700@host-77112646
a=mid:audio1
a=fingerprint:sha-256 1A:4B:71:D6:0A:FA:02:E4:50:4C:53:D0:34:E6:14:CC:8B:5E:46:62:CC:23:25:41:4F:91:AC:B2:63:92:0D:E4
m=application 0 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:3fnnzKQLcvADstjKVkzIozZ8ef4hXGlh
a=ice-pwd:4v7Jlar4UFC33RIB+45H13HsUqSranHQ
a=bundle-only
a=mid:application2
a=sctp-port:5000
a=fingerprint:sha-256 1A:4B:71:D6:0A:FA:02:E4:50:4C:53:D0:34:E6:14:CC:8B:5E:46:62:CC:23:25:41:4F:91:AC:B2:63:92:0D:E4
```

**Comment by ystreet** [comment]
You would need to access the transceiver that is created on pad creation and set it's direction manually to force sendonly in an offer.

**Comment by easonyang** [comment]
who have ran mp-webrtc-sendrecv.c ? It seems not to work in sendrecv mode.

At 2019-11-06 17:53:02, "Matthew Waters" <notifications@github.com> wrote:


You would need to access the transceiver that is created on pad creation and set it's direction manually to force sendonly in an offer.

**Comment by polhaghverdian** [comment]
> 
> 
> You would need to access the transceiver that is created on pad creation and set it's direction manually to force sendonly in an offer.

I cant find  "on pad creation" as a signal from the webrtcbin doc. Should i use **get-transceiver** instead? 

https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c#webrtcbin::get-transceiver

**Comment by ystreet** [comment]
Yes, that should work if you `get-transceiver` before you create any SDP's.  What also works is connecting to the `GstElement::pad-added` signal: https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c#webrtcbin::pad-added

**Comment by polhaghverdian** [comment]
> 
> 
> Yes, that should work if you `get-transceiver` before you create any SDP's. What also works is connecting to the `GstElement::pad-added` signal: https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c#webrtcbin::pad-added

Thank you. I solved it 👍 
```

	// ADD - RTP_TRANSCEIVER_DIRECTION
	GArray* transceivers;
	GstWebRTCRTPTransceiver* transceiver;
	g_signal_emit_by_name(webrtc1, "get-transceivers", &transceivers);
	transceiver = g_array_index(transceivers, GstWebRTCRTPTransceiver*, 0);
	transceiver->direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;
```

Sending offer:
```
v=0
o=- 7633954386828823784 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1 application2
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:znxuvNlhaWYQ17QDWAuWr18nw81VXcdv
a=ice-pwd:FZdM3mAnWlTFNT7yNd/aQBmLRnROBawT
a=rtcp-mux
a=rtcp-rsize
a=sendonly
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:30
a=fmtp:96 packetization-mode=1;profile-level-id=42c028;sprop-parameter-sets=Z0LAKNoB4AiflwFqAgICgAAAAwCAAAAeR4wZUA==,aM48gA==
a=ssrc:2557035831 msid:user1599639323@host-e8753692 webrtctransceiver0
a=ssrc:2557035831 cname:user1599639323@host-e8753692
a=mid:video0
a=fingerprint:sha-256 7F:74:F1:9E:11:F1:5F:C1:25:3D:96:64:FF:8A:4A:CC:51:BF:4D:69:1E:C3:64:A6:03:AB:69:CF:E0:EA:AA:F9
m=audio 0 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:znxuvNlhaWYQ17QDWAuWr18nw81VXcdv
a=ice-pwd:FZdM3mAnWlTFNT7yNd/aQBmLRnROBawT
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:97 OPUS/48000/2
a=rtcp-fb:97 nack pli
a=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0
a=ssrc:2647863353 msid:user1599639323@host-e8753692 webrtctransceiver1
a=ssrc:2647863353 cname:user1599639323@host-e8753692
a=mid:audio1
a=fingerprint:sha-256 7F:74:F1:9E:11:F1:5F:C1:25:3D:96:64:FF:8A:4A:CC:51:BF:4D:69:1E:C3:64:A6:03:AB:69:CF:E0:EA:AA:F9
m=application 0 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:znxuvNlhaWYQ17QDWAuWr18nw81VXcdv
a=ice-pwd:FZdM3mAnWlTFNT7yNd/aQBmLRnROBawT
a=bundle-only
a=mid:application2
a=sctp-port:5000
a=fingerprint:sha-256 7F:74:F1:9E:11:F1:5F:C1:25:3D:96:64:FF:8A:4A:CC:51:BF:4D:69:1E:C3:64:A6:03:AB:69:CF:E0:EA:AA:F9
```

**Comment by hexray-newbee** [comment]
How to apply in python demo?

**Comment by thaytan** [comment]
The equivalent is something like:
trans = self.webrtc.emit('get-transceiver', 0)
trans.direction = GstWebRTC.WebRTCRTPTransceiverDirection.SENDONLY

**Comment by hexray-newbee** [comment]
> The equivalent is something like:
> trans = self.webrtc.emit('get-transceiver', 0)
> trans.direction = GstWebRTC.WebRTCRTPTransceiverDirection.SENDONLY

    trans.direction = GstWebRTC.WebRTCRTPTransceiverDirection.SENDONLY
RuntimeError: field is not writable

refer：https://lazka.github.io/pgi-docs/GstWebRTC-1.0/classes/WebRTCRTPTransceiver.html#fields

**Comment by hexray-newbee** [comment]
Is GstWebRTC.WebRTCRTPTransceiver.direction writable in version 1.18?
refer: https://gstreamer.freedesktop.org/documentation/webrtclib/gstwebrtc-transceiver.html?gi-language=python#GstWebRTCRTPTransceiver:direction

**Comment by thaytan** [comment]
Ah. You should be able to set it via the property:
trans.set_property ('direction', GstWebRTC.WebRTCRTPTransceiverDirection.SENDONLY)

**Comment by hexray-newbee** [comment]
> Ah. You should be able to set it via the property:
> trans.set_property ('direction', GstWebRTC.WebRTCRTPTransceiverDirection.SENDONLY)

TypeError: object of type `WebRTCTransceiver' does not have property `direction'

**Comment by thaytan** [comment]
Doh! Sorry - it's a property in git master, to match the WebRTC spec. In 1.16, there was the set_direction() method.
