### ISSUE TITLE
Rust Build Issues on OSX

### ISSUE THREAD

**Issue by PaulIPS** [centricular/gstwebrtc-demos#145]
Hi I am trying to build the rust send receive sample on OSX 10.14. I am using GStreamer 16.1 and have installed  the runtime and the developer tools. 

When I run `cargo build` I get the following error: 
`library not found for -lgstwebrtc-1.0`

Is there something else needed for building on OSX?

**Comment by sdroege** [comment]
Did you install GStreamer via homebrew or from the binaries that are available from the GStreamer website? I would recommend the GStreamer binaries, and you need the setup steps from https://gitlab.freedesktop.org/gstreamer/gstreamer-rs#installation-macos then.

Make sure to run `cargo clean` after setting the environment variable.

If that still doesn't work, please provide the output of `cargo build -vvv` after `cargo clean`

**Comment by PaulIPS** [comment]
@sdroege yes I did use the binaries from the GStreamer website. The `pkg-config ` step was what I was missing. Thank you for the help! I got the rust sample building now.

**Comment by sdroege** [comment]
Thanks, shout if you run into other problems :)
