### ISSUE TITLE
noise issue(opus audio) with native webrtc(android)

### ISSUE THREAD

**Issue by owpqwo** [centricular/gstwebrtc-demos#146]
is anybody get success with webrtc on chrome browser?

I tried using webrtcbin. source audio is g711 and I decoded it to opus.
everything is working fine but there is some noise so I cannot hear the sound properly because of some noise.

mypipeline = webrtcbin rtspsrc url=xxx.xxx.xx.xxx ! rtppcmudepay ! mulawdec ! opusenc ! opusparse ! rtpopuspay

and offer SDP is 
a=rtpmap:111 OPUS/48000/2
a=rtcp-fb:111 nack pli
a=fmtp:111 sprop-maxcapturerate=8000;sprop-stereo=0

and answer SDP is
a=rtpmap:111 OPUS/48000/2
a=fmtp:111 minptime=10;useinbandfec=1

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
