### ISSUE TITLE
C Sample videoconvert Seg Fault on OSX

### ISSUE THREAD

**Issue by PaulIPS** [centricular/gstwebrtc-demos#147]
When running the C sample on OSX I am getting a `Segmentation fault: 11` after `handle_media_stream` is called. 

This is what I am seeing in Terminal: 

> data channel opened
> data channel opened
> Received data channel message: Hi! (from browser)
> Received data channel message: Hi! (from browser)
> Received data channel message: Hi! (from browser)
> Received data channel message: Hi! (from browser)
> Trying to handle stream with videoconvert ! autovideosinkTrying to handle stream with audioconvert ! autoaudiosinkSegmentation fault: 11

I am running OSX 10.14.and GStreamer 16.1. Any sugestions on how I can fix or debug this?

**Comment by ystreet** [comment]
Run the code in a debugger (`lldb` on macos) and/or grab a gstreamer debug log of some description.  See https://gstreamer.freedesktop.org/documentation/gstreamer/running.html?gi-language=c for the `GST_DEBUG` environment variable.  Depending on where you downloaded or built GStreamer from, this may be a known issue.
