### ISSUE TITLE
gst_dtls_connection_process: runtime check failed: (!priv->bio_buffer)

### ISSUE THREAD

**Issue by polhaghverdian** [centricular/gstwebrtc-demos#148]
For some reason in Chrome i sometimes get below **Warnings**, are those issues related? Problem is that the stream never start. When i execute twice it works suddenly. 

`00:17:51.304: (../ext/dtls/gstdtlsconnection.c:530):gst_dtls_connection_process: runtime check failed: (!priv->bio_buffer)`

This issue also includes: 

`0:00:01.212603100 11576 0000028FAB447E40 WARN               webrtcice gstwebrtcice.c:619:gst_webrtc_ice_add_candidate:<webrtcice0> Could not parse candidate 'a=candidate:1666101572 1 udp 2113937151 c942a318-8cf3-44d6-81b6-0081ac6ab378.local 58597 typ host generation 0 ufrag 9R38 network-cost 999'`

**Comment by polhaghverdian** [comment]
Please any help will be appreciated.

**Comment by thaytan** [comment]
Not handling mDNS ICE candidates is a known issue. Chrome started using these recently. If there's another candidate pair that works, you should still be able to establish a connection reliably.

I remember people complaining about the DTLS connection warnings in 1.14, but I think that was fixed. I haven't seen it recently. Which GStreamer version are you on?

**Comment by polhaghverdian** [comment]
@thaytan Yes the stream works, but i dont like to get those error messages. I have tried both 1.16, 1.16.1 and 1.16.2

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
