### ISSUE TITLE
Trying to replace the "simple-server" with a nodeJS signaling server with websocket

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#15]
If you have any advice, or hint to do this it would be awesome.

I have a read that the signalling server could be replace by another signalling server. But i have no idea of how i can achieve this, and if the python server is handling some logic ! 

Actually i'm trying to replace the python server with a server from "https://www.webrtc-experiment.com/
" websocket-over-nodejs " ssl.js file.

I'm really struggling to adapt the python code in javascript code.

For example : How can i get  raddr = ws.remote_address (python) in javascript ?

I'm looking for good documentation and hints i don't ask you do my job. I know it will be hard for me to achive this.  But i have plenty of time =) 

So if you can help me by giving good documentation on websocket for nodejs / python, or giving steps / hints. It would be very kind

Sypsô

**Comment by nirbheek** [comment]
If you want to implement your own signalling server, you need to know:

1. What websockets are
2. How a websocket server works in whatever library you're using
3. Implement the [protocol used by the demos](https://github.com/centricular/gstwebrtc-demos/blob/master/signalling/Protocol.md).

You might find it useful to start with this: https://github.com/shanet/WebRTC-Example/ to understand (1) and (2).

**Comment by ghost** [comment]
Thank you Nirbheek i start working on your link now :)

**Comment by ghost** [comment]
Ok, so far i have been able to do the HELLO part of the protocol, i also been able to create a map that handle the differents informations of the peers connected to the signalling server. 

But a new question cross my mind. I don't open a new issues, cause i think it's a bit boring to have someone new to coding opening 1545 issues ! 

My question is since the release of gstreamer-1.14.0 and webrtcbin, are we able to replace all the webrtc-sendrecv.c in a single pipeline started by a terminal ?

Can we avoid to do an .c file ? 

Because i want to control the gstreamer pipeline from a node.js server. So if we can control all the WebRTC (sdp,ice) from a single pipeline. I think i'm able to handle the pipeline with node.js

With a gst-inspect-1.0 i have found a lot of option such as "add-ice-candidate", or "set-remote-description" are these option enough to send data to a signalling server. or do you need to "wrap" this in a .c program ?

Edit 16h26 :  Ok i think the answer is "yes". That lead to another question, are you going to make a documentation for this "API" or do we need to "deep-dive" into the code to understand how everything is working ?

**Comment by r4zzz4k** [comment]
The sole purpose of `webrtc-sendrecv.c` is to show client-side example which uses WebRTC via GStreamer APIs. As you can see, apart from multimedia stuff there are other parts there, like WebSocket connection handling the protocol. While probably doable via bash and some shell utilities, it's highly inconvenient to implement it that way.

On the bright side, GStreamer can be used not only by C and `gst-inspect` (which to my knowledge deals only with building pipeline, without general-purpose signalling). You can use any language which has proper [bindings](https://gstreamer.freedesktop.org/bindings/).

The documentation you're asking is already provided by developer as it's merged into the GStreamer docs. You can use [this](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/gst-plugins-bad-plugins-plugin-webrtc.html) as a starting point. To use it from other languages like Python, you'll have to learn basic concepts behind GObject type system (this is generally the case for all the stuff like Gtk+, GStreamer as a whole, GDBus, etc). Check [Wiki page](https://en.wikipedia.org/wiki/GObject) on it, which should be good starting point. Then you'll be able to adopt C-based docs with your favorite tooling in mind.

All in all, I feel like this stuff is out of scope of this specific project, so if you need further assistance, you'll probably have to switch to StackOverflow or specific forums. Project maintainers, of course, can correct me on that.

**Comment by nirbheek** [comment]
> On the bright side, GStreamer can be used not only by C and gst-inspect (which to my knowledge deals only with building pipeline, without general-purpose signalling).

Yes, you cannot dynamically create or modify pipelines through `gst-inspect-1.0`. In this case, as I described in [my blog post](http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html), you need to connect to various signal handlers to provide SDP and ICE to the pipeline, and also dynamically handle incoming media in `pad-added`.

This cannot be done from the command-line.

> All in all, I feel like this stuff is out of scope of this specific project, so if you need further assistance, you'll probably have to switch to StackOverflow or specific forums

The [gstreamer-devel mailing list](https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel) is also a good place for asking such questions.

As for using gstreamer through node.js, it is possible in theory to generate JS bindings for GStreamer with gobject-introspection data, but I don't know if anyone has tried this yet. I would recommend using C, Python, or Rust for this.

Note that your signalling server does not have to also be the multimedia server (which uses gstreamer). The two are usually separate.

**Comment by rebotnix** [comment]
Interesting..Is there a way to build a webrtc pipeline via command line params?

The only example i saw is to compile a C example program. I would like to test if its possible to stream a video file to a own signal webrtc server session with command line:

**Comment by nirbheek** [comment]
> Interesting..Is there a way to build a webrtc pipeline via command line params?

No, there isn't. You need to provide callbacks to fill in SDP and ICE (`on-negotiation-needed`, `on-ice-candidate`, `add-ice-candidate`, etc) and also handle the incoming streams with the `pad-added` callback.
