### ISSUE TITLE
Required gstreamer plugin 'opus' not found

### ISSUE THREAD

**Issue by chcmq** [centricular/gstwebrtc-demos#150]
I have compiled opus, but the Required gstreamer plugin 'opus' is not found

**Comment by thaytan** [comment]
It's not clear what you've compiled here. As well as the libopus library, you need the GStreamer Opus plugin from gst-plugins-base. There's not usually a need to compile it.

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
