### ISSUE TITLE
fail to streaming rtsp [JAVA]

### ISSUE THREAD

**Issue by caserzer** [centricular/gstwebrtc-demos#151]
I changed the video source in the JAVA demo to
"rtspsrc location=rtsp://xxxxxx ! rtph264depay ! avdec_h264 ! vp8enc deadline=1 ! rtpvp8pay ! capsfilter caps=application/x-rtp,media=video,encoding-name=VP8,payload=97 ! webrtcbin=sendrecv "
but I cannot view the video on the page.
and if I did not append "webrtcbin=sendrecv" I will get this error
[gstreamer service thread 1] ERROR WebrtcSendRecv - Error from source: 'Bin: [rtspsrc0]', with code: 1, and message 'Internal data stream error.'

**Comment by chriswiggins** [comment]
You'll likely need an h264parse in your pipeline:

`rtspsrc location=rtsp://xxxxxx ! rtph264depay ! h264parse ! avdec_h264 ! vp8enc deadline=1 ! rtpvp8pay ! capsfilter caps=application/x-rtp,media=video,encoding-name=VP8,payload=97 ! webrtcbin=sendrecv `

**Comment by caserzer** [comment]
thanks @chriswiggins . after add the h264parse , I am able to view the demo, but I cannot see the view the video (blank in the html ) but hear the test sound. Do you have any suggestion?

**Comment by caserzer** [comment]
@nirbheek would you please help

**Comment by caserzer** [comment]
The C demo works.
