### ISSUE TITLE
Issue capturing audio on iOS

### ISSUE THREAD

**Issue by PaulIPS** [centricular/gstwebrtc-demos#152]
Hi, I am trying to create a native iOS application that uses gstreamer for WebRTC.

I am having an issue accessing the microphone using gstreamer on iOS. 

The following pipeline is working properly on me for OSX:
`autoaudiosrc ! audioconvert ! audioresample ! audioconvert ! autoaudiosink`

But on iOS I get the following error when setting the pipeline state to "Ready" and no audio is played back:
`[aurioc] 921: failed: -10851 (enable 1, outf< 2 ch,      0 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)`

I am using:
* Gstreamer 1.16.1
* Xcode 11
* iOS 11, and iOS 13

Is there a better plugin for capturing audio on iOS?

**Comment by PaulIPS** [comment]
I found a fix: 

I had to set the AVAudioSession.sharedInstance category to AVAudioSessionCategoryPlayAndRecord inside my application before trying to start the pipeline.

**Comment by tp-m** [comment]
Thanks for letting us know, but this is not really related to the webrtc demos at all, so best to continue the discussion in the [upstream ticket you filed](https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/480)
