### ISSUE TITLE
 iOS WebRTC pipline "streaming stopped, reason not-linked (-1)"

### ISSUE THREAD

**Issue by PaulIPS** [centricular/gstwebrtc-demos#153]
Hi, 

I am trying to make an iOS application that streams video and audio over WebRTC. 

Here is the pipeline I am using on iOS: 
> webrtcbin bundle-policy=max-bundle name=sendrecv 
> stun-server=stun:/(url):(port)  turn-server=turn://(user)@(url):(port) 
> videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! queue ! application/x-rtp,media=video,encoding-name=VP8,payload=96 ! sendrecv.
> audiotestsrc is-live=true wave=red-noise ! audioconvert ! audio/x-raw, format=S16LE, channels=2 ! audioresample ! queue ! opusenc ! rtpopuspay ! queue ! 
> application/x-rtp, media=audio, channels=2, encoding-name=OPUS, payload=97 ! sendrecv.

The ice and sdp messages seam to be working properly, but I am getting the following error when the stream starts to send: 

> ../libs/gst/base/gstbasesrc.c(3072): gst_base_src_loop (): GstPipeline:pipeline0/GstWebRTCBin:sendrecv/TransportReceiveBin:transportreceivebin0/GstNiceSrc:nicesrc0:
> streaming stopped, reason not-linked (-1)

I am using:
Gstreamer 1.16.1
Xcode 11
iOS 13

I was also seeing the same issue using the camera, and microphone from iOS. I switched the pipelines to use "videotestsrc" and "audiotestsrc" since their sources I can confirm work in the webrtc pipeline on Linux using the C library. Since my pipeline is working on Linux but failing on iOS I am thinking it might be something iOS related. 

Any idea how to debug for fix this? Also if this is not the proper place for this question, please let me know where I should ask it. 

Thank you, 
Paul

**Comment by thaytan** [comment]
I think this points to some needed plugins not being linked in (and webrtc not properly reporting that they are missing). As well as webrtc and nice, you should have the dtls sctp and srtp plugins linked in

**Comment by PaulIPS** [comment]
@thaytan Thank you for the suggestion. 

I checked that  webrtc, nice, dtls, sctp, and srtp are included with `#define GST_IOS_PLUGINS_NET` which I had included. 

I also went ahead and included every define in `gst_ios_init.h`: 

```
#define GST_IOS_PLUGINS_CORE
#define GST_IOS_PLUGINS_CODECS
#define GST_IOS_PLUGINS_ENCODING
#define GST_IOS_PLUGINS_NET
#define GST_IOS_PLUGINS_PLAYBACK
#define GST_IOS_PLUGINS_VIS
#define GST_IOS_PLUGINS_SYS
#define GST_IOS_PLUGINS_EFFECTS
#define GST_IOS_PLUGINS_CAPTURE
#define GST_IOS_PLUGINS_CODECS_GPL
#define GST_IOS_PLUGINS_CODECS_RESTRICTED
#define GST_IOS_PLUGINS_NET_RESTRICTED
#define GST_IOS_PLUGINS_GES

#define GST_IOS_GIO_MODULE_GNUTLS
```

Unfortunitly I am still receiving the same error.

**Comment by thaytan** [comment]
Hmm, OK. If it's working on Linux and you have all the WebRTC plugins installed, then I'm not sure where that's coming from.

**Comment by PaulIPS** [comment]
So this gets strange... 

To double check there are no missing plugins issues we use a little code snippet to print out all plugins in our iOS build: 

```
void printplugin (gpointer data, gpointer user)
{
    g_print("%s\n", gst_plugin_get_name((GstPlugin*)data));
}

// Which can be used like this: 
GList * test = gst_registry_get_plugin_list(gst_registry_get());
g_list_foreach(test, (GFunc)printplugin, NULL);
```

Which cleaned up gave us this list of plugins (I bolded the 5 needed for WebRTC): 

> accurip
> adder
> adpcmdec
> adpcmenc
> aiff
> alaw
> alpha
> alphacolor
> apetag
> app
> applemedia
> audiobuffersplit
> audioconvert
> audiofx
> audiofxbad
> audiomixer
> audioparsers
> audiorate
> audioresample
> audiotestsrc
> auparse
> autoconvert
> autodetect
> avi
> bayer
> cairo
> closedcaption
> coloreffects
> compositor
> coreelements
> coretracers
> cutter
> dashdemux
> debug
> debugutilsbad
> deinterlace
> **dtls**
> dtmf
> dv
> dvbsuboverlay
> dvdspu
> effectv
> equalizer
> fieldanalysis
> flac
> flv
> flxdec
> freeverb
> frei0r
> gaudieffects
> gdkpixbuf
> gdp
> geometrictransform
> gio
> hls
> icydemux
> id3demux
> id3tag
> imagefreeze
> inter
> interlace
> interleave
> isomp4
> ivorbisdec
> ivtc
> jpeg
> jpegformat
> kate
> ladspa
> lame
> legacyrawparse
> level
> matroska
> midi
> mpg123
> mulaw
> multifile
> multipart
> mxf
> **nice**
> ogg
> opengl
> openh264
> openjpeg
> opus
> opusparse
> osxaudio
> overlaycomposition
> pango
> pcapparse
> png
> pnm
> proxy
> rawparse
> removesilence
> replaygain
> rfbsrc
> rsvg
> rtp
> rtpmanager
> rtsp
> rtspclientsink
> sbc
> **sctp**
> sdpelem
> segmentclip
> shapewipe
> shm
> siren
> smooth
> smoothstreaming
> smpte
> soundtouch
> soup
> spandsp
> spectrum
> speed
> speex
> srt
> **srtp**
> staticelements
> subenc
> subparse
> taglib
> tcp
> theora
> typefindfunctions
> udp
> videobox
> videoconvert
> videocrop
> videofilter
> videofiltersbad
> videomixer
> videoparsersbad
> videorate
> videoscale
> videotestsrc
> volume
> vorbis
> vpx
> wavenc
> wavpack
> wavparse
> **webrtc**
> webrtcdsp
> y4mdec
> y4menc

So all the plugins need are there. 

Out of just trying random things I decide to just ignore all error callbacks that I registered for using: 
`g_signal_connect (G_OBJECT (bus), "message::error", (GCallback)error_cb, (__bridge void *)self);`

After days of trying I suddenly had a working WebRTC feed from iOS! 

I am still new to GStreamer, but ignoring errors seams wrong, especially since the official GStreamer iOS samples, end the pipeline when the `error_cb` gets hit. 

Any ideas on how I should proceed or should I just ignore the error?

**Comment by thaytan** [comment]
Is webrtcbin creating pads for incoming video/audio stream(s) and you're ignoring them perhaps? That would lead to not-linked errors indeed.
If your goal is to only send media and not receive, you should configure the transceivers as send-only

**Comment by PaulIPS** [comment]
@thaytan Yes iOS is sending only. So I actually taught about that after seeing your sendonly sample. I tried this but it didn't seam to make a difference: 

iOS Code for send only: 
```
GArray *transceivers;
GstWebRTCRTPTransceiver *trans;

g_signal_emit_by_name (webrtc, "get-transceivers", &transceivers);
trans = g_array_index (transceivers, GstWebRTCRTPTransceiver *, 0);
trans->direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;
```

C Code for recipe only: 
```
GArray *transceivers;
GstWebRTCRTPTransceiver *trans;
g_signal_emit_by_name (webrtc, "get-transceivers", &transceivers);

trans = g_array_index (transceivers, GstWebRTCRTPTransceiver *, 0);
trans->direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY;
```

The transceivers are found but I am still seeing the errors produced. Is there something I am missing in my code?

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
