### ISSUE TITLE
Send only example does not work for me

### ISSUE THREAD

**Issue by deep9** [centricular/gstwebrtc-demos#154]
Just built the code from master branch, it starts ok, but when trying to connect, there are errors in console and the video does not work at all.

![image](https://user-images.githubusercontent.com/1571715/72424211-e9264980-3785-11ea-9afd-f4385d512ed1.png)

Any hints on how to make it work, @thaytan ? Thanks.

**Comment by deep9** [comment]
Here is the program output

```
Processing new websocket connection 0x8c4950Creating negotiation offer

** (webrtc-unidirectional-h264:12790): CRITICAL **: 20:29:43.290: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (webrtc-unidirectional-h264:12790): CRITICAL **: 20:29:43.294: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (webrtc-unidirectional-h264:12790): CRITICAL **: 20:29:43.312: gst_dtls_agent_get_certificate_pem: assertion 'GST_IS_DTLS_CERTIFICATE (self->priv->certificate)' failed

** (webrtc-unidirectional-h264:12790): CRITICAL **: 20:29:43.313: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
Negotiation offer created:
v=0
o=- 1411723176507759111 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=msid-semantic:WMS webrtcbin
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:wmmc7XsOCNtnGjOTkU/OAREYmhv0nqJg
a=ice-pwd:f9cHdMxQrwxWyIyRaKW/OhgNK8/o6G/A
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:15
a=fmtp:96 packetization-mode=1;profile-level-id=42c016;sprop-parameter-sets=Z0LAFtoCgL/lwFqDAILSgAAAAwCAAAAPR4sXUA==,aM48gA==
a=ssrc:387231818 msid:user66781703@host-174d72d9 webrtctransceiver1
a=ssrc:387231818 cname:user66781703@host-174d72d9
a=mid:video0
a=fingerprint:sha-256 (null)

Closed websocket connection 0x8c4950
```

**Comment by deep9** [comment]
Found out that it is probably related to https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/811, so if I use `$ OPENSSL_CONF= ./webrtc-unidirectional-h264` it runs ok and handshake is there, but no video in browser anyway

**Comment by thaytan** [comment]
I had this code sitting here un-pushed for a while, and haven't tried it in a long time. It works for me in Firefox, but I notice has a refcounting bug to fix that's making it crash when the web-page exits.

For Chrome, the H.264 profile probably needs modifying (or munge the profile-level-id= in the SDP) to make it palatable. Or switch the pipeline to using VP8 output should work too.

**Comment by deep9** [comment]
@thaytan Great, thank you, I did try that previously in FF and it did not work, because of the OPENSSL problems, now it plays!
