### ISSUE TITLE
Data channel example with python

### ISSUE THREAD

**Issue by miguelwon** [centricular/gstwebrtc-demos#157]
Hi,
I have a working system based in the [webrtc-sendrecv.py](https://github.com/centricular/gstwebrtc-demos/blob/master/sendrecv/gst/webrtc-sendrecv.py) demo, where I stream video from my webcam. 

I'm now  I trying to include a data channel to the webrtc connection. Is there a python demo with such a feature?

**Comment by sdroege** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1172 has some example code

**Comment by miguelwon** [comment]
Ok, thanks. Do I need GStream 1.16? I currently have the 1.14 installed.

**Comment by sdroege** [comment]
I think datachannel support was new in 1.16, but more important there are some bugs with datachannel that only make it work reliable right now with the two MRs linked from the issue above.
