### ISSUE TITLE
Sendrecv not working in Chrome, only in safari

### ISSUE THREAD

**Issue by Moses0h** [centricular/gstwebrtc-demos#158]
I am using sendrecv and when i open up the index.html, I am able to connect to the local server (signalling). However, when I send an rtsp stream to the index.html using sendrecv/gst/webrtc-sendrecv.py, i only see the video on safari (for a few seconds and freezes) but nothing on chrome, internet explorer, or firefox. What can be causing this issue?

**Comment by thaytan** [comment]
Are you sending H.264?

**Comment by Moses0h** [comment]
Currently yes

**Comment by nirbheek** [comment]
You need to ensure that you're using the `baseline` or `constrained-baseline` profile with H.264. You need to check that the incoming RTSP stream is using that profile. If not, you need to decode and re-encode.

**Comment by Moses0h** [comment]
I see. Sorry the given sample sendrecv is not working on chrome. Just the videotestsrc (without using h264) is not showing on chrome. Currently have signaling Python server running locally, index.html opened waiting to receive call, and sendrecv.py running with the id shown on html. The connection is successful but no video shows

**Comment by miguelwon** [comment]
I'm having the same problem. I had a working environment about two months ago and now when I returned to the project it doesn't work in Chrome anymore. Then tried the  [webrtc_sendrecv.py ](https://github.com/centricular/gstwebrtc-demos/blob/master/sendrecv/gst/webrtc_sendrecv.py) and the same. Working in Safari but not Chrome. Checked if related to [this issue](https://github.com/centricular/gstwebrtc-demos/issues/166#issuecomment-600711918) but the problem remains. Any ideas or other reports about this issue?

**Comment by miguelwon** [comment]
Just an update. I have tested the ICE candidates generation with [Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) and the problem with Chrome remains. No ICE candidates are generated in Chrome. What is more odd is that Trickle ICE works fine when I use Chrome in incognito mode.

**Comment by thaytan** [comment]
are you testing on a local network? Perhaps you are running into https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1139 ?

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
