### ISSUE TITLE
gstwebrtc with rtcp

### ISSUE THREAD

**Issue by zombiecong** [centricular/gstwebrtc-demos#16]
Hi, 

Firstly thanks for this nice demos. I find the video becomes pixelated when packet lost , and I glance over the source code of [gstwebrtc](https://github.com/GStreamer/gst-plugins-bad/tree/master/gst-libs/gst/webrtc), it seems not handle the rtcp packet , is there something I missed? 

![a](https://user-images.githubusercontent.com/7962780/38859949-a5fb3226-4261-11e8-9d1e-b196099c1648.png)

**Comment by nirbheek** [comment]
Yes, you missed that the rtp and rtcp handling is done by [rtpbin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtpbin.html), which is used by webrtcbin for all transmit and receive.

There are a number of techniques to reduce video corruption on packet loss, such as FEC, intra-refresh, retransmission, and adaptive bitrate. Of these, you can currently try intra-refresh on x264enc. As far as I know, the rest are either not implemented, or [not fully implemented yet](https://bugzilla.gnome.org/show_bug.cgi?id=792696).

**Comment by zombiecong** [comment]
Thanks for quickly reply. So what's the reason caused video  pixelated ?Is there a way I can figure out it?

**Comment by nirbheek** [comment]
The reason is likely that the [iframe](https://en.wikipedia.org/wiki/Inter_frame) was lost, and so later frames couldn't find a reference to decode from, and the decoder tried to recover and display *something*.

One way to mitigate this is to use [Periodic Intra Refresh](http://www.chaneru.com/Roku/HLS/X264_Settings.htm#intra-refresh), but I am not sure if any browser implements it.

What is causing packet loss on your system? The mitigation also depends on that.

**Comment by zombiecong** [comment]
I use [facebook atc](http://facebook.github.io/augmented-traffic-control/) to simulate packet lost(5%-10%).
Really thanks , the reply is detailed.I will test it again recently.

**Comment by nirbheek** [comment]
In your case, you probably want FEC to compensate for that level of constant packet loss. Support for FEC in WebRTC not fully implemented in GStreamer yet, but the lower-level parts (RTP and RTCP) are implemented.

**Comment by tp-m** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=795044 might also be of interest
