### ISSUE TITLE
Python send-only example?

### ISSUE THREAD

**Issue by fnoop** [centricular/gstwebrtc-demos#162]
Hi, I've been trying to get a very simple scenario working now for a while without success:
 - Create a simple video 'server' that browsers can connect to and stream the video.  For example, use a Raspberry Pi with Raspberry Camera attached (or any similar device) to stream video to browsers, using python.

I've poured over the various examples and hacked code, but not got anything working.  Has anyone ever got something like this working?

**Comment by thaytan** [comment]
https://github.com/thaytan/gst-rpicamsrc/ has a send-only example specifically for the Raspberry Pi

**Comment by thaytan** [comment]
(not python though)

**Comment by hexray-newbee** [comment]
We cannot set sendonly until gst:1.18.
refer: https://github.com/centricular/gstwebrtc-demos/issues/144#issuecomment-590070423

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
