### ISSUE TITLE
handle the case of media.receiving == false

### ISSUE THREAD

**Issue by hexray-newbee** [centricular/gstwebrtc-demos#163]
https://github.com/centricular/gstwebrtc-demos/blob/b28e46c0d97cb28e945aa6bbd457c16f48dd0170/janus/janusvideoroom.py#L401

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
