### ISSUE TITLE
iOS WebRTC only working on a LAN

### ISSUE THREAD

**Issue by PaulIPS** [centricular/gstwebrtc-demos#164]
Currently I have an iOS application (client) that is streaming to a C application (server) over WebRTC using Gstreamer on both ends. The applications are working fine on a LAN but when I switch to a WAN, "pad-added" never gets called on iOS client or in C server for the bidirectional video feed. Checking our signaling server log I can see the ICE and SDP messages are being generated and sent when using there WAN. 

I am using Coturn at the STUN and TURN server. 

I am doubtful the Coturn is the issue because I have a C client application, and that has no issues communicating to our C
 server, on the LAN or WAN. I have also setup the original sendrecv demo to use our Coturn server and it works with no issues over the LAN and WAN. I am also doubtful the C server is the issue, since the same exact server code works with our C client over the wan. 

Possibly Relevant Information: 
Server is running Ubuntu 19.10 and Gstreamer 16.1
iOS is using Xcode 11, iOS 13 and Gstreamer 16.1
Coturn is version 4.5.1.1 on Ubuntu 19.10 

One interesting I noticed is on the server the version of lib nice is 0.1.14 and the version of lib nice on iOS is 0.1.15. I wonder if there can be a compatibility issue here. 

Any suggestions on how I can debug this?

**Comment by patrickcusack** [comment]
What happened with this?

**Comment by PaulIPS** [comment]
@patrickcusack This issue can probably help you. I will link you to a work around that worked for me. 

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1235#note_426872

Unfortunately I never got a chance to really dig in on why the work around worked, because the team I am on decided to go down a different path due to the issues we where having with gstreamer for our full use case. We are trying to do a lot more to it then just streaming video / audio over WebRTC.

**Comment by patrickcusack** [comment]
@Paul,

So you have been using gstreamer as a source via webRTC gateway to distribute content to iOS? Apart from other needs, what didn’t work on the audio / video side? I’m using gstreamer to stream to Janus, but I am curious if using a complete gstreamer solution would allow me to stream video and audio with ac3.

Patrick

**Comment by PaulIPS** [comment]
@patrickcusack In our use case we are streaming audio and video from iOS to a server over WebRTC. We had gstreamer setup on both sides. The server was a C gstreamer application. 

What ended up being the final straw with the WebRTC approach was we need to get the producers (iOS) capture time. While Webrtcbin get-stats should include this information it looks like  DOMHighResTimeStamp was not being filled in on the iOS side.
