### ISSUE TITLE
Establishing datachannel fails between gst peers (gst communication with firefox works)

### ISSUE THREAD

**Issue by martinangel** [centricular/gstwebrtc-demos#165]
I am using the sendrecv sample code to have datachannel full-duplex communication.

With the Firefox peer sendrecv code perfectly works (video, audio and datachannel). However, If I use sendrecv code as the basis for both peers video/audio works, but datachannel is never opened. I get the same nice-related error notified here #100 for the datachannel:

```
> 0:00:02.786068723 [333m10130[00m 0x7f81cc009b20 [33;01mLOG    [00m [00m            nicesink gstnicesink.c:265:gst_nice_sink_render_buffers:<nicesink0>[00m 1 buffers, 1 memories -> to be sent
> 0:00:02.786119917 [333m10130[00m 0x7f81cc009b20 [33;01mLOG    [00m [00m             srtpenc gstsrtpenc.c:1178:gst_srtp_enc_process_buffer:<srtpenc0:rtp_sink_0>[00m Encoding RTP buffer of size 24
> 0:00:02.786320206 [333m10130[00m 0x7f81fc084190 [33;01mLOG    [00m [00m             nicesrc gstnicesrc.c:199:gst_nice_src_read_callback:<NiceAgent@0x7f821000d690>[00m Got buffer, getting out of the main loop
> 0:00:02.786353545 [333m10130[00m 0x7f81fc084190 [33;01mLOG    [00m [00m             nicesrc gstnicesrc.c:299:gst_nice_src_create:<nicesrc0>[00m Got buffer, pushing
> 0:00:02.786394168 [333m10130[00m 0x7f81fc084190 [33;01mWARN   [00m [00m             basesrc gstbasesrc.c:3072:gst_base_src_loop:<nicesrc0>[00m error: Internal data stream error.
> 0:00:02.786407626 [333m10130[00m 0x7f81fc084190 [33;01mWARN   [00m [00m             basesrc gstbasesrc.c:3072:gst_base_src_loop:<nicesrc0>[00m error: streaming stopped, reason not-linked (-1)
> 0:00:02.786467720 [333m10130[00m 0x7f81fc084190 [33;01mWARN   [00m [00m               queue gstqueue.c:988:gst_queue_handle_sink_event:<queue2>[00m error: Internal data stream error.
> 0:00:02.786480384 [333m10130[00m 0x7f81fc084190 [33;01mWARN   [00m [00m               queue gstqueue.c:988:gst_queue_handle_sink_event:<queue2>[00m error: streaming stopped, reason not-linked (-1)
> 0:00:02.786520489 [333m10130[00m 0x7f81cc009b20 [33;01mLOG    [00m [00m            nicesink gstnicesink.c:265:gst_nice_sink_render_buffers:<nicesink0>[00m 1 buffers, 1 memories -> to be sent
> 0:00:02.786615148 [333m10130[00m 0x7f81cc009b20 [33;01mLOG    [00m [00m             srtpenc gstsrtpenc.c:1178:gst_srtp_enc_process_buffer:<srtpenc0:rtp_sink_0>[00m Encoding RTP buffer of size 1410
```

To this end, I am using master version of gst-plugins-bad.

I manually removed this commit*:
[make the video flow not working also with the Firefox peer](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/commit/0c72a417670c396f63f04fd5d3fd830c91799596)

I manually removed (setter of _SCTP_REUSE_PORT_) from this commit**:
[produce error in the socket creation _Could not set SCTP_REUSE_PORT_](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/commit/26a6b175937fe3b0fece6fb98f623a51c7c905d0)

Thank you a lot in advance.

I am using Ubuntu 18.04 + GStreamer 1.16.2 + Gst-Plugins-Bad Master* ** + UsrSctp Master

**Comment by martinangel** [comment]
Solved, the problem is that I have to take into account the SEND_ONLY, RECV_ONLY or SEND_RECV when creating the pipeline and declaring the transceivers:

```
  GstWebRTCRTPTransceiverDirection direction;
  GstWebRTCRTPTransceiver *trans;
  GArray *transceivers;
...
  webrtc1 = gst_bin_get_by_name (GST_BIN (pipe1), "sendrecv");
  g_assert_nonnull (webrtc1);

  // setting video sendonly transceiver
  g_print("setting video transceiver\n");
  g_signal_emit_by_name (webrtc1, "get-transceivers", &transceivers);
  g_assert (transceivers != NULL && transceivers->len > 0);
  trans = g_array_index (transceivers, GstWebRTCRTPTransceiver *, 0);
  trans->direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;
```

**Comment by thaytan** [comment]
Does that mean everything is working OK with GStreamer git master without reverting commits now?

**Comment by martinangel** [comment]
Hi @thaytan , with the master copy the video never starts. However, the data channel works.

**Comment by thaytan** [comment]
There's something strange going on there to figure out then. I've been testing with both Firefox and Chrome with GStreamer git master very recently

**Comment by martinangel** [comment]
I made further tests meanwhile and this commit breaks video when 2 GST peers communicate (without browser), but a GST communication with a Firefox peer works:
[gstdtlsrtpenc: Add rtp-sync property](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/commit/0c72a417670c396f63f04fd5d3fd830c91799596)

**Comment by thaytan** [comment]
I used the Rust sendrecv client to register with nirbheek's server:

`cargo run`

and then ran the sendrecv example:

`./build/sendrecv/gst/webrtc-sendrecv --peer-id=PEER_ID_FROM_RUST`

and that worked OK, showing video windows from both clients (with GStreamer git master)

Are you doing uni-directional transmission, or something else different to the existing sample code?
