### ISSUE TITLE
sendonly example hangs, but no errors reported?

### ISSUE THREAD

**Issue by floe** [centricular/gstwebrtc-demos#166]
The sendonly example (`webrtc-unidirectional-h264`) would be ideal for my usecase, but I can't get it to work, neither with Chrome nor with Firefox. In both cases, the SDP negotiation seems to complete and the Gstreamer pipeline is successfully launched, but no stream appears in the browser and both processes just seem to idle.
Neither the terminal nor the browser console show any errors. I'm testing on localhost, with firewall disabled, so there shouldn't be any network issues? Or should I just disable STUN entirely for this scenario?

**Comment by floe** [comment]
P.S. I already tried with `OPENSSL_CONF=""` as suggested in #154, but no success either.

**Comment by thaytan** [comment]
Which version of GStreamer are you testing with?

**Comment by thaytan** [comment]
I just tested and it's working here to firefox OK, but not to Chrome (which was working last time I tried). That's probably about the H.264 profile-level-id, Chrome can be very fussy. It accepts the stream, and the chrome://webrtc-internals/ shows frames being received and decoded, they just don't make it to the window for some reason.

I'm not sure what to look at for Firefox to figure out why that's working for me but not you.

**Comment by floe** [comment]
I'm using Gstreamer 1.14 on Ubuntu 18.04. I just got it to work with Firefox, it looks like the issue was indeed related to the STUN server not being reached (firewall). I didn't know about webrtc-internals, I'll check that with Chrome.

Related question: if I know I'll stay within the local network, I should be able to get rid of STUN entirely, right?

**Comment by floe** [comment]
OK, I dug a bit more, and the underlying reason why it doesn't work locally is that Firefox now doesn't use local IP addresses anymore, but random mDNS addresses (see https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/). However, on Firefox, the mDNS addresses don't resolve properly. :-( Meh.

On Chrome, the mDNS addresses work as intended, but there it's apparently the codec thingy that's messing things up. Meh again ;-)

**Comment by floe** [comment]
Stupid question, but where in webrtc-internals should I actually look? RTCTransport_video0_1 (transport) shows `dtlsState: connecting` and no data being sent?

**Comment by floe** [comment]
Finally solved it: in Chromium, the `.local` addresses were the culprit, too (not the codec). When I go to `chrome://flags/#enable-webrtc-hide-local-ips-with-mdns` and set that to Disabled, then everything starts working.

Question now is, who is messing up the `.local` resolution? If I test them with `avahi-resolve-host-name`, they appear to work for Chrome...

**Comment by thaytan** [comment]
Ah, we should add a fat notice about this for the time being.

Putting mdns names in place of local IPs is a Chrome innovation that they decided to make default and now I guess Firefox is too (but not for me yet). Noone has implemented for name resolution of ICE candidates GStreamer (in libnice) yet. It's issue https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1139 upstream
