### ISSUE TITLE
How to connect 2 webrtcbins

### ISSUE THREAD

**Issue by not404-found** [centricular/gstwebrtc-demos#167]
Hi everyone! Thanks for examples. But I have an issue that I cant connect two webrtcbins. Stream flows from client to java app(in example vice versa). So I create two webrtcbins for two clients and establish connection. 

After that I dont know what should I do for connecting them.
Pls help.
Code below:

webRTCBin.connect("on-new-transceiver", TransceiverAdded.class, transceiverAdded, transceiverAdded);
webRTCBin.connect(onIceCandidateListener);
webRTCBin.connect(on_negotiation_needed);

webRTCBin.ready();

webRTCBin.setRemoteDescription(remoteOffer);
webRTCBin.createAnswer(createAnswerListener);
webRTCBin.setLocalDescription(answer);

//add ices to

connect: 
webRTCBin1.link(webRTCBin2)

**Comment by thaytan** [comment]
I've read what you wrote several times, but I still I have no idea what you're trying to do. I think I need more context to understand what your problem is and what you're aiming for.

**Comment by not404-found** [comment]
I`m trying to connect 2 users using webrtcbin on gstreamer-java sdk. 
![webrtc-flow](https://user-images.githubusercontent.com/32771369/77292912-498bb700-6cf2-11ea-9551-943c7c9407a2.gif)

Stream from user-1 flows to user-2.
In example the `source` is VIDEO_ENC_H264 and the `sink` is webrtcbin which sends stream to client. 
In my case the `source` should be stream from client.

**Comment by not404-found** [comment]
![what-is-webrtc-7df5c50f862da5b28f77c27d1837139e7a79e604d12ae8adf8803ad17ac0d1d4](https://user-images.githubusercontent.com/32771369/77292598-ae92dd00-6cf1-11ea-9d2c-b88c2b060a6e.png)
I`m trying to implement such stuff

**Comment by not404-found** [comment]
![webrtc-flow](https://user-images.githubusercontent.com/32771369/77292706-df731200-6cf1-11ea-9465-ee6bea3f0d05.gif)
I`m trying to implement such stuff.

Stream from user-1 goes to user-2.

**Comment by thaytan** [comment]
The sendrecv examples send streams in both directions. There's an H.264 stream fed into webrtcbin, and one received from the peer that comes out a source pad.

It's entirely possible to configure things so that you only receive a stream from the peer, but I don't think we have an example for that.

**Comment by not404-found** [comment]
> It's entirely possible to configure things so that you only receive a stream from the peer, but I don't think we have an example for that.

I did it. 

**But now I need to transfer stream which received from the peer to another webrtcbin as source. Is it possible?**

**Comment by not404-found** [comment]
Hi guys! Can you pls provide more details about how to link several webrtcbins? 
I mean that I have e.g `client-1-webrtcbin` and `clinet-2-webrtc-bin` and I handle incoming stream for both of then in `onIncomingStream` method. So after that I link `client-1-webrtcbin` to `clinet-2-webrtc-bin` but stream not flowing. Is it possible to dynamically add stream from one webrtcbin to another.
I red that webrtcbin webrtcbin currently does not support dynamic addition/removal of streams.
Is that mean that I can't connect 2 webrtcbins?

**Comment by griimick** [comment]
> So after that I link client-1-webrtcbin to clinet-2-webrtc-bin but stream not flowing.

Can you elaborate on how did you link the two clients? If you did mange to have both the bins exchange offer/answer and ice candidates using signalling, then media should start flowing.

You can refer the [webrtcbidirectional example](https://github.com/GStreamer/gst-plugins-bad/blob/master/tests/examples/webrtc/webrtcbidirectional.c) in gst-plugin-bad.
