### ISSUE TITLE
Cannot compile examples on Raspian

### ISSUE THREAD

**Issue by PhilippeDuv** [centricular/gstwebrtc-demos#17]
Hi
Thanks for this nice move towards WebRTC
I am trying to compile the examples, on PI3 Debian, following your instructions
I am hitting the following error

> pi@raspberrypi:~/gstwebrtc-demos/sendrecv/gst $ gcc webrtc-sendrecv.c $(pkg-config --cflags --libs gstreamer-webrtc-1.0 gstreamer-sdp-1.0 libsoup-2.4 json-glib-1.0) -o webrtc-sendrecv
> Package gstreamer-webrtc-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `gstreamer-webrtc-1.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'gstreamer-webrtc-1.0' found
> Package json-glib-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `json-glib-1.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'json-glib-1.0' found
> webrtc-sendrecv.c:9:21: fatal error: gst/gst.h: No such file or directory
>  #include <gst/gst.h>
>                      ^
> compilation terminated.

Can't get around it, please help :)
Phil

**Comment by tp-m** [comment]
What GStreamer version are you using? Did you install 1.14? Can you check if you have a file called gstreamer-webrtc-1.0.pc on your filesystem? If not, you need to install the dev packages for the gst-plugins-bad libraries.

Same for json-glib-1.0, you need to install the `libjson-glib-dev` package for that.

**Comment by PhilippeDuv** [comment]
Thanks for the quick answer

json-glib side fixed with 
$ sudo apt-get install libjson-glib-dev

Gstreamer-webrtc-1.0.pc not there, true.
Please indicate what is the name of the dev package for the gst-plugins-bad libraries

Phil

**Comment by PhilippeDuv** [comment]
version I have here

pi@raspberrypi:~/gstwebrtc-demos/sendrecv/gst $ sudo apt-get install gstreamer-1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libqtgstreamer-1.0-0' for regex 'gstreamer-1.0'
Note, selecting 'gir1.2-gstreamer-1.0' for regex 'gstreamer-1.0'
Note, selecting 'libqt5gstreamer-1.0-0' for regex 'gstreamer-1.0'
gir1.2-gstreamer-1.0 is already the newest version (1.10.4-1).
libqt5gstreamer-1.0-0 is already the newest version (1.2.0-4).
libqtgstreamer-1.0-0 is already the newest version (1.2.0-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tp-m** [comment]
Raspbian ships a fairly old GStreamer (1.10). You will probably have to build gst yourself if you can't find 1.14 packages somewhere.

**Comment by PhilippeDuv** [comment]
got it. shall I start here?
https://github.com/centricular/gstwebrtc-demos#building-gstreamer-manually-from-source

**Comment by tp-m** [comment]
Yes, but be advised that it's not for the fainthearted. If you need help with that, best pop into `#gstreamer` on FreeNode IRC.

**Comment by Bingnan** [comment]
Hi, here is my case:
I use gst-uninstalled tool to build from source, following this guide: https://arunraghavan.net/2014/07/quick-start-guide-to-gst-uninstalled-1-x/

and after install some missing libs: libjson-glib-dev, libnice..  finally, it pass the compile, but when I run the webrtc-sendrecv, it appears:

`Required gstreamer plugin 'webrtc' not found`

here is my env after run : pkg-config --cflags --libs gstreamer-webrtc-1.0

`-pthread -I/root/gst/master/gstreamer/libs -I/root/gst/master/gstreamer -I/root/gst/master/gstreamer/libs -I/root/gst/master/gstreamer -I/root/gst/master/gstreamer/libs -I/root/gst/master/gst-plugins-bad/gst-libs -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -L/root/gst/master/gstreamer/libs/gst/base/.libs -L/root/gst/master/gstreamer/gst/.libs -L/root/gst/master/gst-plugins-bad/gst-libs/gst/webrtc/.libs -lgstwebrtc-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0`

**Comment by tp-m** [comment]
Well, what's your configure output for -bad? What's your libnince version? You will need 0.1.14

**Comment by Bingnan** [comment]
@tp-m it's ok now, you remind me with " what's your configure output for -bad ".

I go to ~/gst/master/gst-plugins-bad folder and 

`./configure; make; make install`

then recompile and run webrtc-sendrecv, it's ok now.

so the guide in https://arunraghavan.net/2014/07/quick-start-guide-to-gst-uninstalled-1-x/ not so exact， it says using below command to build will be ok:

`$ ./gstreamer/scripts/git-update.sh`

maybe we should enter each module and run ./autogen.sh;make;make install

Thanks all the same!
