### ISSUE TITLE
Reusable library 

### ISSUE THREAD

**Issue by makelinux** [centricular/gstwebrtc-demos#173]
There are a lot of code duplication and all code is not reusable directly. Have you plans or may you need help in code deduplication and creating reusable library or just source?

**Comment by sdroege** [comment]
What kind of library are you thinking of, what functionality should it provide? The signalling implemented for the demos is really just a demo and you will want to change that for any real use in applications.

**Comment by makelinux** [comment]
Samples are 500-800 lines and most of the code is duplication. It is confusing. It is difficult to understand what is difference and what is common between examples. It took he hours of reverse engineering. Finally I submitted doxygen patch. From one side  jni/webrtc.c is more modular, but remove JNI. From another side webrtc-sendrecv.c can be used for library unit tesing.

**Comment by sdroege** [comment]
Having the code abstracted into a library would kind of defeat the purpose of these being standalone examples though. You're supposed to be able to read it all in one go and then based on that implement your application. There you would then abstract things away into helper API as needed.

**Comment by makelinux** [comment]
I am trying to refactor and rework your webrtc-sendrecv.c for our application. And it is not smooth.
