### ISSUE TITLE
Static code analysis and code beautification.

### ISSUE THREAD

**Issue by makelinux** [centricular/gstwebrtc-demos#174]
1. Cppcheck and other tools warns about some not critical issues. 
2. A lot of code has inconsistent and broken indentation. BTW 2 spaces is very non-conventional indentation. 
Do you accepts patches for this issues?

**Comment by sdroege** [comment]
2 spaces is standard GStreamer indentation, you can reproduce that with [gst-indent](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/master/tools/gst-indent). But this only really applies to C code. Rust code goes through `rustfmt` with standard settings, and code in other languages should also be automatically formatted according to what is "standard" in those languages.

For static code analysis, go for it :) Thanks!

**Comment by makelinux** [comment]
https://github.com/centricular/gstwebrtc-demos/pull/176

https://github.com/centricular/gstwebrtc-demos/pull/177
