### ISSUE TITLE
can't view rtsp source without decode

### ISSUE THREAD

**Issue by yjjnls** [centricular/gstwebrtc-demos#18]
In the example sendrecv,  the pipeline use videotestsrc as the source, as below:
`videotestsrc pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay !`

But I want to view an rtsp source from a rtspserver with decode h264, I change the code to:
`rtspsrc location=rtsp://127.0.0.1:8554/test ! rtph264depay ! avdec_h264 ! queue ! x264enc ! rtph264pay ! `

And the cap define is `"application/x-rtp,media=video,encoding-name=H264,payload="`
it works fine. 

As the source stream is already coded with h264, so I remove the decode and codec process in the pipeline. But then I can't see the stream on the web.
`rtspsrc location=rtsp://127.0.0.1:8554/test ! rtph264depay ! queue ! rtph264pay ! `

How to view the stream without decodec and codec in the webrtc pipeline?

**Comment by nirbheek** [comment]
What are the stream properties of the h.264 being sent by the RTSP server? What profile level, level, bit-depth, etc? Browsers only support a subset of those.

**Comment by nirbheek** [comment]
Generally, you can get more information about what's going on by going to `about:webrtc` in Firefox and `chrome://webrtc-internals` on Chrome. Can't know what's going on without that.

**Comment by ilsme** [comment]
@yjjnls 
Try to set config-interval=1 param to your rtph264pay element. Worked for me.

**Comment by sunfic** [comment]
@ilsme @yjjnls 
Can you help me how to display H264 encoded video on webpage? I tried convert RTSP stream into VP8 and everything works fine. (Chrome browser)

`"rtspsrc location=rtsp://rtsp_stream_url  ! rtph264depay ! avdec_h264 ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "`

 and then I just tried to covert the RTSP stream into H264 nothing showed up chrome browser. 

`"rtspsrc location=rtsp://rtsp_stream_url  ! rtph264depay ! avdec_h264 ! queue ! x264enc ! rtph264pay !"`

I did modified cap definition. Is there anything I need to change in the webpage part? The RTSP stream is from DAHUA DVR. 

PS. got the error message from `chrome://webrtc-internals`
```
setLocalDescriptionOnFailure
Failed to set local answer sdp: Failed to set local video description recv parameters
```

client program sending offer: 
```
v=0
o=- 4115915154403299899 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:xxxxx
a=ice-pwd:xxxxx
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=mid:video0
a=fingerprint:sha-256 XX:XX:...

```
However Chrome received and refuse to config recv parameters nor reply to request:
```
setLocalDescription
type: answer, sdp: v=0
o=- 5765474179042889739 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 0
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:xxxx
a=ice-pwd:xxxx
a=ice-options:trickle
a=fingerprint:sha-256 XX:XX:...
a=setup:active
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
```

**Comment by yjjnls** [comment]
@ilsme set config-interval=1 in rtph264pay, it really works! Thank you.
@sunfic you can try it, also you can reference my repository [gstwebrtc-demo](https://github.com/yjjnls/gstwebrtc-demos) 

DAHUA DVR, hahahahaha

**Comment by sunfic** [comment]
@yjjnls 
Nice, Thank you!

**Comment by sampleref** [comment]
> set config-interval=1 in rtph264pay

Works!

**Comment by kevkid** [comment]
@yjjnls Can you give the complete pipeline description, I am having the same problem trying to view h264.

**Comment by yjjnls** [comment]
@kevkid 
> Try to set config-interval=1 param to your rtph264pay element.

**Comment by kevkid** [comment]
@yjjnls I am trying to get a stream from a raspberry pi camera which has h264 video streaming through the GPU. This is what I get when setting the following pipeline:
```
PIPELINE_DESC = '''
webrtcbin name=sendrecv bundle-policy=max-bundle
 tcpclientsrc host=192.168.11.32 port=5000 ! gdpdepay ! rtph264depay ! rtph264pay config-interval=1 pt=96 ! queue ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! sendrecv.
 audiotestsrc is-live=true wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay ! queue ! application/x-rtp,media=audio,encoding-name=OPUS,payload=96 ! sendrecv.
'''
```

I get this:
```
candidate: {'type': 'offer', 'sdp': 'v=0\r\no=- 237550636309020496 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\na=group:BUNDLE video0 audio1\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:xmUC86OsndTaQX7jvu3WyUiwqJkAdPWB\r\na=ice-pwd:v9R65zVtH7fJIL/1qMfkmeOcIrQtdGi+\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKKwrQFAe0A8SJqA=,KO4CXLA=\r\na=ssrc:2542831890 msid:user2747687893@host-bc003c06 webrtctransceiver0\r\na=ssrc:2542831890 cname:user2747687893@host-bc003c06\r\na=mid:video0\r\na=fingerprint:sha-256 88:14:F2:A7:06:D7:69:C1:33:C4:34:85:E1:41:73:72:91:12:04:F6:14:4B:E3:9E:D7:69:C2:C7:F3:1F:7E:4F\r\nm=audio 0 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:xmUC86OsndTaQX7jvu3WyUiwqJkAdPWB\r\na=ice-pwd:v9R65zVtH7fJIL/1qMfkmeOcIrQtdGi+\r\na=bundle-only\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 OPUS/48000/2\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 sprop-maxcapturerate=48000;sprop-stereo=0\r\na=ssrc:1925037372 msid:user2747687893@host-bc003c06 webrtctransceiver1\r\na=ssrc:1925037372 cname:user2747687893@host-bc003c06\r\na=mid:audio1\r\na=fingerprint:sha-256 88:14:F2:A7:06:D7:69:C1:33:C4:34:85:E1:41:73:72:91:12:04:F6:14:4B:E3:9E:D7:69:C2:C7:F3:1F:7E:4F\r\n'}
candidate ice From: 7433, candidate ice To: 4078
{"type":"answer","sentTo":7433,"payload":{"type":"answer","sdp":"v=0\r\no=- 5515222523376647172 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE video0 audio1\r\na=msid-semantic: WMS\r\nm=video 9 UDP/TLS/RTP/SAVPF 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:St35\r\na=ice-pwd:3523Kf5aEqQa5QMMhOnDpdsC\r\na=ice-options:trickle\r\na=fingerprint:sha-256 CE:3D:3C:8C:48:DE:98:FA:0C:0C:6A:35:34:B3:B7:32:7A:F4:CF:FC:19:41:28:EA:D0:E3:77:73:44:86:F0:F4\r\na=setup:active\r\na=mid:video0\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:St35\r\na=ice-pwd:3523Kf5aEqQa5QMMhOnDpdsC\r\na=ice-options:trickle\r\na=fingerprint:sha-256 CE:3D:3C:8C:48:DE:98:FA:0C:0C:6A:35:34:B3:B7:32:7A:F4:CF:FC:19:41:28:EA:D0:E3:77:73:44:86:F0:F4\r\na=setup:active\r\na=mid:audio1\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:96 OPUS/48000/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\n"},"name":"4078"}
```

in the console in chrome I get: 

```
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.
192.168.11.138/:1 Uncaught (in promise) DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
```

The stream works when I encode it to vp8 which looks like this:
pipeline:

```
PIPELINE_DESC = '''
webrtcbin name=sendrecv bundle-policy=max-bundle
 tcpclientsrc host=192.168.11.32 port=5000 ! gdpdepay ! rtph264depay ! avdec_h264 ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay !
 queue ! application/x-rtp,media=video,encoding-name=VP8,payload=97 ! sendrecv.
 audiotestsrc is-live=true wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay !
 queue ! application/x-rtp,media=audio,encoding-name=OPUS,payload=96 ! sendrecv.
'''
```
answer and offer:
```
candidate: {'type': 'offer', 'sdp': 'v=0\r\no=- 5533007499173963027 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\na=group:BUNDLE video0 audio1\r\nm=video 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:phAdyMjANb5yKqGUpSq8nDkZUcICoub/\r\na=ice-pwd:u6O12SwmaPtV0HTh49eemgZxZ9hMV+4T\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack pli\r\na=framerate:25\r\na=ssrc:2579782377 msid:user3664347504@host-67023ad1 webrtctransceiver0\r\na=ssrc:2579782377 cname:user3664347504@host-67023ad1\r\na=mid:video0\r\na=fingerprint:sha-256 44:86:F5:13:09:FE:24:27:D5:61:B0:B2:2F:95:A3:93:9A:BE:03:E0:6D:7E:EB:87:A1:76:84:6E:68:BB:02:43\r\nm=audio 0 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:phAdyMjANb5yKqGUpSq8nDkZUcICoub/\r\na=ice-pwd:u6O12SwmaPtV0HTh49eemgZxZ9hMV+4T\r\na=bundle-only\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 OPUS/48000/2\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 sprop-maxcapturerate=48000;sprop-stereo=0\r\na=ssrc:1999492587 msid:user3664347504@host-67023ad1 webrtctransceiver1\r\na=ssrc:1999492587 cname:user3664347504@host-67023ad1\r\na=mid:audio1\r\na=fingerprint:sha-256 44:86:F5:13:09:FE:24:27:D5:61:B0:B2:2F:95:A3:93:9A:BE:03:E0:6D:7E:EB:87:A1:76:84:6E:68:BB:02:43\r\n'}
candidate ice From: 9656, candidate ice To: 6217
{"type":"answer","sentTo":9656,"payload":{"type":"answer","sdp":"v=0\r\no=- 7099190997421906103 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE video0 audio1\r\na=msid-semantic: WMS\r\nm=video 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:e3ie\r\na=ice-pwd:W5qM4EAjxc6QReT1UFaBwXaE\r\na=ice-options:trickle\r\na=fingerprint:sha-256 69:F7:80:4C:61:79:AD:75:6C:30:23:63:6C:7A:36:2C:55:65:8D:13:95:C9:B2:07:85:AC:B3:19:6E:09:B5:CD\r\na=setup:active\r\na=mid:video0\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack pli\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:e3ie\r\na=ice-pwd:W5qM4EAjxc6QReT1UFaBwXaE\r\na=ice-options:trickle\r\na=fingerprint:sha-256 69:F7:80:4C:61:79:AD:75:6C:30:23:63:6C:7A:36:2C:55:65:8D:13:95:C9:B2:07:85:AC:B3:19:6E:09:B5:CD\r\na=setup:active\r\na=mid:audio1\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:96 OPUS/48000/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\n"},"name":"6217"}
answerFrom: 6217, answerTo: 9656
```
**EDIT**

Alright, I got it, It was the profile level in raspivid. I set it to baseline and now I get video out, but looks real weird, getting all kinds of artifacts.

It seems like the video stream skips and when I show the controls for the html5 player it skips to every 10 seconds. 

Here is my raspivid launcher code:
`raspivid -n -t 0 -pf baseline --vflip -w 640 -h 480 -fps 20 -b 2000000 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 ! gdppay ! tcpserversink host=192.168.11.32 port=5000`

**Comment by 823639792** [comment]
I also modify my code to play rtsp source without decode and encode, but latency is so high, nearly 1s-2s, If I use kurento the latency is 200ms, Is there any way to reduce latency.

Sorry for my poor english.

**Comment by 823639792** [comment]
kurento with decode and encode to vp8，latency is 200ms, cpu is 4% (720p)；
gstreamer 1.16 without decode and encode，latency is 300ms； if i modify to decode and encode， latency  nearly 2s，and cpu is 10% (720p).
What parameters can be set?

**Comment by yjjnls** [comment]
@823639792 you can modify the webrtcbin source code to set the SYNC to false, then you will get the stream immediately. Just like the launch `! autovideosink SYNC=false`

**Comment by 823639792** [comment]
@yjjnls 我是通过rtsp 转发到 web端查看，autovideosink 是用来查看web端发过来的视频用到的吧？
你的意思是要修改webrtcbin插件的源码，源码中有这个设置吗？

**Comment by yjjnls** [comment]
@823639792 autovideosink只是用来给你举个例子，gstreamer中的sink类型插件里面有个SYNC属性，设置为false应该就能解决你说的延迟问题。同理webrtcbin中也有对应的sink element，不过没有暴露出来，你得修改源码才可以，可以参考 https://github.com/GStreamer/gst-plugins-bad/blob/0af199e25ec7732c7a8462bae4e62219badb313c/ext/webrtc/nicetransport.c#L226
