### ISSUE TITLE
Janus example error: unknown signal name: get-transceiver

### ISSUE THREAD

**Issue by andrew-somerville** [centricular/gstwebrtc-demos#182]
When running the Janus example on Raspian-buster (all packages installed by standard "apt install" methods), I get this weird error when I hit the line:

`trans = self.webrtc.emit('get-transceiver', 0)`
`Traceback (most recent call last):
  File "/home/pi/VideoStreaming/RunJanusStream.py", line 456, in <module>
    c.loop(signaling)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/VideoStreaming/RunJanusStream.py", line 401, in loop
    self.start_pipeline()
  File "/home/pi/VideoStreaming/RunJanusStream.py", line 347, in start_pipeline
    trans = self.webrtc.emit('get-transceiver', 0)
TypeError: <__gi__.GstWebRTCBin object at 0xb51adbc0 (GstWebRTCBin at 0x19fa130)>: unknown signal name: get-transceiver`

Can't work out why this is missing, especially since if I use the "get-transceivers" instead, it's successful and returns a Glib Array which I can't access. 
`trans = self.webrtc.emit('get-transceivers')`

Any ideas why? Hoping it's not going to require me recompiling the plugin.

**Comment by ystreet** [comment]
get-transceiver signal is available in GStreamer 1.16. Are you attempting to run against a GStreamer 1.14 installation?

**Comment by andrew-somerville** [comment]
Seems so... my version is 1.14. Surprised that such an old version is the latest one packaged

**Comment by ystreet** [comment]
It is fairly common for a lot of distros to be behind in packaging.  They don't really take major version upgrades of packages.

If you want to build a new version of GStreamer without disturbing your packaged install, I would suggest looking into gst-build available from https://gitlab.freedesktop.org/gstreamer/gst-build
