### ISSUE TITLE
Could not create data channel, is usrsctp available?

### ISSUE THREAD

**Issue by zt-luo** [centricular/gstwebrtc-demos#185]
i am using https://github.com/centricular/gstwebrtc-demos/blob/master/sendrecv/gst/webrtc-sendrecv.c demo to make my app. but got `Could not create data channel, is usrsctp available?`

i can find `libusrsctp-1.dll` and `libgstsctp-1.0-0.dll`  from `C:\msys64\mingw64\bin`, what should i do ?

**Comment by zt-luo** [comment]
i have figure out how to fix this on windows. GStreamer prebuild install contain `libgstsctp-1.0-0.dll` just cope this to `C:\msys64\mingw64\lib\gstreamer-1.0`.

**Comment by zt-luo** [comment]
But i still have not idea how to fix this on Linux. Anyone can help me?

**Comment by thaytan** [comment]
On Linux, I needed to build and install libusrsctp to /usr/local/ manually - it's not available in the Fedora packages yet. It might be on other distributions - I don't know.

**Comment by sdroege** [comment]
It's in Debian since last release and Ubuntu since the last two, I don't know about others

**Comment by zt-luo** [comment]
ok, thanks. I think i need to build and install libusrsctp on Manjaro.
closing this issue.
