### ISSUE TITLE
Fail to compile webrtc demo code on Ubuntu

### ISSUE THREAD

**Issue by yx-arch** [centricular/gstwebrtc-demos#187]
Hi,

I'm new to gstreamer and looking for help on the following issue.  I have installed gstreamer 1.16.2 on Ubuntu 20.04. I got the following error when try to compile the webrtc-sendrecv demo code. Can anyone tell me how to solve this issue?

Thanks,
yx

# gst-inspect-1.0 --version
gst-inspect-1.0 version 1.16.2
GStreamer 1.16.2
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0

# gcc webrtc-sendrecv.c $(pkg-config --cflags --libs gstreamer-webrtc-1.0 gstreamer-sdp-1.0 libsoup-2.4 json-glib-1.0) -o webrtc-sendrecv

Package gstreamer-webrtc-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-webrtc-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-webrtc-1.0' found
Package gstreamer-sdp-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-sdp-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-sdp-1.0' found
Package libsoup-2.4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsoup-2.4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsoup-2.4' found
Package json-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-glib-1.0' found
webrtc-sendrecv.c:9:10: fatal error: gst/gst.h: No such file or directory
    9 | #include <gst/gst.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by thaytan** [comment]
You are missing more devel packages - `libgstreamer-plugins-bad1.0-dev` and `libsoup2.4-dev` and `libjson-glib-dev`

**Comment by yx-arch** [comment]
Thanks Jan for the quick response. It works :-)
