### ISSUE TITLE
Is it possible for webrtc-sendrecv to "broadcast" video

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#19]
Hello, 

With a lot of work i have been able to write my own signaling server in Node.js.
I also have been able to write a multi peer (in a single webpage) demo. 

But a question cross my mind. Is it possible to broadcast a single gstreamer pipeline to a a lot of peer browser ? 

A use case would be to have pipeline that broadcast my webcam. And each peer that connect would see the live stream.

It would be the opposite of what i wrote. Actually i have done : multiple (source) webrtc-sendrecv to one (client) page (chrome browser).

And i want : one (source) werbrtc-sendrecv instance and multiple (client) browser page

I have already check the Mesh, MCU, SFU topology.  And i know this isn't really an issue of this demo. 

If someone could feed me with (demo, website, information) or redirect me it would be really nice.

Sypsô

**Comment by ystreet** [comment]
Yes, you can feed the same GStreamer source/pipeline to multiple peers.  That would entail setting up your source pipeline and then using the tee element to duplicate the streams to multiple webrtcbin's that are setup for each client (browser).  If you don't have a middle man of some sort, this is effectively the mesh topology.

**Comment by ghost** [comment]
Okay, perfect i will investigate ! 

Thank for all ystreet ! 

Question anwsered =)

**Comment by sampleref** [comment]
Apologise if I am commenting on a closed issue, but @Sypso is there any such example where this gstreamer webrtc-sendrecv pipeline is broadcasting to multiple peers (browsers). That is webrtc-sendrecv would generate a peer-id and keep running, any browser peer willing to watch broadcast can connect to this peer. 

I hope if you could have tried and written such example may be it can help us

**Comment by hongbo-miao** [comment]
Hi @Sypso just a suggestion, maybe you can write a blog for how to use Node.js and GStreamer with its webrtc plugin to help the community! : )

**Comment by aiden-ct** [comment]
@ystreet - I've adapted the webrtc-sendrecv signalling server for a "broadcast" or streaming use case; spinning up new webrtcbin elements for every client connection to the stream (4k, 25Mbps video). It works perfectly on localhost, but over the network to another machine a *lot* of packets are dropped (not dropped if I stream the same data udpsink->udpsrc). Do you have any experience of this or tips on how to debug this?

**Comment by Moses0h** [comment]
Anyone have an example of this? For example, my pipeline looks like 

PIPELINE_DESC = f'''
rtspsrc location={server_url} ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! queue ! x264enc ! rtph264pay ! queue ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! webrtcbin name=sendrecv
'''
how can I send this pipeline to multiple peers?

**Comment by thaytan** [comment]
You need a program that builds a pipeline with a) a media generation portion leading to tee b) after the tee, queues and multiple webrtcbin's (1 per peer)
