### ISSUE TITLE
Is google transport-wide congestion control supported in webrtc call

### ISSUE THREAD

**Issue by yx-arch** [centricular/gstwebrtc-demos#190]
Hi, 

I need to develop a live streaming application from gstreamer to browser over webrtc. From this thread http://gstreamer-devel.966125.n4.nabble.com/RTP-dynamic-bitrate-depending-on-network-condition-td4689673.html#a4693340, I learned that webrtcbin does not support any congestion control, but some work has been started to add google TWCC in gstreamer. From https://github.com/GStreamer/gst-plugins-good/commit/1df706448ca2f6116173f879f43d596e026e2dc5, I can see code to support google TWCC is there. Can anyone confirm if this feature is supported in latest gstreamer release 1.16.2 now? I need to enable this feature on gstreamer side (when gstreamer is the sender). Is there any demo code available? 

Thanks,
yx

**Comment by ystreet** [comment]
TWCC is not currently implemented in webrtcbin.  TWCC is also not available in GStreamer 1.16.2.  You need GStreamer master for TWCC.  If you'd like to help move this forward let us know.

**Comment by yx-arch** [comment]
Thanks Matthew - do you know if another version of GCC (goog-remb) is supported in GStreamer?

**Comment by ystreet** [comment]
No, goog-remb is not currently supported by GStreamer

**Comment by yx-arch** [comment]
thanks Matthew for the quick response - one more question for TWCC support in Gstreamer master, does it support sender-side implementation (i.e.: in my application, gstreamer is sending video to chrome browser)?
