### ISSUE TITLE
data channel 'on-open' message emited twice

### ISSUE THREAD

**Issue by zt-luo** [centricular/gstwebrtc-demos#191]
i am running `/sendrecv/gst` c demo, i got these data channel debug info. i can see `data_channel_on_open` are called twice, this is a webrtcbin bug or i have missing something?
```
data channel opened
data channel opened
Received data channel message: Hi! (from browser)
Received data channel message: Hi! (from browser)
Received data channel message: Hi! (from browser)
Received data channel message: Hi! (from browser)
```

**Comment by ystreet** [comment]
There are two data channels in the demo example. One initiated from GStreamer, another initiated from the browser so this is entirely expected.
