### ISSUE TITLE
Signalling server does not restart on certificate change

### ISSUE THREAD

**Issue by DejanCotra** [centricular/gstwebrtc-demos#194]
Hello,

One short question.  https://webrtc.nirbheek.in/ its not working currently. It looks like it can not access 
'wss://webrtc.nirbheek.in:8443/ is server temporarily down?

Or I need to make some additional settings in my browser.

Dejan

**Comment by thaytan** [comment]
It probably needs a restart to pick up a new SSL cert

**Comment by neilyoung** [comment]
For me it works

**Comment by DejanCotra** [comment]
> For me it works

Ok. I try it on from several different browsers, form several different machines and several different IP addresses. No luck. Its not working.

**Comment by neilyoung** [comment]
Well you are right. I was focused on the webpage. That comes. But there is an error in red:

"Did you add an exception for the certifcate", or so...

while connecting to wss://...

**Comment by nirbheek** [comment]
I'm working on it.

**Comment by neilyoung** [comment]
Seems to work again. Thanks

**Comment by DejanCotra** [comment]
Its working for me as well. Many thanks for both fix and quick response.

BTW.
Also want to thank you all for contribution to this demos with gstreamer and webrtc.
They are very helpful. They make my life much easier :)

Best Regards,
Dejan
