### ISSUE TITLE
Problems when using webrtcbin with omxh264enc

### ISSUE THREAD

**Issue by spurihwr** [centricular/gstwebrtc-demos#196]
Hi guys, I am fairly new to webrtc and still learning. I am trying to use omxh264enc instead of x264enc in my pipeline. 
When I use x264enc, I can see the video is running fine. However with omxh264enc, video just freezes at the first frame. 

Here is the pipeline I am using:
**receiver_entry->pipeline =
 gst_parse_launch ("webrtcbin name=webrtcbin stun-server=stun://"
 STUN_SERVER " "
"videotestsrc is-live=true pattern=smpte ! video/x-raw,width=1280,height=720,framerate=15/1 ! "
"omxh264enc control-rate=2130706433 num-slices=1 periodicity_idr=60 target-bitrate=5000 qp-mode=2 gop-mode=5 interval-intraframes=1 ! "
"video/x-h264,profile=high,alignment=nal,stream-format=byte-stream,level=(string)4 ! "
"queue max-size-time=100000000  ! h264parse ! "
"rtph264pay config-interval=-1 name=payloader ! "
"application/x-rtp,media=video,encoding-name=H264,payload="
RTP_PAYLOAD_TYPE " ! webrtcbin. ", &error);**  

Any clue what could be the problem?

**Comment by ystreet** [comment]
Using omxh264enc is outside the scope of these examples.  Please use the `#gstreamer` IRC channel on freenode or the gstreamer-devel mailing list for these kinds of support questions.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
