### ISSUE TITLE
video freezes after a second when using omxh264enc on sendonly

### ISSUE THREAD

**Issue by pstegegn** [centricular/gstwebrtc-demos#197]
I am using GStreamer 1.14.4 on aarch64 Linux system. it compiles and runs successfully, but when accessing http://127.0.0.1:57778/, the stream plays for a split second and then freezes, I checked 
the tcpdump on the host, and the RTP stream stops with out any error packets. Also no error is shown in the browser(Firefox) debug console.

gst_parse_launch("webrtcbin name=webrtcbin stun-server=stun://" STUN_SERVER " "
    "videotestsrc is-live=true ! "
    "video/x-raw,width=720,height=480,framerate=15/1 ! "
    "queue max-size-buffers=1 ! "
    "omxh264enc ! "
    "video/x-h264, alignment=nal, profile=constrained-baseline ! "
    "queue max-size-time=100000000 ! "
    "h264parse ! "
    "rtph264pay config-interval=1 ! "
    "application/x-rtp,media=video,encoding-name=H264,payload="   RTP_PAYLOAD_TYPE " ! webrtcbin. ",
    &error);

I appeciate your help in advance 

HOST LOG
:~# GST_DEBUG=3 ./webrtc-unidirectional-h264
WebRTC page link: http://127.0.0.1:57778/
Processing new websocket connection 0x20b07d20[2020-05-28 14:41:56.522058690]   [dma_memory.cpp:61]     [DMAMemory]     No such file or directory: '/dev/dmaproxy'. DMA channel is not availad
0:00:10.821131720 10371     0x20b7ae30 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<videotestsrc0:src> Creating random stream-id, consider implementing a d
!! The specified ScalingList is not allowed; it will be adjusted!!
!! CABAC encoding is not allowed in baseline profile; CAVLC will be used instead !!
!! The specified Level is too low and will be adjusted !!
Creating negotiation offer
0:00:12.216749980 10371     0x20a5bcf0 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<nicesrc1:src> Creating random stream-id, consider implementing a deterd
0:00:12.216882110 10371     0x20a5bcf0 WARN                GST_PADS gstpad.c:4226:gst_pad_peer_query:<nicesrc1:src> could not send sticky events
0:00:12.217277420 10371   0x7fa8089540 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<nicesrc2:src> Creating random stream-id, consider implementing a deterd
0:00:12.217353070 10371   0x7fa8089540 WARN                GST_PADS gstpad.c:4226:gst_pad_peer_query:<nicesrc2:src> could not send sticky events
Negotiation offer created:
v=0
o=- 100328657559895013 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=msid-semantic:WMS webrtcbin
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:qM1fX4LtFYr1AAkIuiys0N8HGCBmmOMR
a=ice-pwd:Bmhpz7YMMwKJmYPrAM1C2SCuieo3vDbT
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:15
a=fmtp:96 packetization-mode=1;profile-level-id=42401f;sprop-parameter-sets=J0JAH+dAKALdgLUBAgLwAAADABAAAAMB4zUD6AXf//wK,KM48gA==
a=ssrc:2990570934 msid:user2279925120@host-218559e0 webrtctransceiver0
a=ssrc:2990570934 cname:user2279925120@host-218559e0
a=mid:video0
a=fingerprint:sha-256 55:6B:F9:C9:FF:E2:27:60:94:44:E2:35:9E:B7:49:59:4B:5D:25:9F:C6:14:37:FF:56:16:33:94:5E:0C:35:9E

Received SDP:
v=0
o=mozilla...THIS_IS_SDPARTA-76.0.1 467976205299278788 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 6A:DB:01:27:38:1F:86:63:39:DD:57:CE:C8:3B:82:0D:25:92:E4:65:3A:2E:DA:2D:34:BB:BC:50:90:D4:6E:70
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=recvonly
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:e3cee26ab62d7cb14d819eccee416be4
a=ice-ufrag:d842647e
a=mid:video0
a=rtcp-fb:96 nack pli
a=rtcp-mux
a=rtpmap:96 H264/90000
a=setup:active
a=ssrc:2765547787 cname:{ac820dda-b534-40cb-9a20-a578589bb286}

Received ICE candidate with mline index 0; candidate: candidate:0 1 UDP 2122252543 e2a058ae-a218-4fbc-989c-b544ac6e44ab.local 48386 typ host, len: 86
Received ICE candidate with mline index 0; candidate: candidate:2 1 TCP 2105524479 e2a058ae-a218-4fbc-989c-b544ac6e44ab.local 9 typ host tcptype active, len: 97
ICE gathering state changed to complete
0:00:12.255803700 10371     0x20a4fa30 WARN               webrtcice gstwebrtcice.c:502:gst_webrtc_ice_add_candidate:<webrtcice0> Could not parse candidate 'a=candidate:0 1 UDP 2122252543 e2'
0:00:12.255895260 10371     0x20a4fa30 WARN               webrtcice gstwebrtcice.c:502:gst_webrtc_ice_add_candidate:<webrtcice0> Could not parse candidate 'a=candidate:2 1 TCP 2105524479 e2'
ICE gathering state changed to gathering
Received ICE candidate with mline index 0; candidate: candidate:1 1 UDP 1686052863 **ip** 48386 typ srflx raddr 0.0.0.0 rport 0, len: 79
0:00:12.388926230 10371   0x7fa81f58f0 FIXME               basesink gstbasesink.c:3156:gst_base_sink_default_event:<nicesink1> stream-start event without group-id. Consider implementing gros
0:00:12.424709690 10371   0x7fa8089540 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux1> received invalid buffer: 1
0:00:12.442515160 10371     0x20a5bcf0 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux0> received invalid buffer: 1
0:00:37.321841400 10371   0x7fa8089540 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux1> received invalid buffer: 1
ICE gathering state changed to complete
0:01:02.323301450 10371   0x7fa8089540 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux1> received invalid buffer: 1
0:01:27.324119740 10371   0x7fa8089540 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux1> received invalid buffer: 1
0:01:52.327502800 10371   0x7fa8089540 WARN           dtlssrtpdemux gstdtlssrtpdemux.c:134:sink_chain:<dtlssrtpdemux1> received invalid buffer: 1

**Comment by ystreet** [comment]
It looks like your browser is producing `.local` mdns candidates.  Supporting them in GStreamer requires at least GStreamer >1.18 and a correctly configured system that supports mdns lookups.
