### ISSUE TITLE
Data Channel and no media, is it possible ?

### ISSUE THREAD

**Issue by rosimildo** [centricular/gstwebrtc-demos#200]
On the browser side, it is possible to create just a data channel peer connection to exchange data and no media ( video or audio ). Is this possible with webrtcbin, and can anyone show an example ?

Today, I have data channels connections working, but always with some media connections along with the data channel. 

Thanks!

**Comment by ystreet** [comment]
Yes, it is possible.  Simply don't add any media pads to webrtcbin and negotiation as normal.  You may need a recent version (maybe master) of GStreamer to make data-channel only work on most cases.

**Comment by rosimildo** [comment]
Thank you!  I am using 1.16.2
I will try in a few days!
