### ISSUE TITLE
Is Gstwebrtc compatible with Windows

### ISSUE THREAD

**Issue by bfamzz** [centricular/gstwebrtc-demos#203]
Hi @nirbheek 

Please is Gstwebrtc compatible with Windows?

I am trying to run some of the demos but I keep getting this error message: 

`C:/msys64/mingw64/include/glib-2.0/glib-unix.h:29:10: fatal error: sys/wait.h: No such file or directory`

I am compiling and running it on Msys2 and Mingw toolchain.

thanks.

**Comment by ystreet** [comment]
Yes, GStreamer and gstwebrtc-demos are known to work on windows.  The very existence of `glib-unix.h` in your glib build indicates that you have not built glib for windows correctly.  Generally, the GStreamer project would recommend using [cerbero](https://gitlab.freedesktop.org/gstreamer/cerbero) to build all the dependencies required for GStreamer and gst-webrtc-demos.  If you have any issues with that, it is best to direct your question at the gstreamer-devel mailing list or ask your question on irc at `#gstreamer` on freenode

**Comment by nirbheek** [comment]
sendonly examples unconditionally include `glib-unix.h`.
