### ISSUE TITLE
Failed to parse launch: no element "ahcsrc" in Android sample

### ISSUE THREAD

**Issue by kwende** [centricular/gstwebrtc-demos#207]
Google Pixel 3a (Android 10.0 - API 29)

I do a fresh pull of the Github repo as-is, and build using the Dockerfile at the end of this issue (I interactively attach to the container and do a _gradle build_ in the /android sub-directory I mount as a volume). The following error occurs: 

I/GLib+stdout( 5218): ca-certificates /data/user/0/org.freedesktop.gstreamer.webrtc/files/ssl/certs/ca-certificates.crt
I/GLib+stdout( 5218): Connecting to server ws://192.168.1.26:8551...
I/GLib+stdout( 5218): Connected to signalling server
I/GLib+stdout( 5218): Registered with server
E/GLib+stderr( 5218): Failed to parse launch: no element "ahcsrc"
E/GLib+stderr( 5218): ERROR: failed to start pipeline

**Dockerfile**

```
FROM ubuntu:latest
USER root

# Install Build Essentials
# Install OpenJDK-8
# Fix certificate issues
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
	apt-get install unzip && \
	apt-get install build-essential -y && \
	apt-get install wget -y && \
	apt-get install file -y && \
	apt-get install apt-utils -y && \
	apt-get install vim -y && \
	apt-get install pkg-config -y && \
	apt-get install curl -y && \
	apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
	apt-get install ca-certificates-java && \
	apt-get install git -y && \
    apt-get clean && \
	update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

ENV GRADLE_VERSION 4.6
ENV GRADLE_SDK_URL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
RUN mkdir /usr/local/gradle
RUN curl -sSL "${GRADLE_SDK_URL}" -o gradle-${GRADLE_VERSION}-bin.zip  \
	&& unzip gradle-${GRADLE_VERSION}-bin.zip -d /usr/local/gradle  \
	&& rm -rf gradle-${GRADLE_VERSION}-bin.zip
ENV GRADLE_HOME /usr/local/gradle/gradle-${GRADLE_VERSION}
ENV PATH ${GRADLE_HOME}/bin:$PATH

ENV SDK_URL="https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip" \
    ANDROID_HOME="/usr/local/android-sdk" \
    ANDROID_VERSION=28 \
    ANDROID_BUILD_TOOLS_VERSION=27.0.3
# Download Android SDK
RUN mkdir "$ANDROID_HOME" .android \
    && cd "$ANDROID_HOME" \
    && curl -o sdk.zip $SDK_URL \
    && unzip sdk.zip \
    && rm sdk.zip \
    && mkdir "$ANDROID_HOME/licenses" || true \
    && echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
#    && yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
# Install Android Build Tool and Libraries
RUN $ANDROID_HOME/tools/bin/sdkmanager --update
RUN $ANDROID_HOME/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
    "platforms;android-${ANDROID_VERSION}" \
    "platform-tools"

# Android NDK
ENV ANDROID_NDK_VERSION r21b
ENV ANDROID_NDK_URL http://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
RUN curl -L "${ANDROID_NDK_URL}" -o android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
RUN unzip android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip -d /usr/local/android-ndk-${ANDROID_NDK_VERSION}
RUN rm -rf android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
ENV ANDROID_NDK_HOME /usr/local/android-ndk-${ANDROID_NDK_VERSION}
ENV PATH ${ANDROID_NDK_HOME}:$PATH
#RUN chmod u+x ${ANDROID_NDK_HOME}/ -R

ENV GSTREAMER_ANDROID_VERSION 1.16.1
RUN mkdir /usr/local/gstreamer
RUN curl -L https://gstreamer.freedesktop.org/data/pkg/android/1.16.1/gstreamer-1.0-android-universal-${GSTREAMER_ANDROID_VERSION}.tar.xz -o /usr/local/gstreamer/gstreamer-1.0-android-universal-${GSTREAMER_ANDROID_VERSION}.tar.xz
RUN tar -xf /usr/local/gstreamer/gstreamer-1.0-android-universal-${GSTREAMER_ANDROID_VERSION}.tar.xz -C /usr/local/gstreamer/
RUN rm -fr /usr/local/gstreamer/gstreamer-1.0-android-universal-${GSTREAMER_ANDROID_VERSION}.tar.xz
ENV GSTREAMER_ROOT_ANDROID /usr/local/gstreamer/
ENV PATH ${GSTREAMER_ROOT_ANDROID}:$PATH
ENV PATH /usr/local/gstreamer/armv7/include/gstreamer-1.0:$PATH


```

One thing to note, I _did_ have to add a local.properties file and set its contents to this: 
```

sdk.dir = /usr/local/android-sdk/
ndk.dir=/usr/local/android-ndk-r21b/android-ndk-r21b
```

**Comment by thaytan** [comment]
Hmm. The `GSTREAMER_PLUGINS_CODECS_CUSTOM := videoparsersbad vpx opus audioparsers opusparse androidmedia
` line in `app/src/main/jni/Android.mk` should be pulling in the androidmedia plugin that includes that element

**Comment by kwende** [comment]
Agreed, it should, but something is wonky here as it doesn't appear to be doing so. If I take the .APK, change its file extension to ZIP, and extract it, I get the following: 

![image](https://user-images.githubusercontent.com/526471/85889780-bdd26c80-b7b1-11ea-83e2-8e2363e487be.png)

This seems to indicate an issue with the build system not including the requisite files, correct? I expect to see the AndroidMedia module somewhere in here. 

**Edit**: After perusing the android files for Gstreamer, I think I'm better understanding that the few files in here are probably built from the .a files, of which androidmedia ought to be one. Still not sure why GStreamer's runtime isn't working. 

**Edit2**: Switching out the ahcsrc module with videotestsrc everything works. So, it's just this singular module that's the issue. Maybe try the docker file I added and see if you can get it to fail too?

**Comment by thaytan** [comment]
On Android, the plugins that are configured into the build get built into the libgstreamer_android.so file from the static libs. I think @ystreet said he can reproduce this bug, so he might have something to add soon.

**Comment by kwende** [comment]
@thaytan yeah, I had discovered that the files are compiled into a single so file and updated my comment from earlier. But, I appreciate you confirming it for me. 

I'd love to have a solution for you as opposed to just a bug write up, but unfortunately I am not a Java nor Android developer. 

I eagerly await any help.

**Comment by kwende** [comment]
@ystreet any bump on this? I've side-stepped the issue for now so I can continue on with what I need to get done for work, but with a bit of a nudge in the right direction I can try solving this issue for you all. I just need to know that you've duplicated it, more or less so I know there is an issue and it's not something stupid I've done. 

Thanks mate.

**Comment by ystreet** [comment]
I have reproduced the problem with ahcsrc not being found, yes.  That's as far as I got before other things distracted me :).  There is at least something else currently wrong with ahcsrc as outlined in https://gitlab.freedesktop.org/gstreamer/cerbero/-/issues/283

i'm currently working on this in https://gitlab.freedesktop.org/ystreet/gst-examples/-/commits/android-webrtc-example/

**Comment by ystreet** [comment]
I can get past the ahcsrc error by reverting https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/765 but then encounter issues with libnice :/

**Comment by kwende** [comment]
OK. Let me see if I can do some digging too and help you out here. Sounds like we're both overwhelmed with work; perhaps between the two of us we can figure this out. Any idea on what seems to be the core issue? I haven't looked at that merge request yet as I'm working on another project atm, but perhaps just give me a high level?

**Comment by ystreet** [comment]
It's mostly just lots of little things as things in Android and GStreamer change over time.

https://gitlab.freedesktop.org/ystreet/gst-examples/-/commits/android-webrtc-example/ are mostly changes that happened upstream in GStreamer that were not applied to the android demo yet (plugin name changes, removal of gnutls in favour of openssl, things like that).  This branch was built against 1.17.1/1.17.2 of upstream GStreamer.

The ahcsrc issue is a result of https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/765 introducing things that don't actually seem to be available everywhere (at least most of the java values retrieved aren't in the android documentation at all).

libnice - I don't know yet :).  I just get a whole bunch of 'code should not be reached' (== `g_assert_not_reached()`) errors related to sockets which is never a good sign :).

**Comment by kwende** [comment]
So, what I'm being tasked with right now is to take the webrtc code and call it from Xamarin. I haven't found a lot of examples out there doing this, and so when I get it done working for my day job, I'll probably see about submitting an example webrtc implementation atop Xamarin to this repo. After that, I'll see if I can jump in and help you with this. 

I don't need the camera on the phone at the moment, just the microphone. So, this isn't a roadblock for me at the moment. I'm hoping to get all of this done this week -- so, I'll circle back around with you later in the week. 

(What's making this all hard for me is I'm not even an Android developer)

**Comment by ystreet** [comment]
The ahcsrc-specific issue is worked around by https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1470.  I also fixed the example android application with https://gitlab.freedesktop.org/gstreamer/gst-examples/-/merge_requests/25 so now I can run the android application again.
