### ISSUE TITLE
Create a pipeline to a tee that contains both audio and video from mp4 or pulsesrc / ximagesrc

### ISSUE THREAD

**Issue by stearnsbq** [centricular/gstwebrtc-demos#209]
Hello,

I am currently stuck with this problem. I have based my code off the multiparty-sendrecv code, and have changed it to be send only as I don't have a use case for receiving streams from clients just data channel.

I have a pipeline for video and a pipeline for audio seperately however I need to figure out how to get both audio and video from demuxing a mp4 file and later on using pulsesrc for audio and ximagesrc for video once I figure out a pipeline for mp4 files.

audio pipeline:
`tee name=videotee ! queue ! fakesink filesrc location=/home/rabclone/Desktop/videoplayback.mp4 ! queue ! qtdemux name=demux demux.audio_0 ! decodebin ! audioconvert ! audioresample ! opusenc ! rtpopuspay ! videotee.`

video pipeline:
`tee name=videotee ! queue ! fakesink filesrc location=/home/rabclone/Desktop/videoplayback.mp4 ! decodebin ! x264enc bitrate=2500 speed-preset=ultrafast tune=zerolatency key-int-max=15 ! rtph264pay ! queue ! videotee.`

Some pointers would be appreciated as I have been stuck on this for a few days and I haven't found a concise answer by googling.

**Comment by stearnsbq** [comment]
Hello, I have found out the pipeline for this use case. I had to implement two tees one for the audio and one for the video

`tee name=videotee ! queue ! fakesink ximagesrc ! videoscale ! video/x-raw,framerate=30/1 ! videoconvert ! queue ! vp8enc error-resilient=partitions keyframe-max-dist=10 auto-alt-ref=true cpu-used=5 deadline=1 ! rtpvp8pay ! videotee. tee name=audiotee ! queue ! fakesink pulsesrc device=alsa_output.pci-0000_02_02.0.analog-stereo.monitor  ! audioconvert ! queue ! opusenc ! rtpopuspay ! audiotee.`

and so I had to change the add_peer_to_pipline function to add the peer for the audio tee and link the audio to the webrtcbin and it works great. if the pipeline could be optimized please let me know!

**Comment by ystreet** [comment]
Sounds like you figured out the funcionality.  There are various other resources available for optimizing GStreamer pipelines but that is outside the scope of this repository.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
