### ISSUE TITLE
Python accept call problem

### ISSUE THREAD

**Issue by fedon** [centricular/gstwebrtc-demos#212]
Trying to answer an offer in Python I have stuck with **create-answer**. I didn't find example in Python itself so, I used c-code for inspiration. But didn't get far. Relevant methods are:

    def on_answer_created(self, promise, e, __):
        promise.wait()
        reply = promise.get_reply()
        print('debug: problem here', flush=True)
        answer = reply['answer']
        promise = Gst.Promise.new()
        self.webrtc.emit('set-local-description', answer, promise)
        promise.interrupt()
        self.send_sdp_answer(answer)

    def on_offer_set(self, promise, element, __):
        print('offer is ready')
        promise.wait()
        promise = Gst.Promise.new_with_change_func(self.on_answer_created, element, None)
        element.emit('create-answer', None, promise)
        promise.interrupt()

The console output:
`
offer is ready

(python3:22185): GStreamer-CRITICAL \*\*: 19:23:08.334: gst_promise_get_reply: assertion 'result == GST_PROMISE_RESULT_REPLIED' failed
debug: problem here
Traceback (most recent call last):
  File "gst-matrix-accept.py", line 120, in on_answer_created
    answer = reply['answer']
TypeError: 'NoneType' object is not subscriptable
`
So, I never get answer from webrtcbin.
Any help?

**Comment by ystreet** [comment]
What version of GStreamer are you using?  GStreamer master will always reply something to a promise, 1.16 and previous versions had a bug that would not.

When responding with webtrcbin to an offer, what usually happens is that there is either a mismatching mline to pad relationship or mismatching caps (normally the payload type field) between GStreamer and the offer SDP which causes the negotiation to fail.  Currently the application needs to manage both of those things itself.

You currently need to look at the GStreamer debug logs to figure out exactly why the negotiation failed.

**Comment by fedon** [comment]
Thank you for clarification.
I'm using version 1.16.2 on postmarketos-allwinner (Alpine Arm64).

 $ gst-launch-1.0 --gst-version
    GStreamer Core Library version 1.16.2

I have managed to parse offer and modify PIPELINE_DESC. But the problem still persist. For streaming only audio I'm composing following PIPELINE_DESC:

  webrtcbin name=sendrecv bundle-policy=max-bundle stun-server=stun://stun.l.google.com:19302
   alsasrc ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay !
   queue ! application/x-rtp,media=audio,encoding-name=OPUS,payload=109 ! sendrecv.

Received offer:
v=0
o=mozilla...THIS_IS_SDPARTA-77.0.1 2112951554859152960 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 nn:nn
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:nn
a=ice-ufrag:nn
a=mid:0
a=msid:{some-id} {some-id}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:4054203355 cname:{some-id}

What am I missing? Initiating a call works perfectly. Adding video doesn't help.
I'm afraid I don't have calculation power to build whole Gstreamer. Is it possible to build only that part I need to replace?

**Comment by ystreet** [comment]
SDP looks good.  Are you maybe hitting https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1139 ?

You need to look through the GStreamer debug logs to see a possible reason as to why this case is not working for you.  1.16 might work for you however it does have multiple known issues with webrtcbin and I would strongly recommend trying out GStreamer master.

**Comment by fedon** [comment]
Unfortunately, the problem persists in 1.17.2. Tested on Manjaro Gst build from master. And it is not about local address (Chrome is not used).
How can I improve webrtcbin verbosity?

**Comment by ystreet** [comment]
`GST_DEBUG=*webrtc*:7`

**Comment by ystreet** [comment]
Also, firefox uses mdns candidates now without a way to disable them.

**Comment by fedon** [comment]
Problem solved. It was wrong placed promise.interrupt(). Now it works in both directions AV. Unfortunately webrtcbin hangs often during the first second of streaming.
And is there a way to disable upnp its warnings are very annoying?
