### ISSUE TITLE
I am using 1.14.5 gst version, cpu usage is very high for the simple examples(recvonly)

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#213]
for webrtc-recvonly-h264.c , CPU usage is 13-15%. How to optimize the pipeline?

**Comment by ystreet** [comment]
Encoding/Decoding h.264 can be expensive.  You can try using a hardware encoder if it exists on your system and is supported.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
