### ISSUE TITLE
Improving stream performance for 4k video

### ISSUE THREAD

**Issue by Yddeon** [centricular/gstwebrtc-demos#214]
Hey! I'm developing a program based on this example to restream a 4k video pipeline coming from a source to at least 1 webrtc client (it'd be great to have more but just one that works ok would be our goal). The program itself is working fine for lower resolutions for a bunch of clients without loosing fps or video quality but with 4k the stream starts to randomly stop every 2-3 seconds and I'm trying to archive at least 20 stable fps (video source it's at 20fps, that could be changed).

The bottleneck and quality loss is definitely coming from the webrtc app since watching the stream at source is mostly fluid and stable, my first idea was to improve the gstreamer pipeline used but it's really basic so I don't know what could be changed about it:

`  pipeline =   "udpsrc multicast-group=224.1.1.1 auto-multicast=true port=5000 ! queue max-size-bytes=0 ! application/x-rtp,media=video,clock-rate=90000,encoding-name=VP8,payload=96, framerate=25/1 ! webrtcbin name=sendrecv latency=0";
`

What would be away to improve webrtc performance and stabilize the stream?

**Comment by ystreet** [comment]
Have you profiled your application to know where the hot spots are?

This is way too little information to give any meaningful answer to :).

**Comment by Yddeon** [comment]
Do you have any advice on how could I do that? I'm a bit new to all of this and I'm learning as I find problems

**Comment by ystreet** [comment]
Depends on your platform really.  You need to figure out if the problem is cpu (top), memory (perf), disk (iotop), network (iftop), etc (linux tools in brackets).

**Comment by Yddeon** [comment]
Oh I get what you mean, sorry.

I'm using an Nvidia Jetson TX2 board, and nvidia provides [tegrastats](https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3231/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/AppendixTegraStats.html) for profiling applications. This (I think) does not provide iotop info but disk shouldn't matter at all for this app.

My tegrastats output doesn't seem like it's suffering anywhere, that's why I don't understand where does the slowdown come from:


```
RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU 58%@1949,0%@2025,0%@2037,58%@2007,42%@2012,55%@2012] EMC_FREQ 25%@1866 GR3D_FREQ 2%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@40C MCPU@40C PMIC@100C Tboard@37C GPU@38.5C BCPU@40C thermal@39.8C Tdiode@38.5C VDD_SYS_GPU 1296/1296 VDD_SYS_SOC 2287/2287 VDD_4V0_WIFI 19/19 VDD_IN 9040/9040 VDD_SYS_CPU 1296/1296 VDD_SYS_DDR 2299/2299

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [39%@1913,0%@2035,0%@2035,41%@2035,28%@2035,46%@2036] EMC_FREQ 24%@1866 GR3D_FREQ 0%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38.5C BCPU@39.5C thermal@39.6C Tdiode@37.5C VDD_SYS_GPU 1220/1258 VDD_SYS_SOC 2212/2249 VDD_4V0_WIFI 19/19 VDD_IN 8467/8753 VDD_SYS_CPU 991/1143 VDD_SYS_DDR 2166/2232

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [44%@1945,0%@2025,0%@2034,51%@2023,40%@2023,44%@2008] EMC_FREQ 24%@1866 GR3D_FREQ 4%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@39.4C Tdiode@37.5C VDD_SYS_GPU 1144/1220 VDD_SYS_SOC 2212/2237 VDD_4V0_WIFI 19/19 VDD_IN 8544/8683 VDD_SYS_CPU 1143/1143 VDD_SYS_DDR 2185/2216

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [30%@1981,0%@2035,0%@2035,43%@2035,30%@2035,40%@2034] EMC_FREQ 23%@1866 GR3D_FREQ 0%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39C MCPU@39C PMIC@100C Tboard@37C GPU@38C BCPU@39C thermal@39.4C Tdiode@37.25C VDD_SYS_GPU 992/1163 VDD_SYS_SOC 2136/2211 VDD_4V0_WIFI 19/19 VDD_IN 7822/8468 VDD_SYS_CPU 915/1086 VDD_SYS_DDR 2052/2175

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [48%@1844,0%@2060,0%@2035,55%@2034,34%@2034,45%@2034] EMC_FREQ 23%@1866 GR3D_FREQ 0%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@38.9C Tdiode@37.5C VDD_SYS_GPU 992/1128 VDD_SYS_SOC 2136/2196 VDD_4V0_WIFI 19/19 VDD_IN 8013/8377 VDD_SYS_CPU 991/1067 VDD_SYS_DDR 2090/2158

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [35%@1912,0%@2057,0%@2035,39%@2035,34%@2035,35%@2035] EMC_FREQ 23%@1866 GR3D_FREQ 0%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@38.9C Tdiode@37.5C VDD_SYS_GPU 1068/1118 VDD_SYS_SOC 2212/2199 VDD_4V0_WIFI 19/19 VDD_IN 8204/8348 VDD_SYS_CPU 991/1054 VDD_SYS_DDR 2109/2150

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [35%@2034,0%@2035,0%@2036,48%@2035,31%@2036,37%@2035] EMC_FREQ 23%@1866 GR3D_FREQ 0%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@39.4C Tdiode@37.5C VDD_SYS_GPU 1068/1111 VDD_SYS_SOC 2212/2201 VDD_4V0_WIFI 19/19 VDD_IN 8277/8338 VDD_SYS_CPU 991/1045 VDD_SYS_DDR 2166/2152

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [40%@1991,0%@2035,0%@2036,47%@2028,40%@2028,34%@2024] EMC_FREQ 24%@1866 GR3D_FREQ 7%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@39.4C Tdiode@38C VDD_SYS_GPU 1144/1115 VDD_SYS_SOC 2288/2211 VDD_4V0_WIFI 19/19 VDD_IN 8544/8363 VDD_SYS_CPU 1067/1048 VDD_SYS_DDR 2204/2158

RAM 3929/7852MB (lfb 605x4MB) SWAP 0/3926MB (cached 0MB) CPU [31%@2049,0%@2035,0%@2034,42%@2036,31%@2035,52%@2035] EMC_FREQ 23%@1866 GR3D_FREQ 4%@1300 NVENC 1164 NVDEC 1203 APE 150 MTS fg 0% bg 0% PLL@39.5C MCPU@39.5C PMIC@100C Tboard@37C GPU@38C BCPU@39.5C thermal@39.4C Tdiode@38C VDD_SYS_GPU 1068/1110 VDD_SYS_SOC 2212/2211 VDD_4V0_WIFI 19/19 VDD_IN 8353/8362 VDD_SYS_CPU 1068/1050 VDD_SYS_DDR 2166/2159
```

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
