### ISSUE TITLE
multiparty-sendrecv, file description(socket) leak

### ISSUE THREAD

**Issue by soupim** [centricular/gstwebrtc-demos#215]
Hi.
When I test multiparty-sendrecv, I've found file description(socket) leak.
I runned two applications with same room-id(=1) like as 
 ./mp-webrtc-sendrecv --room-id=1 
and I checked connections.

When I close one application, I've found CLOSE_WAIT and LISTEN from netstat.
I expected that all network connections are cleared. 

Do you have any advice on how could I do that?

**Comment by ystreet** [comment]
This sounds like something that was fixed in either libnice or GStreamer recently.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
