### ISSUE TITLE
Too many connection attempts, aborting. Refresh page to try again

### ISSUE THREAD

**Issue by QXVTY** [centricular/gstwebrtc-demos#217]
Hi,
 it is still in normal use for a few days, and I cannot connect "https://webrtc.nirbheek.in/"  today. I found such a problem before, the link is as follows:  https://github.com/centricular/gstwebrtc-demos/issues/137    
I don’t know if this is the problem, I look forward to your answer, thank you!

**Comment by nirbheek** [comment]
This is fixed now, thanks for reporting.
