### ISSUE TITLE
How to use js/ directory instantiation locally https://webrtc.nirbheek.in/

### ISSUE THREAD

**Issue by QXVTY** [centricular/gstwebrtc-demos#218]
Hi, 
I am using sendrecv. I have realized https://webrtc.nirbheek.in/ to communicate with the local video, but I cannot use the files in the **js/** directory and **simple_server.py** to instantiate the local signaling service. Refer to the following content in **http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html** 

"**Yes, you need to start ./simple-server.py and point it to your HTTP server's certificate database, which must be signed by a CA.
If you don't have one of those, you can generate a self-signed certificate with ./generate_cert.sh and then tell your browser to accept it when prompted. On the gst side, you need to find the line "SOUP_SESSION_SSL_STRICT, TRUE ," and change it to "SOUP_SESSION_SSL_STRICT, FALSE,".**" 

Still unable to build, the web interface prompts "WebSocket connection to 'wss://xxx.xxx.xxx.xxx:8443/' failed: Error during WebSocket handshake: Unexpected response code: 200
webrtc.js:55 Unable to connect to server, did you add an exception for the certificate?"

How can I use **js/** and **simple_server.py** locally to achieve a function similar to https://webrtc.nirbheek.in/?

 Thank you very much and look forward to your help.

**Comment by lexus2k** [comment]
@QXVTY Hi

Did you figure out the solution?
I have similar problem.

Best regards
