### ISSUE TITLE
Multiple webrtcbin not showing streams

### ISSUE THREAD

**Issue by jaskarn-s-kalsi** [centricular/gstwebrtc-demos#220]
Hi,
I used the example code provided to spin up a pipeline that can serve multiple peers.
Once the first peer gets connected, it is able to show the video just fine.
when i attach new webrtcbin to the tee, i am able to send new sdp and ice messages to the receiver. I am using webrtc.js provided in the example as receiver.
For second peer i am not able to see any video. Do i have to change something on receiver side to get the stream working.
pipeline looks something like this.
videosrc -> ecoder -> rtph264pay -> application/x-rtp,media=video,encoding-name=H264,payload=123 -> tee -> queue -> fakesink
Then we attach queue -> webrtcbin for each peer with the tee.
SDP for first webrtcbin. this shows video in browser.
v=0
o=- 7531250391837001278 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0
m=video 9 UDP/TLS/RTP/SAVPF 123
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:lk2MhduAd0I9kpoJC9QXtIDVPJg3Vuvt
a=ice-pwd:RVGSub8QGW+dnqBResWt1S7CsoGpFX3y
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:123 H264/90000
a=rtcp-fb:123 nack pli
a=framerate:30
a=fmtp:123 packetization-mode=1;sprop-parameter-sets=Z2QAHqwrIBaGvzQgAAB9AAAdTBCA,aOuPLA==
a=ssrc:4136997112 msid:user3218621629@host-a027d500 webrtctransceiver0
a=ssrc:4136997112 cname:user3218621629@host-a027d500
a=mid:video0
a=fingerprint:sha-256 A5:F0:2C:D5:42:AA:92:1B:7E:30:A9:4F:B9:AA:51:05:FF:54:AD:EA:30:1B:D4:B3:5B:A8:21:1A:5A:69:39:78

SDP for second webrtcbin:
v=0
o=- 4158117608041698096 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0
m=video 9 UDP/TLS/RTP/SAVPF 123
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:dqfhJ8bdJzkXEdrkFUAQ8rpNa7RV5kOH
a=ice-pwd:xhNMkbraiyqIP69R7FeUC7ZAnFPiVgcx
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:123 H264/90000
a=rtcp-fb:123 nack pli
a=framerate:30
a=fmtp:123 packetization-mode=1;sprop-parameter-sets=Z2QAHqwrIBaGvzQgAAB9AAAdTBCA,aOuPLA==
a=ssrc:4136997112 msid:user176087587@host-1acaf03b webrtctransceiver1
a=ssrc:4136997112 cname:user176087587@host-1acaf03b
a=mid:video0
a=fingerprint:sha-256 A5:F0:2C:D5:42:AA:92:1B:7E:30:A9:4F:B9:AA:51:05:FF:54:AD:EA:30:1B:D4:B3:5B:A8:21:1A:5A:69:39:78

Thanks

**Comment by thaytan** [comment]
You should check that the encoder is generating keyframes periodically (or at least when new clients connect)

**Comment by sampleref** [comment]
U can also try setting **config-interval** on **rtph264pay**  to -1 or any non zero value

**Comment by jaskarn-s-kalsi** [comment]
@sampleref Thanks That solved the issue.
