### ISSUE TITLE
Sendrecv demo fails

### ISSUE THREAD

**Issue by alexfreed58** [centricular/gstwebrtc-demos#221]
Hi,

I have built the sendrecv demo on Ubuntu 18.04 by following the instructions verbatum.  Now I'm trying to run it. Opened the page on https://webrtc.nirbheek.in/ using Chrome (or Firefox).  Got the registered status and an ID. Start the demo with the same ID, but get an error. Clearly it's me missing something :( But what is it? 

./webrtc-sendrecv --peer-id = 6747
Connecting to server...
> GET  HTTP/1.1
> Soup-Debug-Timestamp: 1602297558
> Soup-Debug: SoupSession 1 (0x55bc80d85100), SoupMessage 1 (0x55bc813248d0), SoupSocket 1 (0x55bc80b93b70)
> Host: webrtc.nirbheek.in:8443
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Key: oZIl7wicsLts16pYkRyu2g==
> Sec-WebSocket-Version: 13
> Accept-Encoding: gzip, deflate

< HTTP/1.1 101 Switching Protocols
< Soup-Debug-Timestamp: 1602297558
< Soup-Debug: SoupMessage 1 (0x55bc813248d0)
< Upgrade: websocket
< Connection: Upgrade
< Sec-WebSocket-Accept: ice/lMQQTaSl2A/JyyyQJwkKpMU=
< Date: Sat, 10 Oct 2020 02:39:21 GMT
< Server: Python/3.7 websockets/8.1

Connected to signalling server
Registering id 6920 with server
Registered with server
Setting up signalling server call with =
ERROR peer '=' not found

(webrtc-sendrecv:19682): GLib-CRITICAL **: 19:39:18.659: g_main_loop_unref: assertion 'loop != NULL' failed

**Comment by framkant** [comment]
./webrtc-sendrecv --peer-id = 6747 should be ./webrtc-sendrecv --peer-id=6747
No spaces...
