### ISSUE TITLE
webrtc-unidirectional-h264 no video on browser

### ISSUE THREAD

**Issue by messageid** [centricular/gstwebrtc-demos#222]
Hi,
   I'm working on the example **webrtc-unidirectional-h264** to stream an USB webcam to browser but after many attempts I was unable to make it work.

I'm using gstreamer version 1.14.5 and using the pipeline (I tried videotestsrc without differences):
`webrtcbin name=webrtcbin stun-server=stun://" STUN_SERVER " v4l2src device=/dev/video0 do-timestamp=true ! videorate ! video/x-raw,width=640,height=360,framerate=15/1 ! videoconvert ! queue max-size-buffers=1 ! x264enc bitrate=600 speed-preset=ultrafast tune=zerolatency key-int-max=15 ! video/x-h264,profile=constrained-baseline,level=(string)4 ! queue max-size-time=100000000 ! h264parse ! rtph264pay config-interval=1 name=payloader ! application/x-rtp,media=video,encoding-name=H264,payload=" RTP_PAYLOAD_TYPE " ! webrtcbin. `

But when I connect to http://ip:57778 with Firefox, Chromium or Chrome I see the video element always "on loading" without the stream. On browser console there are no error.

This is the output of webrtc-uniderctional-h264 used with Chrome:
```
Processing new websocket connection 0x55a43f5960
Creating negotiation offer
Negotiation offer created:
v=0
o=- 7968106101378966704 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=msid-semantic:WMS webrtcbin
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:oC8hjZTn1oP21yrI34hr2KUGUk88MZH5
a=ice-pwd:F9ozEEFQ/OaPhja9QuMk7sFYxETshfWA
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:15
a=fmtp:96 packetization-mode=1;profile-level-id=42c028;sprop-parameter-sets=Z0LAKNoCgL/lwFqDAIKgAAADACAAAAMD0eMGVA==,aM48gA==
a=ssrc:3338267909 msid:user2071916704@host-6b0b6971 webrtctransceiver0
a=ssrc:3338267909 cname:user2071916704@host-6b0b6971
a=mid:video0
a=fingerprint:sha-256 FB:D4:80:87:E3:DD:BD:A2:CC:AA:E6:9B:71:E5:B2:49:E3:A6:49:EA:67:C3:42:71:57:43:80:4B:E6:FD:EF:8D

Received SDP:
v=0
o=- 7404214875006842748 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:t/q+
a=ice-pwd:NhCwVZ+wIPfj50r7u4cW7py+
a=ice-options:trickle
a=fingerprint:sha-256 AB:4F:FA:47:C5:9A:AE:04:B5:15:7D:BA:C4:CD:9D:65:C1:7A:47:06:F2:63:A1:EE:A3:98:F7:89:31:DA:26:65
a=setup:active
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

Received ICE candidate with mline index 0; candidate: candidate:2437072876 1 udp 2113937151 936eebef-0309-439d-adc8-cddd735a789e.local 37836 typ host generation 0 ufrag t/q+ network-cost 999

```

Do you have any suggestions ?

**Comment by thaytan** [comment]
Chrome and more recently Firefox have switched to masking local IPs by assigning them a .local name in the ICE candidates, and libnice (that GStreamer uses for WebRTC ICE) can't yet resolve those back to IPs, so the connections fail if that's the only ICE candidate available.

https://www.thespaghettidetective.com/docs/chrome-streaming-issue/ shows how to disable that in chrome for testing.

**Comment by messageid** [comment]
I have tried the thaytan suggestion but:

- Firefox 78.4.0 on linux: **don't work**
- Chromium 83.0 with enable-webrtc-hide-local-ips-with-mdns disabled on linux: **don't work**
- Chrome 86.0 that don't have the suggested param on linux: **don't work**
- Chrome 83.0 with enable-webrtc-hide-local-ips-with-mdns disabled on windows: **work**
- Firefox 81.0.2 on MacOS: **work**

It's strange ?! Maybe a problem with libnice ? My testing environment use gstreamer 1.14.5 and libnice version 0.1.14.

**Comment by ystreet** [comment]
I would very much suggest upgrading GStreamer and libnice to the latest stable versions.  Multiple issues have been fixed since.
