### ISSUE TITLE
When webrtc sends a real-time stream to the browser, the real-time stream is disconnected

### ISSUE THREAD

**Issue by 1happyboy** [centricular/gstwebrtc-demos#224]
When using webrtcbin to send a video stream, sometimes you can see the video on the browser side, but sometimes you can’t see the video, but the interactive data is there. It is found that the video stream is disconnected. What is the reason
Information in the file when gst-debug=5
![image](https://user-images.githubusercontent.com/34050345/98222642-0e41ae00-1f8c-11eb-9bc2-296fc6c37bc6.png)

**Comment by 1happyboy** [comment]
![QQ图片20201105172804](https://user-images.githubusercontent.com/34050345/98223322-e4d55200-1f8c-11eb-95aa-bc64ae79232b.png)
[MobaXterm_192.168.10.108root_20201105_143323.txt](https://github.com/centricular/gstwebrtc-demos/files/5493292/MobaXterm_192.168.10.108root_20201105_143323.txt)

**Comment by ystreet** [comment]
A BIO error from the dtls elements is not always fatal.  This may be an actual issue but could also be a false-positive.  Failing to see the received video from GStreamer in the browsers is usually the result of something else though.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
