### ISSUE TITLE
webrtc-sendrecv work only in localhost

### ISSUE THREAD

**Issue by rosciio** [centricular/gstwebrtc-demos#225]
I have tried webrtc-sendrecv.
I have modified wss -> ws, disabled ssl and it's works inside se same virtal machine. the same example doesn't works if I use an external browser. 

can someone help me?

Marco

**Comment by ystreet** [comment]
If you disable ssl, then browsers won't allow access to the websocket or media from external sources as the website is not trusted.   Depending on your browser depends on the specific requirements for what operations are possible for different domains.

**Comment by rosciio** [comment]
yes. I have enabled ssl and now it's works. 
thanks
