### ISSUE TITLE
Used gstreamer 1.18.1 to run demo code got error!!!

### ISSUE THREAD

**Issue by kikiyami** [centricular/gstwebrtc-demos#227]
Hi,
Before upgrade to GStreamer 1.18.1
I used GStreamer 1.16.2 to run demo code as well as work success.
A few days ago, I saw the GStreamer 1.18.1 and understood the newest version could resolve .local address.
So I upgrade GStreamer 1.18.1 and run the demo code.
But debug of browser shows the error message as below,

DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='video0'.

Thanks

**Comment by ystreet** [comment]
This is not enough information to debug why you are getting that particular error, sorry.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
