### ISSUE TITLE
sendrecv implements voice calls, using local signaling, the sound on the client side is normal, but there is no sound on the web side

### ISSUE THREAD

**Issue by QXVTY** [centricular/gstwebrtc-demos#228]
Hi,
      I am using the sendrecv case, and created a signaling service locally using simple_server.py and js files. In order to implement the voice call function, the pipeline in webrtc-sendrecv.c is modified.
"alsasrc device=hw:2,0 ! audioconvert ! audioresample ! queue ! opusenc audio-type=voice ! rtpopuspay ! "
 After the link is established, the web audio is sent to the local client. It plays normally, but there is no sound when the reverse local client sends to the web side. After changing the server_url to https://webrtc.nirbheek.in:8443, the same operation, the web and client voice calls are normal. 
     I am currently in trouble. Do you have any suggestions? 
     Looking forward to your reply... 
Thank you!

**Comment by QXVTY** [comment]
The web service runs inside the docker, and the signaling runs outside the docker. This may be the cause of the connection problem. The problem of running the web service outside the docker no longer occurs

**Comment by thaytan** [comment]
I would also suggest looking at the STUN servers configured in each case

**Comment by QXVTY** [comment]
Hello, thanks for your reply
The following are the latest developments:
The only difference between the two cases is the location where webrtc.js is called, one is inside docker and the other is outside docker. The stun used by webrtc.js is the same. Or you mean that the stun services that can be used by different environments are different, But I did another video implementation in the same direction, which is normal in both cases, which confuses me.
In addition, I checked the stats in the two cases in chrome://webrtc-internals , and found that in the case of no sound, the audioLevel/totalAudioEnergy/[Audio_Level_in_RMS] three parameters in the Statistics RTCMediaStreamTrack_receiver_xx in the received remote data It is always 0. Do you have any suggestions on this phenomenon?
Looking forward to your reply again, thank you very much!

**Comment by QXVTY** [comment]
> I would also suggest looking at the STUN servers configured in each case

Hi, thanks for your reply
The following are the latest developments:
The only difference between the two cases is the location where webrtc.js is called, one is inside docker and the other is outside docker. The stun used by webrtc.js is the same. Or you mean that the stun services that can be used by different environments are different, But I did another video implementation in the same direction, which is normal in both cases, which confuses me.
In addition, I checked the stats in the two cases in chrome://webrtc-internals , and found that in the case of no sound, the audioLevel/totalAudioEnergy/[Audio_Level_in_RMS] three parameters in the Statistics RTCMediaStreamTrack_receiver_xx in the received remote data It is always 0. Do you have any suggestions on this phenomenon?
Looking forward to your reply again, thank you very much!
