### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by nirvitarka** [centricular/gstwebrtc-demos#229]
After trying installation of all packages, I am still not able to get the webrtc_sendrecv.y example working on raspberry pi.

I tried steps mentioned on below links:

https://gist.github.com/sphaero/02717b0b35501ad94863
https://gist.github.com/Brainiarc7/9f9b3de1246c0316f2a273c80841cadc

Can someone please guide me to a good source showing correct steps to install everything required to run these demos on raspberry pi buster?

I see this message 
Missing gstreamer plugins: ['webrtc', 'dtls', 'srtp']

**Comment by ystreet** [comment]
The standard process for developing GStreamer itself (or even using a newer version of GStreamer than is provided by the linux distribution) is to use https://gitlab.freedesktop.org/gstreamer/gst-build/.  This allows one to build and develop against a newer version of GStreamer than is available from the system.  All the build dependencies would still be required if taking this approach.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
