### ISSUE TITLE
(python3:12664): libnice-CRITICAL **: 16:56:58.187: nice_agent_parse_remote_candidate_sdp: assertion 'sdp != NULL' failed

### ISSUE THREAD

**Issue by tankienleong** [centricular/gstwebrtc-demos#230]
ubuntu 18.04, gstreamer 1.16
(python3:12664): libnice-CRITICAL **: 16:56:58.187: nice_agent_parse_remote_candidate_sdp: assertion 'sdp != NULL' failed
anyone faced this error before?

**Comment by ystreet** [comment]
This seems like something that was fixed in GStreamer a while ago.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
