### ISSUE TITLE
Connection fails when trying to connect to webRTC stream on a remote system browser

### ISSUE THREAD

**Issue by deep-saxena** [centricular/gstwebrtc-demos#232]
I am able to run the send-recv example, when the https://webrtc.nirbheek.in/ is open on my own system and i run the python version of send-recv on my own system. In that case the connection is established and webcam stream is displayed on gstreamer videosink and ball pattern testsrc on the browser

But when the link is opened on another system and i run the python script on another system (entering the peer id displayed on remote system browser) the ICE connection fails and streaming does not start.
Following are the libnice debug logs after ice candidate are received

> ========================== {"ice":{"candidate":"candidate:3775701198 1 udp 2122262783 2401:4900:110c:26ac:79bb:7864:2f3b:4586 37383 typ host generation 0 ufrag DK9n network-id 2 network-cost 10","sdpMid":"video0","sdpMLineIndex":0}}
> 
> Ice CANDIDATE candidate:3775701198 1 udp 2122262783 2401:4900:110c:26ac:79bb:7864:2f3b:4586 37383 typ host generation 0 ufrag DK9n network-id 2 network-cost 10
> ========================== {"ice":{"candidate":"candidate:3062301492 1 udp 2122194687 192.168.43.228 52812 typ host generation 0 ufrag DK9n network-id 1 network-cost 10","sdpMid":"video0","sdpMLineIndex":0}}
> Ice CANDIDATE candidate:3062301492 1 udp 2122194687 192.168.43.228 52812 typ host generation 0 ufrag DK9n network-id 1 network-cost 10
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040: set_remote_candidates 1 1
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : Adding UDP remote candidate with addr [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383 for s1/c1. U/P '(null)'/'(null)' prio: 2122262783
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : Adding check pair between 1 and 3775701198 for s1/c1
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : creating new pair 0x7f1d940bff70 state 5
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : new pair 0x7f1d940bff70 : [fe80::867f:99e3:ebe5:2036]:47790 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : added a new conncheck 0x7f1d940bff70 with foundation of '1:3775701198' to list 1.
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : stream 1 component 1 STATE-CHANGE disconnected -> connecting.
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : Adding check pair between 4 and 3775701198 for s1/c1
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : creating new pair 0x7f1d940c07a0 state 5
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : new pair 0x7f1d940c07a0 : [2401:4900:1f3a:5092:a1c9:4cd1:1e21:7ff8]:37505 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : added a new conncheck 0x7f1d940c07a0 with foundation of '4:3775701198' to list 1.
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : Adding check pair between 7 and 3775701198 for s1/c1
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : creating new pair 0x7f1d940c0db0 state 5
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : new pair 0x7f1d940c0db0 : [2401:4900:1f3a:5092:dc25:78a2:72c5:cc74]:53237 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:26.325: Agent 0x292a040 : added a new conncheck 0x7f1d940c0db0 with foundation of '7:3775701198' to list 1.
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040: set_remote_candidates 1 1
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040 : Adding UDP remote candidate with addr [192.168.43.228]:52812 for s1/c1. U/P '(null)'/'(null)' prio: 2122194687
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040 : Adding check pair between 10 and 3062301492 for s1/c1
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040 : creating new pair 0x7f1d940c13c0 state 5
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040 : new pair 0x7f1d940c13c0 : [192.168.1.3]:50597 --> [192.168.43.228]:52812
> (python:21656): libnice-DEBUG: 20:06:26.326: Agent 0x292a040 : added a new conncheck 0x7f1d940c13c0 with foundation of '10:3062301492' to list 1.
> (python:21656): libnice-DEBUG: 20:06:26.346: Agent 0x292a040 : stream 1: timer tick #1: 4 frozen, 0 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:26.346: Agent 0x292a040 : Pair 0x7f1d940bff70 with s/c-id 1/1 (1:3775701198) unfrozen.
> (python:21656): libnice-DEBUG: 20:06:26.346: Agent 0x292a040 : pair 0x7f1d940bff70 state WAITING
> (python:21656): libnice-DEBUG: 20:06:26.346: Agent 0x292a040 : pair 0x7f1d940bff70 state IN_PROGRESS
> (python:21656): libnice-DEBUG: 20:06:26.346: Agent 0x292a040 : STUN-CC REQ [fe80::867f:99e3:ebe5:2036]:47790 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383, socket=29, pair=1:3775701198 (c-id:1), tie=5875957570451824408, username='DK9n:wEVnPO53oOs9fFvvTcyewKux1M9SPKeI' (37), password='Fznq6BrazSM++PLr/jwXwuYw' (24), prio=1845494271, cont=1.
> (python:21656): libnice-stun-DEBUG: 20:06:26.348:  Message HMAC-SHA1 message integrity:
> (python:21656): libnice-stun-DEBUG: 20:06:26.348:   key     : 0x467a6e71364272617a534d2b2b504c722f6a775877755977
> (python:21656): libnice-stun-DEBUG: 20:06:26.348:   sent    : 0x3c546cbdee65916f3912b09fcd67e7fe540b6aa7
> (python:21656): libnice-stun-DEBUG: 20:06:26.348:  Message HMAC-SHA1 fingerprint: 0xdd1bda27
> (python:21656): libnice-DEBUG: 20:06:26.348: Agent 0x292a040: conncheck created 120 - 0x7f1d940c0030
> (python:21656): libnice-DEBUG: 20:06:26.348: Agent 0x292a040 : timer set to 100ms (waiting+in_progress=1)
> ========================== {"ice":{"candidate":"candidate:2945408062 1 tcp 1518283007 2401:4900:110c:26ac:79bb:7864:2f3b:4586 9 typ host tcptype active generation 0 ufrag DK9n network-id 2 network-cost 10","sdpMid":"video0","sdpMLineIndex":0}}
> Ice CANDIDATE candidate:2945408062 1 tcp 1518283007 2401:4900:110c:26ac:79bb:7864:2f3b:4586 9 typ host tcptype active generation 0 ufrag DK9n network-id 2 network-cost 10
> ========================== {"ice":{"candidate":"candidate:4161077188 1 tcp 1518214911 192.168.43.228 9 typ host tcptype active generation 0 ufrag DK9n network-id 1 network-cost 10","sdpMid":"video0","sdpMLineIndex":0}}
> Ice CANDIDATE candidate:4161077188 1 tcp 1518214911 192.168.43.228 9 typ host tcptype active generation 0 ufrag DK9n network-id 1 network-cost 10
> (python:21656): libnice-DEBUG: 20:06:26.351: Agent 0x292a040: set_remote_candidates 1 1
> (python:21656): libnice-DEBUG: 20:06:26.351: Agent 0x292a040 : Adding TCP-ACT remote candidate with addr [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:9 for s1/c1. U/P '(null)'/'(null)' prio: 1518283007
> (python:21656): libnice-DEBUG: 20:06:26.351: Agent 0x292a040: set_remote_candidates 1 1
> (python:21656): libnice-DEBUG: 20:06:26.351: Agent 0x292a040 : Adding TCP-ACT remote candidate with addr [192.168.43.228]:9 for s1/c1. U/P '(null)'/'(null)' prio: 1518214911
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040 : Pair 0x7f1d940c07a0 with s/c-id 1/1 (4:3775701198) unfrozen.
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040 : pair 0x7f1d940c07a0 state WAITING
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040 : pair 0x7f1d940c07a0 state IN_PROGRESS
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040 : STUN-CC REQ [2401:4900:1f3a:5092:a1c9:4cd1:1e21:7ff8]:37505 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383, socket=36, pair=4:3775701198 (c-id:1), tie=5875957570451824408, username='DK9n:wEVnPO53oOs9fFvvTcyewKux1M9SPKeI' (37), password='Fznq6BrazSM++PLr/jwXwuYw' (24), prio=1845494270, cont=1.
> (python:21656): libnice-stun-DEBUG: 20:06:26.366:  Message HMAC-SHA1 message integrity:
> (python:21656): libnice-stun-DEBUG: 20:06:26.366:   key     : 0x467a6e71364272617a534d2b2b504c722f6a775877755977
> (python:21656): libnice-stun-DEBUG: 20:06:26.366:   sent    : 0xf13570ecc41295493d4bcad99ddce1cc8a132d1d
> (python:21656): libnice-stun-DEBUG: 20:06:26.366:  Message HMAC-SHA1 fingerprint: 0xa4b80574
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040: conncheck created 120 - 0x7f1d940c0860
> (python:21656): libnice-DEBUG: 20:06:26.366: Agent 0x292a040 : timer set to 100ms (waiting+in_progress=2)
> ========================== {"ice":{"candidate":"candidate:2047491239 1 udp 1685987071 182.66.20.135 41848 typ srflx raddr 192.168.43.228 rport 52812 generation 0 ufrag DK9n network-id 1 network-cost 10","sdpMid":"video0","sdpMLineIndex":0}}
> Ice CANDIDATE candidate:2047491239 1 udp 1685987071 182.66.20.135 41848 typ srflx raddr 192.168.43.228 rport 52812 generation 0 ufrag DK9n network-id 1 network-cost 10
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040: set_remote_candidates 1 1
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040 : Adding UDP remote candidate with addr [182.66.20.135]:41848 for s1/c1. U/P '(null)'/'(null)' prio: 1685987071
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040 : Adding check pair between 10 and 2047491239 for s1/c1
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040 : creating new pair 0x7f1d940c1d90 state 5
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040 : new pair 0x7f1d940c1d90 : [192.168.1.3]:50597 --> [182.66.20.135]:41848
> (python:21656): libnice-DEBUG: 20:06:26.368: Agent 0x292a040 : added a new conncheck 0x7f1d940c1d90 with foundation of '10:2047491239' to list 1.
> (python:21656): libnice-DEBUG: 20:06:26.386: Agent 0x292a040 : Pair 0x7f1d940c0db0 with s/c-id 1/1 (7:3775701198) unfrozen.
> (python:21656): libnice-DEBUG: 20:06:26.386: Agent 0x292a040 : pair 0x7f1d940c0db0 state WAITING
> (python:21656): libnice-DEBUG: 20:06:26.386: Agent 0x292a040 : pair 0x7f1d940c0db0 state IN_PROGRESS
> (python:21656): libnice-DEBUG: 20:06:26.386: Agent 0x292a040 : STUN-CC REQ [2401:4900:1f3a:5092:dc25:78a2:72c5:cc74]:53237 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383, socket=38, pair=7:3775701198 (c-id:1), tie=5875957570451824408, username='DK9n:wEVnPO53oOs9fFvvTcyewKux1M9SPKeI' (37), password='Fznq6BrazSM++PLr/jwXwuYw' (24), prio=1845494269, cont=1.
> (python:21656): libnice-stun-DEBUG: 20:06:26.386:  Message HMAC-SHA1 message integrity:
> (python:21656): libnice-stun-DEBUG: 20:06:26.386:   key     : 0x467a6e71364272617a534d2b2b504c722f6a775877755977
> (python:21656): libnice-stun-DEBUG: 20:06:26.386:   sent    : 0x7c1b5ce2b63e6d04b7e6e57c9516d6fe5954f75b
> (python:21656): libnice-stun-DEBUG: 20:06:26.386:  Message HMAC-SHA1 fingerprint: 0x0bf0d1d4
> (python:21656): libnice-DEBUG: 20:06:26.386: Agent 0x292a040: conncheck created 120 - 0x7f1d940c0e70
> (python:21656): libnice-DEBUG: 20:06:26.387: Agent 0x292a040 : timer set to 100ms (waiting+in_progress=3)
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040 : Pair 0x7f1d940c13c0 with s/c-id 1/1 (10:3062301492) unfrozen.
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040 : pair 0x7f1d940c13c0 state WAITING
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040 : pair 0x7f1d940c13c0 state IN_PROGRESS
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040 : STUN-CC REQ [192.168.1.3]:50597 --> [192.168.43.228]:52812, socket=40, pair=10:3062301492 (c-id:1), tie=5875957570451824408, username='DK9n:wEVnPO53oOs9fFvvTcyewKux1M9SPKeI' (37), password='Fznq6BrazSM++PLr/jwXwuYw' (24), prio=1845494268, cont=1.
> (python:21656): libnice-stun-DEBUG: 20:06:26.407:  Message HMAC-SHA1 message integrity:
> (python:21656): libnice-stun-DEBUG: 20:06:26.407:   key     : 0x467a6e71364272617a534d2b2b504c722f6a775877755977
> (python:21656): libnice-stun-DEBUG: 20:06:26.407:   sent    : 0x6b349b17260d909a84bfbc89bab0c05a9bc6574c
> (python:21656): libnice-stun-DEBUG: 20:06:26.407:  Message HMAC-SHA1 fingerprint: 0xccf016b1
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040: conncheck created 120 - 0x7f1d940c1480
> (python:21656): libnice-DEBUG: 20:06:26.407: Agent 0x292a040 : timer set to 100ms (waiting+in_progress=4)
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040 : Pair 0x7f1d940c1d90 with s/c-id 1/1 (10:2047491239) unfrozen.
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040 : pair 0x7f1d940c1d90 state WAITING
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040 : pair 0x7f1d940c1d90 state IN_PROGRESS
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040 : STUN-CC REQ [192.168.1.3]:50597 --> [182.66.20.135]:41848, socket=40, pair=10:2047491239 (c-id:1), tie=5875957570451824408, username='DK9n:wEVnPO53oOs9fFvvTcyewKux1M9SPKeI' (37), password='Fznq6BrazSM++PLr/jwXwuYw' (24), prio=1845494267, cont=1.
> (python:21656): libnice-stun-DEBUG: 20:06:26.427:  Message HMAC-SHA1 message integrity:
> (python:21656): libnice-stun-DEBUG: 20:06:26.427:   key     : 0x467a6e71364272617a534d2b2b504c722f6a775877755977
> (python:21656): libnice-stun-DEBUG: 20:06:26.427:   sent    : 0x68dbe3f6959ef7a5f1153e8c590c94b1834dc7ad
> (python:21656): libnice-stun-DEBUG: 20:06:26.427:  Message HMAC-SHA1 fingerprint: 0xe549da19
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040: conncheck created 120 - 0x7f1d940c1e50
> (python:21656): libnice-DEBUG: 20:06:26.427: Agent 0x292a040 : timer set to 100ms (waiting+in_progress=5)
> (python:21656): libnice-DEBUG: 20:06:26.448: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 200ms, delay=200ms, retrans=2).
> (python:21656): libnice-DEBUG: 20:06:26.468: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 198ms, delay=200ms, retrans=2).
> (python:21656): libnice-DEBUG: 20:06:26.488: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 198ms, delay=200ms, retrans=2).
> (python:21656): libnice-DEBUG: 20:06:26.508: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 198ms, delay=200ms, retrans=2).
> (python:21656): libnice-DEBUG: 20:06:26.529: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 198ms, delay=200ms, retrans=2).
> (python:21656): libnice-DEBUG: 20:06:26.649: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 398ms, delay=400ms, retrans=3).
> (python:21656): libnice-DEBUG: 20:06:26.670: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 396ms, delay=400ms, retrans=3).
> (python:21656): libnice-DEBUG: 20:06:26.690: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 396ms, delay=400ms, retrans=3).
> (python:21656): libnice-DEBUG: 20:06:26.710: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 396ms, delay=400ms, retrans=3).
> (python:21656): libnice-DEBUG: 20:06:26.730: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 397ms, delay=400ms, retrans=3).
> (python:21656): libnice-DEBUG: 20:06:27.052: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 796ms, delay=800ms, retrans=4).
> (python:21656): libnice-DEBUG: 20:06:27.072: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 794ms, delay=800ms, retrans=4).
> (python:21656): libnice-DEBUG: 20:06:27.093: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 795ms, delay=800ms, retrans=4).
> (python:21656): libnice-DEBUG: 20:06:27.113: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 795ms, delay=800ms, retrans=4).
> (python:21656): libnice-DEBUG: 20:06:27.133: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 795ms, delay=800ms, retrans=4).
> (python:21656): libnice-DEBUG: 20:06:27.656: Agent 0x292a040 : stream 1: timer tick #51: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:27.857: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 1591ms, delay=1600ms, retrans=5).
> (python:21656): libnice-DEBUG: 20:06:27.877: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 1590ms, delay=1600ms, retrans=5).
> (python:21656): libnice-DEBUG: 20:06:27.897: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 1590ms, delay=1600ms, retrans=5).
> (python:21656): libnice-DEBUG: 20:06:27.917: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 1590ms, delay=1600ms, retrans=5).
> (python:21656): libnice-DEBUG: 20:06:27.938: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 1590ms, delay=1600ms, retrans=5).
> (python:21656): libnice-DEBUG: 20:06:28.761: Agent 0x292a040 : stream 1: timer tick #101: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:29.465: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 3182ms, delay=3200ms, retrans=6).
> (python:21656): libnice-DEBUG: 20:06:29.485: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 3180ms, delay=3200ms, retrans=6).
> (python:21656): libnice-DEBUG: 20:06:29.506: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 3181ms, delay=3200ms, retrans=6).
> (python:21656): libnice-DEBUG: 20:06:29.526: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 3181ms, delay=3200ms, retrans=6).
> (python:21656): libnice-DEBUG: 20:06:29.546: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 3181ms, delay=3200ms, retrans=6).
> (python:21656): libnice-DEBUG: 20:06:29.868: Agent 0x292a040 : stream 1: timer tick #151: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:30.874: Agent 0x292a040 : stream 1: timer tick #201: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:31.881: Agent 0x292a040 : stream 1: timer tick #251: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:32.664: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940bff70 (timeout 6383ms, delay=6400ms, retrans=7).
> (python:21656): libnice-DEBUG: 20:06:32.684: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c07a0 (timeout 6381ms, delay=6400ms, retrans=7).
> (python:21656): libnice-DEBUG: 20:06:32.704: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c0db0 (timeout 6382ms, delay=6400ms, retrans=7).
> (python:21656): libnice-DEBUG: 20:06:32.725: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c13c0 (timeout 6382ms, delay=6400ms, retrans=7).
> (python:21656): libnice-DEBUG: 20:06:32.745: Agent 0x292a040 :STUN transaction retransmitted on pair 0x7f1d940c1d90 (timeout 6382ms, delay=6400ms, retrans=7).
> (python:21656): libnice-DEBUG: 20:06:32.986: Agent 0x292a040 : stream 1: timer tick #301: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:33.991: Agent 0x292a040 : stream 1: timer tick #351: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:34.996: Agent 0x292a040 : stream 1: timer tick #401: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:36.000: Agent 0x292a040 : stream 1: timer tick #451: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:37.004: Agent 0x292a040 : stream 1: timer tick #501: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:38.009: Agent 0x292a040 : stream 1: timer tick #551: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:39.013: Agent 0x292a040 : stream 1: timer tick #601: 0 frozen, 5 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom, 0 valid.
> (python:21656): libnice-DEBUG: 20:06:39.053: Agent 0x292a040 : Retransmissions failed, giving up on connectivity check 0x7f1d940bff70
> (python:21656): libnice-DEBUG: 20:06:39.053: Agent 0x292a040 : Failed pair is [fe80::867f:99e3:ebe5:2036]:47790 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:39.053: Agent 0x292a040 : pair 0x7f1d940bff70 state FAILED
> (python:21656): libnice-DEBUG: 20:06:39.073: Agent 0x292a040 : Retransmissions failed, giving up on connectivity check 0x7f1d940c07a0
> (python:21656): libnice-DEBUG: 20:06:39.073: Agent 0x292a040 : Failed pair is [2401:4900:1f3a:5092:a1c9:4cd1:1e21:7ff8]:37505 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:39.073: Agent 0x292a040 : pair 0x7f1d940c07a0 state FAILED
> (python:21656): libnice-DEBUG: 20:06:39.094: Agent 0x292a040 : Retransmissions failed, giving up on connectivity check 0x7f1d940c0db0
> (python:21656): libnice-DEBUG: 20:06:39.094: Agent 0x292a040 : Failed pair is [2401:4900:1f3a:5092:dc25:78a2:72c5:cc74]:53237 --> [2401:4900:110c:26ac:79bb:7864:2f3b:4586]:37383
> (python:21656): libnice-DEBUG: 20:06:39.094: Agent 0x292a040 : pair 0x7f1d940c0db0 state FAILED
> (python:21656): libnice-DEBUG: 20:06:39.114: Agent 0x292a040 : Retransmissions failed, giving up on connectivity check 0x7f1d940c13c0
> (python:21656): libnice-DEBUG: 20:06:39.114: Agent 0x292a040 : Failed pair is [192.168.1.3]:50597 --> [192.168.43.228]:52812
> (python:21656): libnice-DEBUG: 20:06:39.114: Agent 0x292a040 : pair 0x7f1d940c13c0 state FAILED
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : Retransmissions failed, giving up on connectivity check 0x7f1d940c1d90
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : Failed pair is [192.168.1.3]:50597 --> [182.66.20.135]:41848
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : pair 0x7f1d940c1d90 state FAILED
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : priv_conn_check_tick_unlocked: stopping conncheck timer
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : stream 1 component 1 STATE-CHANGE connecting -> failed.
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : conn.check list status: 0 nominated, 0 valid, c-id 1.
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : conn.check list status: 0 nominated, 0 valid, c-id 2.
> (python:21656): libnice-DEBUG: 20:06:39.134: Agent 0x292a040 : changing conncheck state to COMPLETED.`

**Comment by ystreet** [comment]
This may be due to any number of network related architectures or scenarios.  The examples do not make use of TURN at all so if there is no direct path, then the connection will fail.

These examples have also moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc.
