### ISSUE TITLE
What is this supposed to demo?

### ISSUE THREAD

**Issue by sunapi386** [centricular/gstwebrtc-demos#24]
* I see the ball rolling around in the browser. 
* I see my own video feed when I run `./webrtc-sendrecv --peer-id <id given in https://webrtc.nirbheek.in/>`.

What I expect to see is (1) a program to stream up your own video/audio device or a test source encoded in webRTC, telling where to stream-to (2) a program to pull down the video/audio webRTC source and render it. But seems like I get one tool, `webrtc-sendrecv` that does both?

Seems to me that `webrtc-sendrecv.c` implements the 

1. Handshake (proposed in signalling/Protocol.md)
2. Starts the video capture from device.
3. Streams it up to the server? Or maybe locally? 
4. Opens a GUI window and I can see my camera feed, with a bit of latency delay.

I am confused why this is one program, I expect two. Also unclear from reading the readme, so I read through the code. It seems like it implements steps 1-4 in one program.

**Comment by sunapi386** [comment]
From your blog http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html it seems the goal is to capture video from V4L2, stream it to a webrtc peer, and receive video back from it. So to clarify this issue, I was expecting this to be two separate programs because then I can run it on different machines and under different network conditions to test performance.

**Comment by ystreet** [comment]
It's supposed to demo the use of webrtcbin as akin to the PeerConnection API in that a single PeerConnection can send and receive (possibly) multiple streams.  If you want something different (like different streams, only send, only receive), you have to write your own signalling/implementation.

There are also simple examples in https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/tests/examples/webrtc that do one-way streaming.
