### ISSUE TITLE
GstWebRTC does not work with MacOS 10.12.6

### ISSUE THREAD

**Issue by juniiorlima** [centricular/gstwebrtc-demos#26]
Hello, thank you for making this material available.

I have tried compiling the example webrtc-sendrecv.py but I did not succeed.

I Tried:

```
import gi
gi.require_version('Gst', '1.0')
from gi.repository import Gst
gi.require_version('GstSdp', '1.0')
from gi.repository import GstSdp
gi.require_version('GstWebRTC', '1.0')
from gi.repository import GstWebRTC
```

I get:
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GstWebRTC not available

I installed gst-python with "brew install gst-python"

brew info gst-python
gst-python: stable 1.14.1 (bottled)
Python overrides for gobject-introspection-based pygst bindings
https://gstreamer.freedesktop.org/modules/gst-python.html
/usr/local/Cellar/gst-python/1.14.1 (12 files, 395KB) *
  Poured from bottle on 2018-06-23 at 03:19:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-python.rb
==> Dependencies
Required: gst-plugins-base ✔, pygobject3 ✔
Recommended: python ✔
Optional: python@2 ✔

What could be wrong?
It's strange that Gst and Gst Sdp work while Gst WebRtc does not

**Comment by sdroege** [comment]
The WebRTC bindings would require files from gst-plugins-bad, i.e. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-bad.rb (same as the others require files from gstreamer core and gst-plugins-base). I'm not sure if Homebrew is including those, but if you don't have gst-plugins-bad installed please do so and try again.

There should be a GstWebRTC-1.0.typelib provided by that one.

**Comment by 0x0c** [comment]
I solved this issue. The reason of this issue is that when install `gst-plugins-bad` by homebrew, ` GstWebRTC-1.0.typelib` is not generated. So I generate it manually as follows

1. install these.
```
brew install libffi
brew install gobject-introspection
```

2. add `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig` to your rc file like `.zshrc`.

3. clone `gst-plugins-bad` from https://github.com/GStreamer/gst-plugins-bad and run `$ ./autogen.sh`

4. move to `gst-libs/gst/webrtc` directory and run `$ make` then run `$ make install`

5. move to `ext/webrtc` directory and run `$ make` then run `$ make install`

I think this is workaround solution and I'm looking for install `GstWebRTC-1.0.typelib` by homebrew.

**Comment by 0x0c** [comment]
Ah, my solution cause following errors...

```
0:00:06.708719000 82484 0x7fca7d269850 ERROR              gldisplay gstgldisplay_cocoa.m:171:GstGLDisplayCocoa *gst_gl_display_cocoa_setup_nsapp(gpointer): Custom NSApp initialization failed
0:00:06.708860000 82484 0x7fca7d269850 ERROR                glutils gstglutils.c:229:void gst_gl_element_propagate_display_context(GstElement *, GstGLDisplay *):<sink> Could not get GL display connection
[1]    82484 illegal hardware instruction  python3 sendrecv/gst/webrtc-sendrecv.py 5096
```

**Comment by matthew1000** [comment]
In case it hasn't been spotted, the comments here talk about how 1.14.1 (the latest version that Homebrew has) isn't enough for Python WebRTC to work:

https://github.com/centricular/gstwebrtc-demos/commit/9a264159453b7ab60e77a41feb90d8f1ac6032a1

I don't think homebrew can be persuaded to checkout the 1.14 branch, but you could upgrade streamer/bad/ugly to the latest dev (1.15) using `--head`. Or wait for 1.14.2.

**Comment by 0x0c** [comment]
I installed gstreamer/bad/ugly using `--head` but python example not work in same issue.
https://github.com/centricular/gstwebrtc-demos/issues/26#issue-335134893

**Comment by juniiorlima** [comment]
Using --head did not work. The version continues to be 1.14.1.
I had the same problem using apt-get on Ubuntu.

**Comment by notedit** [comment]
same issue.

**Comment by notedit** [comment]
After install  gstreamer/base/bad/good  all  from head,  still have this issuse.

**Comment by lpasarel** [comment]
Hi guys,

I have managed to fix `GstWebRTC-1.0.typelib` installation issue by adding (`brew edit gst-plugins-bad`):
```
depends_on "gobject-introspection" => :build
--enable-introspection=yes
```
as in:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-base.rb

and reinstalling the gst plugins
```
brew reinstall --build-from-source gst-plugins-base
brew reinstall --build-from-source gst-plugins-bad
```

**Comment by notedit** [comment]
@LucianZala  Hi,  can you give more details about where add that two lines?

**Comment by notedit** [comment]
@LucianZala  Thanks,  it works.

**Comment by dmanpearl** [comment]
Hello. Thank you for the work you have done on WebRTC and congratulations on the _fairly_ recent merge into GStreamer 1.4.x. As a regular user of GStreamer via command line and C/C++ I am having a difficult time getting started with WebRTC. I am trying to follow the Centricular demo and this blog, but there does not seem to be a concise/direct step-by-step guide. My goal is to create a server that streams to a mobile client, but I would happily start with any web client. I am on a Mac but have Docker experience. Is there a getting started guide that I have not yet found?

**Comment by ystreet** [comment]
I think we can close this as homebrew has been updated.

@dmanpearl Have you looked at the README.md and http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html ?

**Comment by kevkid** [comment]
> Hello. Thank you for the work you have done on WebRTC and congratulations on the _fairly_ recent merge into GStreamer 1.4.x. As a regular user of GStreamer via command line and C/C++ I am having a difficult time getting started with WebRTC. I am trying to follow the Centricular demo and this blog, but there does not seem to be a concise/direct step-by-step guide. My goal is to create a server that streams to a mobile client, but I would happily start with any web client. I am on a Mac but have Docker experience. Is there a getting started guide that I have not yet found?

yes there is no real good guide on how it works, try the tutorials point webrtc tutorial and come back to this. It helped me a lot. and if you have questions ask
