### ISSUE TITLE
webrtcmulti.js

### ISSUE THREAD

**Issue by joaogvfelix** [centricular/gstwebrtc-demos#29]
Please can you see this https://github.com/centricular/gstwebrtc-demos/compare/master...joaogvfelix:patch-2, and try to fix this peer_connection.onaddstream = onRemoteStreamAdded;, cause this never start

**Comment by joaogvfelix** [comment]
i already can get the sound from browser but not from gstreamer

**Comment by joaogvfelix** [comment]
anyhelp?

**Comment by ystreet** [comment]
Unfortunately we don't have the capacity/bandwidth to review this in any meaningful capacity.  Sorry.
