### ISSUE TITLE
plugin 'opus' not found

### ISSUE THREAD

**Issue by SUlbrichA** [centricular/gstwebrtc-demos#33]
Hi

I build all plugins required to run `webrtc-sendrec` and although the `opus` in plugins-bad has been built and installed (to `/usr/local/lib/gstreamer-1.0/libgstopusparse.so` and `libgstopusparse.la`), I get the error message:
```
required gstreamer plugin 'opus' not found
```
What could be the problem? 
Ubuntu 16.04, gstreamer (& plugins): 1.14.1 

Best
Stefan

**Comment by maxmcd** [comment]
I believe you'll need:
```
./usr/lib/gstreamer-1.0/libgstopusparse.la
./usr/lib/gstreamer-1.0/libgstopusparse.so
./usr/lib/gstreamer-1.0/libgstopus.la
./usr/lib/gstreamer-1.0/libgstopus.so
```

How are you building?

**Comment by lpasarel** [comment]
@SUlbrichA make sure that you have `opus-tools` and `gst-plugins-base` installed

https://gstreamer.freedesktop.org/documentation/plugins.html

**Comment by SUlbrichA** [comment]
@LucianZala Thank you that resolved the issue!

As a side note: I built the gstreamer packages without cerbero (just plain autoconf/configure/make install)
`gst-plugins-base`, however, did not mention `opus` in the output of `./configure` so I did not notice that I was missing anything.

**Comment by maxmcd** [comment]
@SUlbrichA If you would like a reference this is a working debian build with necessary dependencies: https://github.com/maxmcd/gstreamer-docker/blob/master/1.14/buster/Dockerfile

**Comment by SUlbrichA** [comment]
@maxmcd Awesome thank you that definitively helps cleaning up my setup!
