### ISSUE TITLE
Detect Peer Connection Loss

### ISSUE THREAD

**Issue by meldron** [centricular/gstwebrtc-demos#35]
Hey guys,

what is the best way to detect if the peer connection has been lost? 

Currently I am thinking about polling the `webrtcbin` property `conection-state`. Anybody with a better idea?

Thanks!

**Comment by ystreet** [comment]
You can attach a notify signal with a callback on all the `*state` properties instead of polling but yes, that is probably the best option.  The callback will happen in a different thread than any your application owns so synchronisation would be required.

**Comment by ystreet** [comment]
E.g. example in C
```C
static void
on_state_notify (gpointer webrtcbin, GParamSpec * pspec, gpointer user_data)
{
  /* do things */
}

// on setup
g_signal_connect (webrtcbin, "notify::connection-state", G_CALLBACK(on_state_notify), some_user_data);
```

**Comment by meldron** [comment]
Thanks @ystreet for your info and the example!

My polling approach of the webrtc element properties did not result in changing states (`connection-state` and `ice-connection-state` always remained the initial state), so I guess i have to try the signal approach.

But may be my polling approach is wrong? I tried:

```rust
    thread::spawn(move || {
        let one_sec = time::Duration::from_millis(1000);

        loop {
            let mut state = None;
            {
                let mut lock = app_control_polling.0.lock().unwrap();
                let mut webrtc = lock.pipeline.get_by_name("sendrecv");
                
                webrtc = match webrtc {
                    Some(w) => {
                        match w.get_property("connection-state") {
                            Ok(r) => { 
                                state = Some(r.clone());
                                },
                            Err(_) => {  }
                        };
                        Some(w)
                    }
                    None => None,
                };

                lock.webrtc = webrtc;
            }

            match state {
                Some(s) => {
                    println!("{:?}", s);
                }
                None => {}
            }

            thread::sleep(one_sec);
        }
    });
```

**Comment by ystreet** [comment]
Hrm, `connection-state` isn't quite hooked up correctly yet.  The DTLS implementation currently doesn't notify us about connection state changes.

I thought `ice-connection-state` was hooked up though.

That rust code looks fine

**Comment by meldron** [comment]
Hey I just checked the `ice-connection-state` again and I found my mistake:

So at first it is `GST_WEBRTC_ICE_CONNECTION_STATE_NEW` and then it is changed to `GST_WEBRTC_ICE_CONNECTION_STATE_CONNECTED`. But if I disconnect with the browser the `ice-connection-state` remains `GST_WEBRTC_ICE_CONNECTION_STATE_CONNECTED`. Is this intended behavior? I thought it should be `GST_WEBRTC_ICE_CONNECTION_STATE_DISCONNECTED` after the peer disconnects.

Sorry for the misinformation!

**Comment by ystreet** [comment]
That would indicate that libnice doesn't tell us that the connection is not valid anymore and is a fun debugging job.

**Comment by givip** [comment]
Why did you close this topic? This problem remains in GStreamer 1.16.1

**Comment by Xaeroxe** [comment]
I concur, this shouldn't be closed. This issue presents a pretty nasty problem for using GstWebRtc in production code.

**Comment by ystreet** [comment]
This is not an issue in these examples but in webrtcbin itself or with libnice.  Issues for those components are tracked at https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad and https://gitlab.freedesktop.org/libnice/libnice respectively.

**Comment by Xaeroxe** [comment]
Here's the relevant issue: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/758

Thanks @ystreet !
