### ISSUE TITLE
Namespace GstWebRTC is not available

### ISSUE THREAD

**Issue by ashwindharne** [centricular/gstwebrtc-demos#37]
Hey! I've been trying to run your examples for a while and for some reason, regardless of what configuration I build Gstreamer in I keep getting the error:
ValueError: Namespace GstWebRTC not available
I'm on Ubuntu 18.04, and have tried installing with both the 1.14 branch of gst-build and the master branch, but neither seems to work in this regard. Should I be installing gst-python, or relying on the regular introspection? Does introspection have to be disabled while building? 

Thanks!

**Comment by lpasarel** [comment]
Hi

There was a similar issue (#26) when installing on MacOS and it was related to missing `GstWebRTC-1.0.typelib`
The resolution was to `--enable-introspection` when building `gst-plugins-bad`

Have a look at #26, it may help you.

**Comment by ashwindharne** [comment]
Thanks! A variation of that worked for me.

**Comment by petedaws** [comment]
I am having the same issue also on 18.04, however I am still getting: 
`ValueError: Namespace GstWebRTC not available`

I have tried building gst-plugins-bad 1.14.2 with introspection enabled without success:
`gst-plugins-bad$ ./autogen.sh --enable-introspection`

**Comment by maxmcd** [comment]
If it's helpful, here are working debian build steps: https://github.com/maxmcd/gstreamer-docker/blob/master/1.14/buster/Dockerfile

**Comment by ashwindharne** [comment]
I copied the .typelib file for GstWebRTC into the girepository folder. I found the typelib file in the build folder of gst-build. The client I’m writing is still not working so I’m not sure if this works or not, but the error went away.

**Comment by petedaws** [comment]
Yep thanks @ashwindharne. Copying to the typelib file worked for me. 
To make this explicit for others (and for future me) I did the following:

```
~$ git clone https://github.com/GStreamer/gst-plugins-bad.git
gst-plugins-bad$ git checkout 1.14.2
gst-plugins-bad$ ./autogen.sh --enable-introspection
gst-plugins-bad$ make
gst-plugins-bad$ sudo make install
gst-plugins-bad$ sudo cp ./gst-libs/gst/webrtc/GstWebRTC-1.0.typelib /usr/lib/girepository-1.0/
```
I then ran:
`gstwebrtc-demos/sendrecv/gst$ python3 webrtc-sendrecv.py <peerid>`

Which shows the bouncing ball when you go to: [https://webrtc.nirbheek.in/](https://webrtc.nirbheek.in/) and replace `<peerid>` with the peerid reported on the page.

#Update: Now I understand why @maxmcd uses `--prefix=/usr` in [https://github.com/maxmcd/gstreamer-docker](https://github.com/maxmcd/gstreamer-docker). 
If you run `gst-plugins-bad$ ./autogen.sh --prefix=/usr --enable-introspection` you don't need the extra copy step. Better to go this way.

**Comment by ystreet** [comment]
`ValueError: Namespace GstWebRTC` and building things manually probably means you need to augment the `GI_TYPELIB_PATH` environment variable to point to the correct place.  You can also setup an uninstalled environment which will take care this automatically.

**Comment by edholland** [comment]
In ubuntu the typelib file is in package `gir1.2-gst-plugins-bad-1.0`

**Comment by tobiasfriden** [comment]
> If it's helpful, here are working debian build steps: https://github.com/maxmcd/gstreamer-docker/blob/master/1.14/buster/Dockerfile

@maxmcd I am trying to run the demo using this dockerfile:
```docker
FROM maxmcd/gstreamer:1.14-buster

WORKDIR /usr/src

RUN apt-get install -y python3-pip pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev

COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["/usr/bin/python3", "./client.py"]
```
However, getting `ValueError: Namespace Gst not available`. Any idea how to resolve this issue? Thanks!

EDIT:
Managed to get the python demo working with the following setup:
https://gist.github.com/tobiasfriden/3359c9a125c726d9c134359507d3450a
Note that I hade to edit the demo code as discussed in #45

**Comment by sampleref** [comment]
> Yep thanks @ashwindharne. Copying to the typelib file worked for me.
> To make this explicit for others (and for future me) I did the following:
> 
> ```
> ~$ git clone https://github.com/GStreamer/gst-plugins-bad.git
> gst-plugins-bad$ git checkout 1.14.2
> gst-plugins-bad$ ./autogen.sh --enable-introspection
> gst-plugins-bad$ make
> gst-plugins-bad$ sudo make install
> gst-plugins-bad$ sudo cp ./gst-libs/gst/webrtc/GstWebRTC-1.0.typelib /usr/lib/girepository-1.0/
> ```
> I then ran:
> `gstwebrtc-demos/sendrecv/gst$ python3 webrtc-sendrecv.py <peerid>`
> 
> Which shows the bouncing ball when you go to: https://webrtc.nirbheek.in/ and replace `<peerid>` with the peerid reported on the page.
> 
> #Update: Now I understand why @maxmcd uses `--prefix=/usr` in https://github.com/maxmcd/gstreamer-docker.
> If you run `gst-plugins-bad$ ./autogen.sh --prefix=/usr --enable-introspection` you don't need the extra copy step. Better to go this way.

This helped! Thanks

**Comment by saket424** [comment]
I tried a fresh copy of Debian buster x86_64 yesterday. After installing stock gstreamer-plugins-bad-1.0 (1.14.4) via apt-get, even though gst-inspect-1.0 lists webrtc as a supported element, the module is not compiled with --enable-introspection.

When can we expect stock buster to support gstwebrtc-sendrecv python sample without having to modify and compile our own copy of gstreamer-plugins-bad-1.0 to explicitly enable introspection?

**Comment by ystreet** [comment]
> When can we expect stock buster to support gstwebrtc-sendrecv python sample without having to modify and compile our own copy of gstreamer-plugins-bad-1.0 to explicitly enable introspection?

You need to ask the debian maintainers that question :)

**Comment by wmanley** [comment]
> When can we expect stock buster to support gstwebrtc-sendrecv python sample without having to modify and compile our own copy of gstreamer-plugins-bad-1.0 to explicitly enable introspection?

AFAICS it already does.  The package is [gir1.2-gst-plugins-bad-1.0](https://packages.debian.org/search?keywords=gir1.2-gst-plugins-bad-1.0&searchon=names&suite=all&section=all) in Debian too.

**Comment by saket424** [comment]
@wmanley 

I just now installed stock ubuntu19.10 which has gstreamer 1.16.1. At first, the webrtcbin plugins were not there even though gstreamer1.0-plugins-bad was

After I installed

sudo apt-get install -y python3-pip pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev python-gst-1.0 gir1.2-gst-plugins-bad-1.0 gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-nice

voila

gst-inspect-1.0 | egrep "webrtc|dtls|nice|dtls"
webrtc:  webrtcbin: WebRTC Bin
dtls:  dtlsenc: DTLS Encoder
dtls:  dtlsdec: DTLS Decoder
dtls:  dtlssrtpdec: DTLS-SRTP Decoder
dtls:  dtlssrtpenc: DTLS-SRTP Encoder
dtls:  dtlssrtpdemux: DTLS SRTP Demultiplexer
nice:  nicesink: ICE sink
nice:  nicesrc: ICE source


pip3 install websockets attrs

and the gstwebrtc-demo worked without my having to do any cerbero compilation

Thanks again!
