### ISSUE TITLE
audio error in sendrecv example

### ISSUE THREAD

**Issue by yjjnls** [centricular/gstwebrtc-demos#38]
>** (webrtc-sendrecv:6515): CRITICAL **: file gstaudioringbuffer.c: line 2044 (gst_audio_ring_buffer_set_channel_positions): should not be reached

I got this error  recently and received no audio from web, video is ok. 

why does this happen?

**Comment by yjjnls** [comment]
I ran it on Ubuntu 16.04, web browser is chrome(latest version) and the audio format is PCMA. I received audio data form chrome but it plays no sound and raise the error above.

**Comment by ystreet** [comment]
Receiving PCMA means you've changed the program to not use opus.  We can't help you with that without at least seeing what you've changed.

Also, some useful information like OS/Platform or where you're trying to run this program would be useful to know which audio sink you're using :)
