### ISSUE TITLE
Datachannels

### ISSUE THREAD

**Issue by petergerten** [centricular/gstwebrtc-demos#4]
Hi,

are there any plans for Datachannel support?

Peter

**Comment by sdroege** [comment]
It's on the TODO list but no ETA or concrete plans yet. Better to be reported at https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer&component=gst-plugins-bad

Could be based on this plugin: https://github.com/EricssonResearch/openwebrtc-gst-plugins/tree/master/ext/sctp
However the underlying library is an API nightmare and makes embedding in frameworks very difficult.

**Comment by odinho** [comment]
For anyone looking, the real bug is here:

https://bugzilla.gnome.org/show_bug.cgi?id=794351

No movement yet.
