### ISSUE TITLE
Python demo stops working after few seconds

### ISSUE THREAD

**Issue by mohammadbhuyan** [centricular/gstwebrtc-demos#45]
What I have:

I have Ubuntu 18.04 on VirtualBox (Mac)

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
```

I have built GStreamer 1.1.4.2 using the sources obtained from:
https://gstreamer.freedesktop.org/news/

```
$ gst-inspect-1.0 --version
gst-inspect-1.0 version 1.14.2
GStreamer 1.14.2
Unknown package origin
```

More details of my setup can be found in #42 

I am using https://webrtc.nirbheek.in/ for signalling.

Once I start the python demo, I see the bouncing ball video appear in my browser but then it freezes after a few seconds. By that time the python end has an assertion error in console:

```
Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 75, in on_incoming_decodebin_stream
    assert (len(caps))
TypeError: object of type 'Caps' has no len()
Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 75, in on_incoming_decodebin_stream
    assert (len(caps))
TypeError: object of type 'Caps' has no len()
```
Screenshot attached.

![webrtcprogress](https://user-images.githubusercontent.com/23430389/45262325-536b0380-b447-11e8-9f53-740da84c85f3.jpg)

Any suggestion regarding what to investigate?

**Comment by notedit** [comment]
change  these lines  
```
        caps = pad.get_current_caps()
        assert (len(caps))
        s = caps[0]
        name = s.get_name()

```

to  

```


        caps = pad.get_current_caps()
        name = caps.to_string()

```

**Comment by mohammadbhuyan** [comment]
@notedit Again, much appreciate your prompt response.

Unfortunately, I got progress but hit another roadblock. After applying your fix, the demo now runs for a little longer but freezes after this:

```
Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 83, in on_incoming_decodebin_stream
    self.pipe.add(q, conv, sink)
TypeError: Gst.Bin.add() takes exactly 2 arguments (4 given)
Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 93, in on_incoming_decodebin_stream
    self.pipe.add(q, conv, resample, sink)
TypeError: Gst.Bin.add() takes exactly 2 arguments (5 given)
```

There seems to me like API changes. I am confident that I have the necessary programming skills to adapt the code to new API if I am pointed to documentation or example materials so that I can have a better understanding of GStreamer/Python API.

Do you have any pointer for me? Or better yet, any python codebase that is using the latest state of GStreamer webrtc pipeline?

Thanks.

**Comment by notedit** [comment]
you can see my wrapper   here  https://github.com/RTCEngine/rtc-mcu

**Comment by mohammadbhuyan** [comment]
@notedit Awesome! I have got the demo running with the help of your code.

**Comment by petrosagg** [comment]
@mohammadbhuyan It'd be great if you also PRed the changes

**Comment by mpottinger** [comment]
> @notedit Again, much appreciate your prompt response.
> 
> Unfortunately, I got progress but hit another roadblock. After applying your fix, the demo now runs for a little longer but freezes after this:
> 
> ```
> Traceback (most recent call last):
>   File "webrtc-sendrecv.py", line 83, in on_incoming_decodebin_stream
>     self.pipe.add(q, conv, sink)
> TypeError: Gst.Bin.add() takes exactly 2 arguments (4 given)
> Traceback (most recent call last):
>   File "webrtc-sendrecv.py", line 93, in on_incoming_decodebin_stream
>     self.pipe.add(q, conv, resample, sink)
> TypeError: Gst.Bin.add() takes exactly 2 arguments (5 given)
> ```
> There seems to me like API changes. I am confident that I have the necessary programming skills to adapt the code to new API if I am pointed to documentation or example materials so that I can have a better understanding of GStreamer/Python API.
> 
> Do you have any pointer for me? Or better yet, any python codebase that is using the latest state of GStreamer webrtc pipeline?
> 
> Thanks.

Just so others who are searching can see the solution to this more clearly. The syntax does appear to have changed (annoying, but oh well, we deal with this all the time) I changed all the self.pipe.add() lines from passing multiple results of Gst.ElementFactory.make() at one time, to just passing one at a time

example change the single line:

self.pipe.add(q, conv, sink) 

to multiple lines:

self.pipe.add(q)
self.pipe.add(conv)
self.pipe.add(sink)

then it worked perfectly!

Arrrghh such an annoying part of programming in Python especially, this always happens. Oh well, at least the solution was easy enough to find!
