### ISSUE TITLE
Strange problem after replace videotestsrc to v4l2src (white screen at second time)

### ISSUE THREAD

**Issue by dukelec** [centricular/gstwebrtc-demos#46]
I have modified the demo to one-way video streaming, so, one camera is enough for test when web browser and webrtc-sendrecv.py run on same computer.
I also test without change the demo, attach one more camera to the computer, and use "v4l2src device=/dev/video1" instead, and got the same problem.

After use "v4l2src" instead, I can watch camera video in the browser only at first one or two times, after that, everything is fine except the video become while screen. (use videotestsrc is always fine)

This problem only exist for Chrome (Firefox is fine), after I upgrade my Chrome to "Version 69.0.3497.92 (Official Build) (64-bit)", I can watch my camera video again, but only at first time. I try to test it in an incognito page, only got successed at first time. Reopen incognito page or reopen the Chrome or reboot my computer doesn't help.

In Chrome WebRTC debug page, I found that, when the video is while screen, there are two ssrc_xxxxxx_recv, the framesDecoded of one ssrc is always zero, another one is normal. Why this happen?

![screenshot_2018-09-17_18-34-21](https://user-images.githubusercontent.com/4454365/45620500-bbf15a80-baaf-11e8-8b5f-9cbbdc250f98.png)

**Comment by ystreet** [comment]
Which direction are you streaming? browser -> gst or gst -> browser? I assume gst is still creating the offer.

If you use the second camera, is there any debug output if you have GST_DEBUG=3 in the environment when running the gst sample.  Are there any criticals/warnings printed?

**Comment by dukelec** [comment]
The direction is: gst -> browser, this is my code: https://github.com/dukelec/gstwebrtc-demos  
(the commented pipeline descript on top of python script is the camera version.)

Logs with `GST_DEBUG=3` :
[camera_and_browser_on_same_machine (not ok).log](https://github.com/centricular/gstwebrtc-demos/files/2454236/camera_and_browser_on_same_machine.not.ok.log)
[stream_camera_to_android_chrome (ok).log](https://github.com/centricular/gstwebrtc-demos/files/2454237/stream_camera_to_android_chrome.ok.log)
[test_video_and_browser_on_same_machine (ok).log](https://github.com/centricular/gstwebrtc-demos/files/2454238/test_video_and_browser_on_same_machine.ok.log)

**Comment by aniketor** [comment]
I have encountered this same issue. Im streaming as gst -> webbrowser. The page could not load the video even if my pipeline is running. However if i decode v4l2src from h264 and re-encode to VP8 it is working. Maybe the issue is with h264 parsing.

**Comment by ystreet** [comment]
There are a number of things that one needs to get right for h.264 to work correctly.  Only a subset of h.264 will ever be supported by the browsers and the sender needs to limit itself to that subset.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
