### ISSUE TITLE
Video recv fails on Windows with not-linked in nicesrc

### ISSUE THREAD

**Issue by nirbheek** [centricular/gstwebrtc-demos#5]
For some reason, the video stream we receive from the browser outputs one frame to the video sink, but the [link itself](https://github.com/centricular/gstwebrtc-demos/blob/3cd6478c5c1bdecf46eaad5d0a26eaae0e02a538/sendrecv/gst/webrtc-sendrecv.c#L126) fails with `GST_PAD_LINK_NOFORMAT`, which leads to a not-linked in nicesrc.

I've attached the [`GST_DEBUG=3,*webrtc*:6,*nice*:6` log](https://github.com/centricular/gstwebrtc-demos/files/1793571/out.log), with the pad link assert commented out.

I can't really figure out what's going on :)

**Comment by ystreet** [comment]
Erm. I have no idea why that would fail linking on Windows but not on Linux.

You also need to add the `*PAD*:6` category for link errors.

**Comment by SKilb** [comment]
For me both links fail, the video stream and the audio stream.
I tested it by skipping the assert when it's a video stream.
