### ISSUE TITLE
Does not seems to work over cellular network

### ISSUE THREAD

**Issue by imdark** [centricular/gstwebrtc-demos#52]
if the gst-js is opened in a browser and gst are on machines on the same network it works fine otherwise when gst-js is opened over the internet they do not seem to pair

**Comment by ystreet** [comment]
gstwebrtc does work over internet links.  Could you be more specific in your setup?  Where is your signalling server? Do the two machines share a network subnet at all? How are you accessing the web page?  With a web server or served from a file?  Does the web page have access to the internet for the webrtc adapter.js ?  Are gst and the browser accessing the same signalling server ? Do you get any logs in the signalling server you may be running when attempting a connection ?

**Comment by imdark** [comment]
I have it setup using a 4g internet on the gst side and I use https://webrtc.nirbheek.in as my web client and the default server, and open the link in chrome, I will provide some logs

**Comment by rtcnerd** [comment]
I have been trying to connect from my mobile on 4G to my PC. It does not seem to work. I am using the JS from Nirbheek on my server. The TURN server has been added which is numb.viagenie.ca on both the java code (PC) and the JS on mobile. It works on local network but not when the mobile is on 4G. Please see the logs below.


[AsyncHttpClient-3-1] INFO WebrtcSendRecv - websocket onOpen
[gstreamer service thread 1] INFO WebrtcSendRecv - Pipe state changed from NULL to new READY
[gstreamer service thread 1] INFO WebrtcSendRecv - Pipe state changed from READY to new PAUSED
[GCallback] INFO WebrtcSendRecv - onNegotiationNeeded: sendrecv
[gstreamer service thread 1] INFO WebrtcSendRecv - Pipe state changed from PAUSED to new PLAYING
[GCallback] INFO WebrtcSendRecv - Sending offer:
{"sdp":{"type":"offer","sdp":"v=0\r\no=- 4580197353156026988 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:spGjH67qbyuQxyBKO7t+N68GRwbwF1pX\r\na=ice-pwd:k3fzOK5HJh/sMszAkN4XIWkgWAkNylRV\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 OPUS/48000/2\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 sprop-maxcapturerate=48000;sprop-stereo=0\r\na=ssrc:4209926198 msid:user3501531524@host-987954e2 webrtctransceiver1\r\na=ssrc:4209926198 cname:user3501531524@host-987954e2\r\na=mid:audio0\r\na=fingerprint:sha-256 E9:5B:5E:F4:91:DC:97:2E:B6:E6:03:67:96:96:7B:A2:85:2E:E2:CC:3F:BC:C1:C5:8F:76:4B:FB:1C:D8:A4:46\r\n"}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:1 1 UDP 2013266431 fe80::a041:592d:e848:d218 64600 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:2 1 TCP 1015023871 fe80::a041:592d:e848:d218 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:3 1 TCP 1010829567 fe80::a041:592d:e848:d218 54493 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:4 1 UDP 2013266430 fe80::8408:95ff:fe27:6f37 64601 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:5 1 TCP 1015023870 fe80::8408:95ff:fe27:6f37 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:6 1 TCP 1010829566 fe80::8408:95ff:fe27:6f37 54494 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:7 1 UDP 2013266429 2001:1c05:1700:8800:3f49:4189:5d:5355 64602 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:8 1 TCP 1015022335 2001:1c05:1700:8800:3f49:4189:5d:5355 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:9 1 TCP 1010828031 2001:1c05:1700:8800:3f49:4189:5d:5355 54495 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:10 1 UDP 2013266428 192.168.178.33 52893 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:11 1 TCP 1015022591 192.168.178.33 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:12 1 TCP 1010828287 192.168.178.33 54496 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:13 1 UDP 2013266427 fe80::1024:76c0:a23a:fdfd 52894 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:14 1 TCP 1015023869 fe80::1024:76c0:a23a:fdfd 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:15 1 TCP 1010829565 fe80::1024:76c0:a23a:fdfd 54497 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:1 2 UDP 2013266430 fe80::a041:592d:e848:d218 52895 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:2 2 TCP 1015023870 fe80::a041:592d:e848:d218 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:3 2 TCP 1010829566 fe80::a041:592d:e848:d218 54498 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:4 2 UDP 2013266429 fe80::8408:95ff:fe27:6f37 52896 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:5 2 TCP 1015023869 fe80::8408:95ff:fe27:6f37 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:6 2 TCP 1010829565 fe80::8408:95ff:fe27:6f37 54499 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:7 2 UDP 2013266428 2001:1c05:1700:8800:3f49:4189:5d:5355 52897 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:8 2 TCP 1015022334 2001:1c05:1700:8800:3f49:4189:5d:5355 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:9 2 TCP 1010828030 2001:1c05:1700:8800:3f49:4189:5d:5355 54500 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:10 2 UDP 2013266427 192.168.178.33 49580 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:11 2 TCP 1015022590 192.168.178.33 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:12 2 TCP 1010828286 192.168.178.33 54501 typ host tcptype passive","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:13 2 UDP 2013266426 fe80::1024:76c0:a23a:fdfd 49581 typ host","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:14 2 TCP 1015023868 fe80::1024:76c0:a23a:fdfd 9 typ host tcptype active","sdpMLineIndex":0}}
[GCallback] INFO WebrtcSendRecv - ON_ICE_CANDIDATE: {"ice":{"candidate":"candidate:15 2 TCP 1010829564 fe80::1024:76c0:a23a:fdfd 54502 typ host tcptype passive","sdpMLineIndex":0}}
[AsyncHttpClient-3-1] INFO WebrtcSendRecv - answer SDP:
v=0
o=- 1627615650638887674 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS pHPA1JOARSv7Mlz93ou0ttwphb3F9cqDsKF3
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:vOaE
a=ice-pwd:qAgD097i2ksNXOAtvisCceoj
a=ice-options:trickle
a=fingerprint:sha-256 CD:9D:1D:9C:E2:FF:89:C6:E7:38:44:5F:72:B3:91:68:2A:2D:55:8C:0E:29:B6:88:A7:90:5C:8C:20:C4:27:38
a=setup:active
a=mid:audio0
a=sendrecv
a=rtcp-mux
a=rtpmap:96 OPUS/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=ssrc:150807825 cname:TEXgtxep+erIaCJv
a=ssrc:150807825 msid:pHPA1JOARSv7Mlz93ou0ttwphb3F9cqDsKF3 03fabdda-ed79-42e0-9781-ea0ccfb97217
a=ssrc:150807825 mslabel:pHPA1JOARSv7Mlz93ou0ttwphb3F9cqDsKF3
a=ssrc:150807825 label:03fabdda-ed79-42e0-9781-ea0ccfb97217

[AsyncHttpClient-3-1] INFO WebrtcSendRecv - Adding ICE candidate: candidate:1890559624 1 udp 2122260223 10.217.183.138 40018 typ host generation 0 ufrag vOaE network-id 1 network-cost 900
[AsyncHttpClient-3-1] INFO WebrtcSendRecv - Adding ICE candidate: candidate:1043094136 1 tcp 1518280447 10.217.183.138 9 typ host tcptype active generation 0 ufrag vOaE network-id 1 network-cost 900
[AsyncHttpClient-3-1] INFO WebrtcSendRecv - Adding ICE candidate: candidate:3156384027 1 udp 1686052607 148.252.129.204 64062 typ srflx raddr 10.217.183.138 rport 40018 generation 0 ufrag vOaE network-id 1 network-cost 900
[AsyncHttpClient-3-1] INFO WebrtcSendRecv - Adding ICE candidate: candidate:453802058 1 udp 41885439 158.69.221.198 55633 typ relay raddr 148.252.129.204 rport 64062 generation 0 ufrag vOaE network-id 1 network-cost 900

**Comment by ystreet** [comment]
Has the turn server been added on both peers?  If you're using webrtc.nirbheek.in, then that does not configure the use of a TURN server.
