### ISSUE TITLE
Safari?

### ISSUE THREAD

**Issue by peebles** [centricular/gstwebrtc-demos#57]
This seems hardcoded to use VP8.  Shouldn't the negotiation phase pick the right video codec based on what the browser wants?  I mean, isn't this the whole purpose of webrtc?

**Comment by degtyaryov** [comment]
I also do not quite understand how to implement it.

If the offer creates a browser, then you can determine which codecs the browser supports and build the pipeline with need codec.

How to create an offer in which all VP8, VP9, H264, H265 codecs will be listed and then launch the required pipeline according to the answer?

**Comment by ystreet** [comment]
Currently there's no easy way to signal this through webrtcbin.  You might be able to do something with manually performing 'add-transceiever' for each stream however you're delving into untested webrtcbin code :).

webrtcbin currently is mostly concerned with getting the data to and from the peer.  The contents of that data and it's encoding is currently out-of scope.

All that being said, webrtcbin does talk with Safari fine when fed with a compatible H.264 stream.
