### ISSUE TITLE
In which gstreamer version can I find the bundle-policy property of Webrtcbin?

### ISSUE THREAD

**Issue by aswathisivan** [centricular/gstwebrtc-demos#62]
In the latest webrtc-sendrecv.c, I see the bundle-policy being added to the pipeline. In which version of gstreamer I could get this support? I have tried till 1.14.4 but it doesn't look like it has been added. When I tried building from master branch I get errors in gst-uninstalled. Any suggestions to get the bundle policy patch applied?

**Comment by alexlapa** [comment]
@aswathisivan ,

Bundle works on master.

**Comment by ystreet** [comment]
Please use the GStreamer mailing list or IRC for support questions.

Bundle is in GStreamer >1.16
