### ISSUE TITLE
Getting "_get_final_direction: code should not be reached " error in versions  >1.14.1

### ISSUE THREAD

**Issue by aswathisivan** [centricular/gstwebrtc-demos#65]
I am using the below pipeline to stream the video to a web chrome browser. 

-  **_gst_parse_launch ("webrtcbin bundle-policy=max-bundle name=sendrecv " STUN_SERVER
      " rtspsrc location=rtsp://<ipcamera_url_info_here> !  queue ! application/x-rtp, media=video, encoding-name=H264, payload=96 ! sendrecv.  ",
      &error);_**

The video used to stream with 1.14.1 version. But in version 1.14.2 and 1.15.0 I am getting the below errors:

- **_0:00:15.475758027 32474 0x7f087c073590 ERROR         dtlsconnection gstdtlsconnection.c:727:ssl_err_cb:<GstDtlsConnection@0x7f087c005590> ssl error: 139674417313168:error:140B4090:SSL routines:SSL_do_handshake:connection type not set:ssl_lib.c:2779:_**

- _**0:00:15.476559073 32474      0x1863400 ERROR                default webrtcsdp.c:380:_get_direction_from_media: Multiple direction attributes**_
 **_ERROR:webrtcsdp.c:493:_get_final_direction: code should not be reached_**
**_Aborted (core dumped)_**

I am adding the Offer and answer below for reference. Anyone have idea about what has been changed in the later versions due to which the sig_abort is happening?

```
Sending offer:
v=0
o=- 7690451568308751661 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:vbCMdyTJVZSepXT6mqDUL3NcG9gRGM2e
a=ice-pwd:hNt5nrHBIM5k64hk0I+8auyt2CqwSCqi
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=packetization-supported:DH
a=rtppayload-supported:DH
a=framerate:10.000000
a=recvonly
a=fmtp:96 packetization-mode=1;profile-level-id=428029;sprop-parameter-sets=Z0KAKZpkA8ARPy4C3AQEBQAAAwPoAABOIOhgDQwANDC7y40MAaGABoYXeXCg,aM48gA==
a=ssrc:588744535 msid:user784747222@host-3812aea4 webrtctransceiver0
a=ssrc:588744535 cname:user784747222@host-3812aea4
a=mid:video0
a=fingerprint:sha-256 19:37:42:9E:0E:36:84:79:6C:A2:50:63:29:25:2E:8E:32:9D:68:23:60:9F:B5:3A:3E:43:B2:AF:9B:56:DC:1E
```

```
Received answer:
v=0
o=- 4087386550310822300 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MKIk
a=ice-pwd:AEhz5dDhQL2GeY9lyVrIj2O9
a=ice-options:trickle
a=fingerprint:sha-256 DE:3A:B5:09:C2:AE:0F:20:E9:16:25:3D:34:E6:64:79:3A:8C:8E:50:1F:2A:72:0B:1A:CB:55:B7:53:FE:54:A2
a=setup:active
a=mid:video0
a=inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
```

**Comment by ystreet** [comment]
Your offer has both an `a=sendrecv` and an `a=recvonly` attribute which is invalid SDP and would result in such an error.  I'm curious as to how you get that state.

**Comment by aswathisivan** [comment]
Ya that's right. But I am not sure why an incorrect SDP is getting generated with latest versions. I suspect the `a=inactive` in the answer is due to the incorrect SDP offer. 

In version 1.14.1 only `a=sendrecv` used to go in offer. I am adding the SDP answer/offer (for reference) which used to go in version 1.14.1.

```
Sending offer:
v=0
o=- 88621682472756419 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:34JK+qtjYFohYNNe//mVNl1Bct6HYfxd
a=ice-pwd:yMKoRmHcZvCHZgNlZh1BRHgD7ZLBzD0h
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/1959849984
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=mid:video0
a=fingerprint:sha-256 95:77:09:B2:B3:ED:AD:65:C1:79:6B:21:C3:81:AC:25:EB:02:3C:52:F3:F7:01:DD:88:9D:AC:76:E9:48:A8:28
```

```
Received answer:
v=0
o=- 614707326112457058 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:stfR
a=ice-pwd:ho36492KQhBhQAn5/FuC92xu
a=ice-options:trickle
a=fingerprint:sha-256 97:43:53:30:D8:85:FF:76:E1:4C:20:10:8C:D0:1D:C0:BB:3D:EA:9F:93:E7:81:46:6F:30:B2:93:D0:55:14:83
a=setup:active
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
```

**Comment by Dreamlol** [comment]
Same problem with ip camera, version 1.14.4

**Comment by saket424** [comment]
I just tried an ip camera with cerbero gstreamer webrtcbin 1.15.1 streaming to janus videoroom and it works fine

**Comment by ystreet** [comment]
This is most likely a result of the caps being provided on the sink pad.
