### ISSUE TITLE
Remote Offer with multiple Video Codecs, how to set preference for a Codec ?

### ISSUE THREAD

**Issue by rosimildo** [centricular/gstwebrtc-demos#67]
When I remote peer set several codecs in an Offer, how to make the answer to pick a particular codec ?
It seems the "create-answer" signal has an "options" parameter, but it is not documented how to use it.

Any hints where to look ?

Thanks!

**Comment by rosimildo** [comment]
Looking at the sources, it seems the implementation still not complete:
https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/webrtc/gstwebrtcbin.c#L2474

**Comment by ystreet** [comment]
The webrtcbin answer will choose the format that's configured on the associated sink pad or through the codec_preferences on the transceiver created using the 'add-transceiver' signal.

**Comment by rosimildo** [comment]
Interesting, I did not think about that!

EDIT: the approach I has written here, did not work.

The suggestion to add a transceiver with a preferred codec, works!

This is done during the setup of the pipeline!!!!
The code is more or less like this:

// H264 Codec
   GstCaps *caps = gst_caps_new_simple ("application/x-rtp",
                                                            "media", G_TYPE_STRING, "video",
                                                            "encoding-name", G_TYPE_STRING, "H264",
                                                            "clock-rate", G_TYPE_INT, 90000, NULL);
    GstWebRTCRTPTransceiver *trans = NULL;
    g_signal_emit_by_name( webrtcbin, "add-transceiver", GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY, caps, &trans );
    gst_caps_unref( caps );
    if( trans != NULL ) {
         gst_object_unref (trans);
    }
