### ISSUE TITLE
How does on-negotiation-needed work?

### ISSUE THREAD

**Issue by kevkid** [centricular/gstwebrtc-demos#73]
Looking at this code:
```
 def start_pipeline(self):
        self.pipe = Gst.parse_launch(PIPELINE_DESC)
        self.webrtc = self.pipe.get_by_name('sendrecv')
        **self.webrtc.connect('on-negotiation-needed', self.on_negotiation_needed)**
        self.webrtc.connect('on-ice-candidate', self.send_ice_candidate_message)
        self.webrtc.connect('pad-added', self.on_incoming_stream)
        self.pipe.set_state(Gst.State.PLAYING)

```
How does the webrtc pipeline get any information about its peers?
I see that it has the on_negotiation_needed callback but its unclear where the element variable comes from? I looked here: http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html and I am still confused as to how this negotiation works? From what I understand there are 2 (or more) peers and both of them must connect to the signaling server, then one of them has to create an offer.

This is what I assume what the on_negotiation_needed callback does?

**Comment by ystreet** [comment]
It works the same as described in the W3C specification: https://www.w3.org/TR/webrtc/

**Comment by kevkid** [comment]
@ystreet thanks
