### ISSUE TITLE
signalling/simple-server.py says it's listening on https on line 265

### ISSUE THREAD

**Issue by towc** [centricular/gstwebrtc-demos#75]
https://github.com/centricular/gstwebrtc-demos/blob/master/signalling/simple-server.py#L265

Is this correct? I've been trying to debug something else, and when I noticed that it said it was listening through https I was pretty shocked, and was left wondering if I misunderstood something.

Unless I have, can this be changed to wss, so the next poor soul doesn't get the same doubts?

**Comment by ystreet** [comment]
wss is a protocol upgrade from https.  In order to bypass browser security limitations when running with subpar ssl certificates, one needs to visit the https location.

**Comment by towc** [comment]
The way I understand it, one needs to make the wss connection from another page loaded with https in order for the security checks to pass, and that's how it would normally be used.

How wss is built on top of https is an unnecessary detail for the user, who again, might think that there's something missing, as they'd expect the more reasonable `listening on wss://...`

I feel like it wouldn't make sense for http servers to say `listening on tcp at ...`, either
