### ISSUE TITLE
Examples with different codecs

### ISSUE THREAD

**Issue by riccardocagnasso** [centricular/gstwebrtc-demos#77]
Could you please please please provide some examples with using different codec / encoders?

I managed to use vaapivp8enc instead of vp8enc. It works fine despite of not having a "deadline" option, and this is great for obvious reasons. But it would be nice to be able to use other codecs. AFAIK h264 should be supported by chrome at the very least.

**Comment by kevkid** [comment]
@riccardocagnasso 

I was able to get this to kinda work:

```
PIPELINE_DESC = '''
webrtcbin name=sendrecv bundle-policy=max-bundle
 videotestsrc ! x264enc ! h264parse ! rtph264pay ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! sendrecv.
'''
#this works videotestsrc h264enc on firefox, chrome gives artifacts
```

It is unclear to me why chrome gives lots of artifacts? actually trying this seems to send a keyframe every few seconds on Chrome. FF works fine, but has a delay. I also tried this on the same machine giving much better results, and no artifacts. Can the devs chime in as to what we can do to alleviate this? Do we have to send keyframes? if so how?

**Comment by ystreet** [comment]
You probably want to reduce the h264 profile to constrained baseline and you also need to get the H.264 level correct otherwise the profile-level-id in the SDP will cause chrome/firefox to barf.

We're not going to add other examples anytime soon.  If you'd like to, please submit an PR.
