### ISSUE TITLE
gstreamer does not intiate DTLS handshake

### ISSUE THREAD

**Issue by petergerten** [centricular/gstwebrtc-demos#78]
Hi, I am trying to connect to 'janus gateway'. Janus provided an offer with candidates and the gstreamer client replied with answer and trickle candidates. A ICE candidate pair has been selected.
(see janus debug output: https://pastebin.com/qFBctiyS)

Now I expect gstreamer to initiate a DTLS handshake. I use wireshark to check for DTLS packets but nothing goes over the wire. The SDP produced by gstreamer indicates "a=setup:active" which I think should determine that gstreamer should start the handshake.

I saw that dtlsenc has a 'is-client' property which I assume is internally used by webrctbin. (https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-dtlsenc.html)

Is there anything else that I am missing?

**Comment by petergerten** [comment]
After further investigation I found that gstreamer did not automatically add the ICE candidates from the SDP and I had to manually add them. (I wrongly assumed I only have to do that for trickle candidates)
After that - all is fine and the DTLS handshake works :-)

**Comment by saket424** [comment]
Hi @petergerten 
Can you elaborate on "had to manually add the ICE candidates". I too am stuck at the ICE connectivity check failing stage and would like to know which function you had to invoke to tell gstreamer of the trickle candidates. BTW I am using the python sendrecv example as my starting point and I modified it to talk to janus instead of nirbheek's server.

Some of my local reflexive ICE candidates trickle candidates are arriving well after the answer from Janus and I suspect that is where the problem is

I am using the videoroom plugin to publish and you seem to be using the streaming plugin to view but these ice connectivity checks are common across either plugin

**Comment by saket424** [comment]
Yes it works now!
I had to "manually add the local ice candidates that were trickling in by adding the "self.webrtc.emit" line which was in a different spot in the python example

 def send_ice_candidate_message(self, _, mlineindex, candidate):
        icemsg = {'candidate': candidate, 'sdpMLineIndex': mlineindex, 'sdpMid': "0"}
        self.webrtc.emit('add-ice-candidate', mlineindex, candidate)
        print (icemsg)
        loop = asyncio.new_event_loop()
        loop.run_until_complete(self.signaling.sendtrickle(icemsg))

**Comment by sampleref** [comment]
> After further investigation I found that gstreamer did not automatically add the ICE candidates from the SDP and I had to manually add them. (I wrongly assumed I only have to do that for trickle candidates)
> After that - all is fine and the DTLS handshake works :-)

Hi @petergerten  I am facing the same issue, where webrtcbin is acting as media receiver. Using GStreamer 1.16 on Ubuntu 16.04. The sdp is sent from browser as sendonly and its only SDP, no ICE within. All ICE is coming up as trickle. Gstreamer logs as below,

_0:01:19.248821190    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:595:get_agent_by_pem: no agent with generated cert found, creating new
0:01:19.249210492    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1020:bio_method_new: BIO: new
0:01:19.249251780    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d3404cb00> connection created: role=server buf=((nil):0/0) 10110|0 before SSL initialization
0:01:19.249468775    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:599:get_agent_by_pem:<GstDtlsAgent@0x7f3d20019970> using agent with generated cert
0:01:19.249571638    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1020:bio_method_new: BIO: new
0:01:19.249592799    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d20047d70> connection created: role=server buf=((nil):0/0) 10110|0 before SSL initialization
0:01:19.250192175    19 0x7f3d34002ca0 DEBUG            dtlssrtpenc gstdtlssrtpenc.c:329:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> pad requested
0:01:19.250296352    19 0x7f3d34002ca0 LOG              dtlssrtpenc gstdtlssrtpenc.c:347:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> added rtp sink pad
0:01:19.250325347    19 0x7f3d34002ca0 DEBUG            dtlssrtpenc gstdtlssrtpenc.c:329:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> pad requested
0:01:19.250414248    19 0x7f3d34002ca0 LOG              dtlssrtpenc gstdtlssrtpenc.c:362:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> added rtcp sink pad
0:01:19.250455687    19 0x7f3d34002ca0 DEBUG            dtlssrtpenc gstdtlssrtpenc.c:329:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> pad requested
0:01:19.250468782    19 0x7f3d34002ca0 DEBUG                dtlsenc gstdtlsenc.c:347:gst_dtls_enc_request_new_pad:<dtlsenc0> sink pad requested
0:01:19.250521012    19 0x7f3d34002ca0 LOG              dtlssrtpenc gstdtlssrtpenc.c:369:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc0> added data sink pad
0:01:19.250588258    19 0x7f3d34002ca0 DEBUG            dtlssrtpenc gstdtlssrtpenc.c:329:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc1> pad requested
0:01:19.250666029    19 0x7f3d34002ca0 LOG              dtlssrtpenc gstdtlssrtpenc.c:362:gst_dtls_srtp_enc_request_new_pad:<dtlssrtpenc1> added rtcp sink pad
0:01:19.251023764    19 0x7f3d34002ca0 DEBUG            dtlssrtpdec gstdtlssrtpdec.c:285:gst_dtls_srtp_dec_request_new_pad:<dtlssrtpdec0> pad requested
0:01:19.251037189    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:360:gst_dtls_dec_request_new_pad:<dtlsdec0> requesting pad
0:01:19.251077102    19 0x7f3d34002ca0 LOG              dtlssrtpdec gstdtlssrtpdec.c:304:gst_dtls_srtp_dec_request_new_pad:<dtlssrtpdec0> added data src pad
0:01:19.251110708    19 0x7f3d34002ca0 DEBUG            dtlssrtpdec gstdtlssrtpdec.c:285:gst_dtls_srtp_dec_request_new_pad:<dtlssrtpdec1> pad requested
0:01:19.251123030    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:360:gst_dtls_dec_request_new_pad:<dtlsdec1> requesting pad
0:01:19.251163124    19 0x7f3d34002ca0 LOG              dtlssrtpdec gstdtlssrtpdec.c:304:gst_dtls_srtp_dec_request_new_pad:<dtlssrtpdec1> added data src pad
0:01:19.252112090    19 0x7f3d200196d0 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<nicesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:01:19.252142638    19 0x7f3d200196d0 WARN                GST_PADS gstpad.c:4230:gst_pad_peer_query:<nicesrc0:src> could not send sticky events
0:01:19.252241508    19 0x7f3d200730f0 FIXME                default gstutils.c:3981:gst_pad_create_stream_id_internal:<nicesrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:01:19.252284122    19 0x7f3d200730f0 WARN                GST_PADS gstpad.c:4230:gst_pad_peer_query:<nicesrc1:src> could not send sticky events
0:01:19.818888078    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:658:gst_dtls_dec_fetch_connection: fetching 'rtp_0_1672472566' from connection table, size is 2
0:01:19.818919615    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:496:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d3404cb00> locking @ set_send_callback
0:01:19.818950233    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:498:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d3404cb00> locked @ set_send_callback
0:01:19.818964403    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:510:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d3404cb00> unlocking @ set_send_callback
0:01:19.819047033    19 0x7f3d34002ca0 DEBUG                dtlsenc gstdtlsenc.c:378:src_activate_mode:<dtlsenc0> src pad activating in push mode
0:01:19.819114275    19 0x7f3d34002ca0 DEBUG                dtlsenc gstdtlsenc.c:330:gst_dtls_enc_change_state:<dtlsenc0> starting connection rtp_0_1672472566
0:01:19.819129207    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:303:gst_dtls_connection_start:<GstDtlsConnection@0x7f3d3404cb00> locking @ start
0:01:19.819141912    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:305:gst_dtls_connection_start:<GstDtlsConnection@0x7f3d3404cb00> locked @ start
0:01:19.819159030    19 0x7f3d200fb320 TRACE                dtlsenc gstdtlsenc.c:414:src_task_loop:<dtlsenc0> src loop: acquiring lock
0:01:19.819162363    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d3404cb00> initial state set: role=client buf=((nil):0/0) 1110|0 before SSL initialization
0:01:19.819186832    19 0x7f3d200fb320 TRACE                dtlsenc gstdtlsenc.c:416:src_task_loop:<dtlsenc0> src loop: acquired lock
0:01:19.819225485    19 0x7f3d200fb320 TRACE                dtlsenc gstdtlsenc.c:426:src_task_loop:<dtlsenc0> src loop: queue empty, waiting for add
0:01:19.819211576    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d3404cb00> poll: before handshake: role=client buf=((nil):0/0) 1110|0 before SSL initialization
0:01:19.819339512    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 6
0:01:19.819403512    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:980:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: Timeout set
0:01:19.819422778    19 0x7f3d34002ca0 DEBUG         dtlsconnection gstdtlsconnection.c:390:gst_dtls_connection_check_timeout_locked:<GstDtlsConnection@0x7f3d3404cb00> waiting for 999981 usec
0:01:19.819495301    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 49
0:01:19.819506492    19 0x7f3d34002ca0 DEBUG         dtlsconnection gstdtlsconnection.c:1006:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: MTU query, returning 0...
0:01:19.819516489    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 49
0:01:19.819527594    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 49
0:01:19.819538094    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 42
0:01:19.819556173    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d3404cb00> BIO: unhandled ctrl, 49

0:01:19.819987805    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d3404cb00> poll: after handshake: role=client buf=((nil):0/0) 1001010|c SSLv3/TLS write client hello
0:01:19.820002220    19 0x7f3d34002ca0 DEBUG         dtlsconnection gstdtlsconnection.c:758:openssl_poll:<GstDtlsConnection@0x7f3d3404cb00> do_handshake encountered BIO error
0:01:19.820023588    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:793:openssl_poll:<GstDtlsConnection@0x7f3d3404cb00> SSL syscall error: errno 0: Success
0:01:19.820039250    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d3404cb00> first poll done: role=client buf=((nil):0/0) 1001010|c SSLv3/TLS write client hello
0:01:19.820053051    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:325:gst_dtls_connection_start:<GstDtlsConnection@0x7f3d3404cb00> unlocking @ start
0:01:19.820211876    19 0x7f3d34002ca0 DEBUG                dtlsdec gstdtlsdec.c:658:gst_dtls_dec_fetch_connection: fetching 'rtcp_0_1115281242' from connection table, size is 1
0:01:19.820230701    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:496:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d20047d70> locking @ set_send_callback
0:01:19.820244661    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:498:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d20047d70> locked @ set_send_callback
0:01:19.820257349    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:510:gst_dtls_connection_set_send_callback:<GstDtlsConnection@0x7f3d20047d70> unlocking @ set_send_callback
0:01:19.820338526    19 0x7f3d34002ca0 DEBUG                dtlsenc gstdtlsenc.c:378:src_activate_mode:<dtlsenc1> src pad activating in push mode
0:01:19.820399376    19 0x7f3d34002ca0 DEBUG                dtlsenc gstdtlsenc.c:330:gst_dtls_enc_change_state:<dtlsenc1> starting connection rtcp_0_1115281242
0:01:19.820411636    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:303:gst_dtls_connection_start:<GstDtlsConnection@0x7f3d20047d70> locking @ start
0:01:19.820421325    19 0x7f3d34002ca0 TRACE         dtlsconnection gstdtlsconnection.c:305:gst_dtls_connection_start:<GstDtlsConnection@0x7f3d20047d70> locked @ start
0:01:19.820430493    19 0x7f3d200fc800 TRACE                dtlsenc gstdtlsenc.c:414:src_task_loop:<dtlsenc1> src loop: acquiring lock
0:01:19.820448016    19 0x7f3d200fc800 TRACE                dtlsenc gstdtlsenc.c:416:src_task_loop:<dtlsenc1> src loop: acquired lock
0:01:19.820435910    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d20047d70> initial state set: role=client buf=((nil):0/0) 1110|0 before SSL initialization
0:01:19.820482086    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:629:log_state:<GstDtlsConnection@0x7f3d20047d70> poll: before handshake: role=client buf=((nil):0/0) 1110|0 before SSL initialization
0:01:19.820525455    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:1012:bio_method_ctrl:<GstDtlsConnection@0x7f3d20047d70> BIO: unhandled ctrl, 6
0:01:19.820570160    19 0x7f3d34002ca0 LOG           dtlsconnection gstdtlsconnection.c:980:bio_method_ctrl:<GstDtlsConnection@0x7f3d20047d70> BIO: Timeout set_


Looks like its trying to send client hello but not succeeded. No DTLS packets on wireshark sent. And I verified that no ICE messages are within SDP offer. SDP offer to gstreamer webrtcbin as below,

_"sdp":"v=0\r\no=- 8360833541034081384 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:r7ot\r\na=ice-pwd:Odrs9UUbWfEdJ+Q1iKO/WyQQ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 FD:D2:FC:22:F2:FB:1A:2A:57:35:6D:3B:07:05:0A:EC:3E:3B:EC:60:72:10:67:4F:1B:71:AB:5B:2D:C1:A7:4D\r\na=setup:actpass\r\na=mid:0\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=msid:bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB 4b66ef68-338b-4d2c-8323-3e413426204f\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 red/90000\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 ulpfec/90000\r\na=ssrc-group:FID 2514817883 3089842812\r\na=ssrc:2514817883 cname:sN4lY/QCwlweDDS8\r\na=ssrc:2514817883 msid:bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB 4b66ef68-338b-4d2c-8323-3e413426204f\r\na=ssrc:2514817883 mslabel:bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB\r\na=ssrc:2514817883 label:4b66ef68-338b-4d2c-8323-3e413426204f\r\na=ssrc:3089842812 cname:sN4lY/QCwlweDDS8\r\na=ssrc:3089842812 msid:bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB 4b66ef68-338b-4d2c-8323-3e413426204f\r\na=ssrc:3089842812 mslabel:bq1tGSK02H1PuMDFtTllrvRqC9dXWTgLyFCB\r\na=ssrc:3089842812 label:4b66ef68-338b-4d2c-8323-3e413426204f\r\n","type":"offer"_

And answer from webrtcbin as below

_"sdp": "v=0\r\no=- 8360833541034081384 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:AqKWFBwNk27K5GortmY8krLAcgqC1JtE\r\na=ice-pwd:y/Ba3mcc+NGno7mrlQz4+0Ov76EEVfmp\r\na=mid:0\r\na=rtcp-mux\r\na=setup:active\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 ccm fir\r\na=recvonly\r\na=fingerprint:sha-256 D5:5A:84:8E:BA:92:6F:2E:88:C1:24:20:F6:FA:FE:11:62:96:4B:DE:58:44:1F:09:48:1F:44:3D:7D:E4:5F:D9\r\n",
    "type": "answer"_

But no DTLS **client hello** triggered by webrtcbin

**Comment by sampleref** [comment]
Sorry for the long post earlier, but I could figure out that actual cause was with libnice. On machine with GStreamer host actually there were many virtual interfaces, where libnice was exhausting while matching the pairs and logging messages as below

_Pruned 1 candidates. Conncheck list has 101 elements left. Maximum connchecks allowed : 100_

I could find few suggestions on that (https://gitlab.freedesktop.org/libnice/libnice/issues/95) where libnice can be built with meson option **ignored-network-interface-prefix** and with that I could make it work. Not sure if its a consistent fix but helped by skipping few non essential interfaces which were exhausting libnice loop
