### ISSUE TITLE
Looking for Help : Trying to use v4l2src instead of videotestsrc

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#8]
Hi, i'm a student on an internship, trying to implement a live stream with webRTC. The recent update of Gstreamer head me to this API and Demo. 

I'm a new be on WebRTC and this Gstreamer API for WebRTC.

So here is my problem. When i use the "https://webrtc.nirbheek.in/" + the demo everything work fine i'm able to watch the ball moving. I was also able to hear the sound ! But i have disable it :) 

My problem is "switching from videotestsrc pattern = ball. to v4l2src isn't working" [The video stream doesn't show in the <video> HTML5 ]  I have looked at http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html But my low skill on C language is slowing me.

And it's a bit weird because JUST changing videotestsrc to v4l2src doesn't show any error :/

I supposed it's a SDP problem. But i have any clue ! And i also supposed that you have already tryied to replace this by a webcam =) 

Thank you for reading my post ! I hope you can help me =) 

P.S I have read : http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html  and the link it shares

**Comment by ghost** [comment]
Ok, i have invistigated and it's seems this pipeline isn't working for me :
 gst-launch-1.0 v4l2src ! queue ! vp8enc ! rtpvp8pay !
    application/x-rtp,media=video,encoding-name=VP8,payload=96 ! 
    webrtcbin name=sendrecv

The error is
GstPipeline:pipeline0/GstV4l2Src:v4l2src0 : Internal data stream error
streaming stopped, reason not-negotiated (-4)

So i have invistigated the caps. Everythings look fine the compatibility beetween the elements of the pipeline seems good.

The good point is it's "just" a gstreamer problem.

**Comment by ystreet** [comment]
Try adding a videoconvert element after v4l2src.

**Comment by ghost** [comment]
It's working now ! Still lot of bad things "low framerate don't know why" But it's work !!

Thank you ystreet

**Comment by tp-m** [comment]
Try `vp8enc deadline=1`

**Comment by ghost** [comment]
Yeah, thank you it's better now it could improve but that "good". 

Thank you tp-m
