### ISSUE TITLE
Reuse pipeline

### ISSUE THREAD

**Issue by dernster** [centricular/gstwebrtc-demos#83]
Is there a way to not recreate the entire the pipeline every time we get a peer connection? I'm wondering if setting a NULL state on the pipeline and then start playing will trigger the on-negotiation-needed callback. In my use case I'd like to not create an entire pipeline each time I get a peer connection.

Thanks!

**Comment by dernster** [comment]
Solved this by dynamically adding/removing a webrtc branch on the pipeline

**Comment by roberto497** [comment]
Can you show me how you did it? I have the same problem
