### ISSUE TITLE
gstwebrtc-sendrecv on Android using C JNI

### ISSUE THREAD

**Issue by saket424** [centricular/gstwebrtc-demos#84]
@MathieuDuponchelle,
Thus far, I have managed to use the cerbero cross-compile script to compile Android libraries but don't know how to proceed from there. Do you have a sample Android studio project or Android.mk ndk-build file that you can share that interworks with the webrtc.nirbheek.in websocket sample, so I can setup the right environment to use gstreamer webrtcbin on Android.. I assume no root access is needed on Android.
I really appreciate you efforts on this project. Many thanks in advance.

**Comment by MathieuDuponchelle** [comment]
@saket424 : https://github.com/ystreet/gstwebrtc-demos/tree/android . You shouldn't need root access no. @ystreet you probably should make a PR with this :)

**Comment by saket424** [comment]
@ystreet 
Thanks for this android project

I set gstAndroidRoot=/home/anand/gstreamer-stuff/cerbero/android/cerbero/build/dist/ in the gradle.properties file so it finds most of the libraries. I am only compiling for armv7 and not universal

I get the following linker error
...
-pthread nice gupnp-igd-1.0 gstreamer-base-1.0 -pthread -llog -Wl,-no-undefined -fuse-ld=gold -Wl,-soname,libgstreamer_android.so
clang++: error: no such file or directory: 'nice'
clang++: error: no such file or directory: 'gupnp-igd-1.0'
clang++: error: no such file or directory: 'gstreamer-base-1.0'
make: *** [buildsharedlibrary_armeabi-v7a] Error 1

Full logs are here
https://pastebin.com/aGqFM4kv

Maybe I missed a step?

**Comment by MathieuDuponchelle** [comment]
@saket424 try compiling against the universal binaries first I'd say :)

**Comment by saket424** [comment]
@MathieuDuponchelle and @ystreet ,

With the pre-compiled 15.1.1 universal binaries, I get the same linker error messages as my cerbero-built binaries when i try to build the apk

However when I try the 14.4.4 universal binaries, no linker error and I am able to build and install the apk

When I connect to nirbheek's server I get an android assert right after the offer and ice candidadtes are sent to nirbheek's server and this assertion fires before nirbheek's sdp answer is processed

Can you confirm this c-based demo still builds and works for you with 14.4.4 and does not compile with 15.1.1 ?


2019-02-18 12:21:53.901 4992-5066/? E/GLib+stderr: **
    ERROR:/home/anand/gstreamer-stuff/cerbero/android/gstwebrtc-demos/android/app/src/main/jni/webrtc.c:523:on_server_message: assertion failed: (json_object_has_member (object, "type"))
2019-02-18 12:21:53.902 4992-5066/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 5066 (Thread-2)

**Comment by MathieuDuponchelle** [comment]
Oh I remember having fixed that bug, I think @ystreet might have developed this against an older version of the signalling server, please try and apply this: https://paste.fedoraproject.org/paste/367MFHKB10fiwvbSbmRJPQ

**Comment by saket424** [comment]
That patched worked! Now the remaining unknown is why do we get a build error with 15.1.1 universal and not with 14.4.4 universal android binaries

**Comment by MathieuDuponchelle** [comment]
That's a good question, but I haven't tried this project with 1.15.1 I'm afraid :) @nirbheek might have a clue (or not)

**Comment by saket424** [comment]
Also when I try this on T-Mobile 4G, webrtc.nirbheek.in reports receiving some fully bogus ice candidates from android

Received {"ice":{"candidate":"candidate:1 2 UDP 2013266430 192.0.0.4 37332 typ host","sdpMLineIndex":1}}
webrtc.js:104 Received {"ice":{"candidate":"candidate:2 2 TCP 1015021822 192.0.0.4 9 typ host tcptype active","sdpMLineIndex":1}}
webrtc.js:104 Received {"ice":{"candidate":"candidate:3 2 TCP 1010827518 192.0.0.4 45616 typ host tcptype passive","sdpMLineIndex":1}}

Even adding a stun-server to the pipeline did not seem to help.

**Comment by MathieuDuponchelle** [comment]
What makes these "bogus"? They are `host` candidates, favoured if the peer you're initiating a connection with is in the same network

**Comment by saket424** [comment]
i called it "bogus" because I was frustrated that it did not work over 4G

**Comment by MathieuDuponchelle** [comment]
I see, annoying, these are the only candidates you're seeing?

**Comment by saket424** [comment]
Yes those were the only candidates that were received by the desktop browser using nirbheek's wss server. There should have been many more candidates. Can you or nirbheek try the Android sample using 4G instead of wifi and report your results? It is a non-starter for me if the sample doesn't work over 4G reliably.

**Comment by MathieuDuponchelle** [comment]
@saket424 perhaps at some point, in the meantime I would suggest looking at the libnice / gstreamer logs

**Comment by MathieuDuponchelle** [comment]
@saket424 , @nirbheek and I looked into the 1.15.1 issue last Friday, https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/114 fixes it.

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
