### ISSUE TITLE
Audio Transceivers not working

### ISSUE THREAD

**Issue by a-morales** [centricular/gstwebrtc-demos#86]
So I've been playing around with transceivers and have been using `webrtc-sendrecv.c` for testing. For background I'm working on receiving only audio/video from a connected client and then do some processing with Gstreamer. I have successfully been able to request video only by adding a transceiver  to the `webrtcbin`, but when I try to do the same for audio I'm getting an error thrown in google chrome. I have my [changes in a fork](https://github.com/centricular/gstwebrtc-demos/compare/master...a-morales:figure-out-transceivers?expand=1), and when I try to run it I get the following error when setting the remote description in chrome. 

```
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote audio description send parameters
```

When comparing the SDP from my changes compared to the original `webrtc-sendrecv.c` code, which I have pasted below, the first thing I noticed is that the clock rate for audio and video in the SDP is set to some random number. Additionally the audio media is missing the `a=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0` attribute. Is there a way to add new attributes for a transceiver? I have looked through the Gstreamer source code and at the WebRTC examples in `gst-plugins-bad`, and the closest thing I found was https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/commit/bbb1143ca36f9e201a6236dcfed384d44b26b4e4#4e11eb1a784eb7e36cf9a1d60a77ae7da9c78c9d_98_104. I've tried to set those properties in the transceiver caps, but unfortunately this doesn't work. 
```
SDP offer from my branch (fails)

v=0
o=- 5871605055453365992 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1 application2
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:ZXUmPp2Nfd8iTW0TD548U9s1EKBVN9Q/
a=ice-pwd:Ob0nA5tZkiF7CEsXH1dUj915qCxk7t33
a=rtcp-mux
a=rtcp-rsize
a=recvonly
a=rtpmap:96 VP8/-1819307696
a=rtcp-fb:96 nack pli
a=mid:video0
a=fingerprint:sha-256 FD:1F:9F:46:C4:76:91:E8:6D:F2:0F:61:9F:1D:E6:E4:5C:12:DA:9F:B3:56:2A:ED:A1:E4:1D:A6:0A:B3:6B:83
m=audio 0 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:ZXUmPp2Nfd8iTW0TD548U9s1EKBVN9Q/
a=ice-pwd:Ob0nA5tZkiF7CEsXH1dUj915qCxk7t33
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=recvonly
a=rtpmap:97 OPUS/-1811692800
a=rtcp-fb:97 nack pli
a=mid:audio1
a=fingerprint:sha-256 FD:1F:9F:46:C4:76:91:E8:6D:F2:0F:61:9F:1D:E6:E4:5C:12:DA:9F:B3:56:2A:ED:A1:E4:1D:A6:0A:B3:6B:83
m=application 0 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:ZXUmPp2Nfd8iTW0TD548U9s1EKBVN9Q/
a=ice-pwd:Ob0nA5tZkiF7CEsXH1dUj915qCxk7t33
a=bundle-only
a=mid:application2
a=sctp-port:5000
a=fingerprint:sha-256 FD:1F:9F:46:C4:76:91:E8:6D:F2:0F:61:9F:1D:E6:E4:5C:12:DA:9F:B3:56:2A:ED:A1:E4:1D:A6:0A:B3:6B:83
```

```
SDP offer from master branch (succeeds) 

v=0
o=- 8605264427952112764 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1 application2
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:tg9wzBiR5lk48tW7LTDHP5tRD834kxKV
a=ice-pwd:LXnwZhDqiZmkw9u8ILKhx8uywED52Bq0
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack pli
a=framerate:30
a=ssrc:259899146 msid:user2688560425@host-574aa372 webrtctransceiver0
a=ssrc:259899146 cname:user2688560425@host-574aa372
a=mid:video0
a=fingerprint:sha-256 33:E3:CE:D8:AE:19:9F:19:AA:33:14:83:C0:24:80:32:D9:58:91:38:BB:62:EA:1E:E5:35:2F:CA:8D:2D:29:AA
m=audio 0 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:tg9wzBiR5lk48tW7LTDHP5tRD834kxKV
a=ice-pwd:LXnwZhDqiZmkw9u8ILKhx8uywED52Bq0
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:97 OPUS/48000/2
a=rtcp-fb:97 nack pli
a=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0
a=ssrc:1553823004 msid:user2688560425@host-574aa372 webrtctransceiver1
a=ssrc:1553823004 cname:user2688560425@host-574aa372
a=mid:audio1
a=fingerprint:sha-256 33:E3:CE:D8:AE:19:9F:19:AA:33:14:83:C0:24:80:32:D9:58:91:38:BB:62:EA:1E:E5:35:2F:CA:8D:2D:29:AA
m=application 0 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:tg9wzBiR5lk48tW7LTDHP5tRD834kxKV
a=ice-pwd:LXnwZhDqiZmkw9u8ILKhx8uywED52Bq0
a=bundle-only
a=mid:application2
a=sctp-port:5000
a=fingerprint:sha-256 33:E3:CE:D8:AE:19:9F:19:AA:33:14:83:C0:24:80:32:D9:58:91:38:BB:62:EA:1E:E5:35:2F:CA:8D:2D:29:AA
=fingerprint:sha-256 8C:43:BD:9C:70:7E:1C:40:F8:08:B7:FE:6C:70:A2:C3:10:E1:CE:AA:BF:E5:FA:32:B8:11:C9:0A:27:9F:7D:A9
```

**Comment by ystreet** [comment]
The caps you provide to create the transceiver must be complete enough to create a SDP from.  The parsing code from the caps to the SDP structure is at https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/master/gst-libs/gst/sdp/gstsdpmessage.c#L3763.  The clock rate is taken from the `clock-rate` field in the caps you provide.

Please use the GStreamer issue tracker SDP or webrtcbin related issues.
