### ISSUE TITLE
The server did not accept the WebSocket handshake

### ISSUE THREAD

**Issue by LuckeX** [centricular/gstwebrtc-demos#88]
When I run "./webrtc-sendrecv  --peer-id 3277" in my ubuntu shell ,and I use " https://webrtc.nirbheek.in:8443 " for my singling server. But  there is something wrong like this:
it shows
 "
 Connecting to server ....
< HTTP/1.1 4 Could not connect :Network is unreachable
< Soup-Debug-Timestamp:1551343363
< Soup-Debug: SoupMessage 0 (0xbc60b0 )

The server did not accept the WebSocket handshake
" 
So , what should I do to solve this problem.
Thank you very much!

**Comment by generic-beat-detector** [comment]
Try with `--disable-ssl` ... but this seems to solve issues when the HTTP reason is

    < HTTP/1.1 4 Could not connect: Connection refused

... your case might be different `: Network is unreachable`...

**Comment by ystreet** [comment]
`Network is unreachable` generally means you don't have a valid network connection.  It may be temporary or not.  You need to figure out your network reachability yourself, we cannot help with that.
