### ISSUE TITLE
errors with addIceCandidate

### ISSUE THREAD

**Issue by ocampana** [centricular/gstwebrtc-demos#89]
I setup the demo, running the signaling server, opening the browser and finally running webrtc-sendrecv. I have gstreamer 1.14.4.

With Firefox 60.5.1esr on Debian Buster, in the browser I get the following message:
`Status: InvalidStateError: setRemoteDescription needs to called before addIceCandidate`
The same happens when connecting to https://webrtc.nirbheek.in/ .

With google Chrome 72.0.3626.119 on Debian Buster, in the browser I get the following message:
`Status: OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate`
The same happens when connecting to https://webrtc.nirbheek.in/ .

**Comment by ocampana** [comment]
I upload a wireshark trace acquired without using encryption in the signalling server

[setRemoteDescription_before_addIceCandidate.pcapng.zip](https://github.com/centricular/gstwebrtc-demos/files/2918553/setRemoteDescription_before_addIceCandidate.pcapng.zip)

**Comment by PaulIPS** [comment]
@ocampana I am seeing the same issue when I host the JS files from an ip address instead of localhost. Was a workaround found?

**Comment by ystreet** [comment]
I'm pretty sure JSEP mandates that ice candidates received before the SDP are held until the SDP is applied.  Also there have been multiple fixes in this area within webrtcbin to help solve this case in the past 2 years.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.
