### ISSUE TITLE
Error in sendrecv demo

### ISSUE THREAD

**Issue by yjjnls** [centricular/gstwebrtc-demos#9]
I run the demo in windows with Gstreamer 1.14.0 release.

In the example sendrecv, when I open the index.html in chrome, it always shows 
`failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
and can't connect to the server.

But I try the session-client.py and they work well.

Any idea about the error?

**Comment by ghost** [comment]
Can't help you with your problem now, but if you just want to test the WebRTCbin you have https://webrtc.nirbheek.in, which worked pretty well.

Do you have a server who just share index.html and the js folder ?

**Comment by yjjnls** [comment]
OK, I may use https://webrtc.nirbheek.in now, but I want to configure my own webrtc application, so I still need to build the local signalling.

>Do you have a server who just share index.html and the js folder ?

what does it mean?

**Comment by ghost** [comment]
Serve the js/ directory on the root of your website !*

But nevermind you are already serving the JS and html file.

Can't help you :/ I'm not enough strong !

**Comment by ystreet** [comment]
If you're serving the html/js yourself, you need to either 1. have a proper SSL certificate installed for your server or 2. add an exception for the signalling server inside your browser by visiting the signalling server location (default is `https://<hostname>:8443`) and adding the exception.

Note that you don't need to use this specific signalling to build a webrtc application using GStreamer's webrtcbin.  This is just an example of how it could be done.

**Comment by yjjnls** [comment]
@ystreet Thank you
