### ISSUE TITLE
Is there a webrtc implement without gstreamer?

### ISSUE THREAD

**Issue by BloodyF** [centricular/gstwebrtc-demos#90]
Hi @ystreet ,
I have a raw H264 bitstream and need to feed it to webrtc input. I want to implement everything in pure C/C++ without Glib, GObject, Gstreamer....
So do you have a light weight Webrtc implement in C/C++? I tried Webrtc API of Google but it is too heavy and complex.
If not, please suggest a gstreamer pipeline to feed H264 bitstream (in buffer) as source.
Thank you

**Comment by ystreet** [comment]
I don't know of any off the top of my head although if you search you may find some.  This project is for a demos based on a GStreamer-based solution so you're unlikely to find information on other webrtc implementations.

One could imagine a pipeline like so:
filesrc location=file.h264 ! h264parse ! rtph264pay ! webrtcbin
