### ISSUE TITLE
Can not remove and then add audio track to peer connection

### ISSUE THREAD

**Issue by CallousOdesa** [centricular/gstwebrtc-demos#91]
On the first connection audio works in both directions of Google Chrome browser Version 72.0.3626.121 (Official Build) (64-bit). 
But when I remove audio track and then add it again there is no audio sent to webrtc-sendrecv.
As I can see in chrome://webrtc-internals/ triggered transceiverModified and transceiverAdded after that came negotiationneeded. After that audio cannot be heard on client with webrtc-sendrecv and only one packet in few seconds is sent I can see that in chrome://webrtc-internals/ Conn-audio1-1-0 (googCandidatePair) section.
`let senders = peer_connection.getSenders();`
`  senders.forEach(function(sender){`
`	peer_connection.removeTrack(sender);`
`  })`
`  let audioTracks = local_stream.getAudioTracks();`
`  sender = peer_connection.addTrack(audioTracks[0], local_stream);`
`  peer_connection.dispatchEvent(new Event("negotiationneeded"))`

**Comment by ystreet** [comment]
webrtcbin currently does not support renegotiation of anything.  There is work ongoing for simple cases in https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/167
