### ISSUE TITLE
Could not create data channel, is usrsctp available?

### ISSUE THREAD

**Issue by kwizzk** [centricular/gstwebrtc-demos#94]
Attempting to run gstWebRTC sendrecv on Ubuntu 18.10.   The system worked well until we modified the pipeline (could see the ball and hear the noise).  

Our pipeline settings are as follows:
 pipe1 =
      gst_parse_launch ("webrtcbin bundle-policy=max-bundle name=sendrecv " STUN_SERVER
      "v4l2src ! video/x-raw,format=YUY2,width=320,height=240 ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "
      "queue ! " RTP_CAPS_VP8 "96 ! sendrecv. ",
      &error);

When we tried to connect to another computer using the following commands we received the following response/errors:

<pre><font color="#4CE64C"><b>ubuntu@bionic-xfce</b></font>:<font color="#295FCC"><b>~/gstwebrtc-demos/sendrecv/gst</b></font>$ ./webrtc-sendrecv --peer-id=2750
Connecting to server...
&gt; GET  HTTP/1.1
&gt; Soup-Debug-Timestamp: 1553022601
&gt; Soup-Debug: SoupSession 1 (0x231f098), SoupMessage 1 (0x21b1170), SoupSocket 1 (0x25c8498)
&gt; Host: webrtc.nirbheek.in:8443
&gt; Upgrade: websocket
&gt; Connection: Upgrade
&gt; Sec-WebSocket-Key: WS84Vt3H03mQm8guZLFSlQ==
&gt; Sec-WebSocket-Version: 13
&gt; Accept-Encoding: gzip, deflate
  
&lt; HTTP/1.1 101 Switching Protocols
&lt; Soup-Debug-Timestamp: 1553022601
&lt; Soup-Debug: SoupMessage 1 (0x21b1170)
&lt; Server: Python/3.5 websockets/3.3
&lt; Upgrade: WebSocket
&lt; Connection: Upgrade
&lt; Sec-WebSocket-Accept: YY4BsKaet7VNG5aWPGrlxv6D0Ks=
  
Connected to signalling server
Registering id 6541 with server
Registered with server
Setting up signalling server call with 2750

(webrtc-sendrecv:1637): GLib-GObject-<font color="#DED82C"><b>WARNING</b></font> **: <font color="#0039AA">12:10:03.199</font>: ../../../../gobject/gsignal.c:3492: signal name &apos;create-data-channel&apos; is invalid for instance &apos;0x25d8148&apos; of type &apos;GstWebRTCBin&apos;
Could not create data channel, is usrsctp available?

(webrtc-sendrecv:1637): GLib-GObject-<font color="#DED82C"><b>WARNING</b></font> **: <font color="#0039AA">12:10:03.200</font>: ../../../../gobject/gsignal.c:2523: signal &apos;on-data-channel&apos; is invalid for instance &apos;0x25d8148&apos; of type &apos;GstWebRTCBin&apos;
Starting pipeline
ERROR: failed to start pipeline

(webrtc-sendrecv:1637): GLib-<font color="#CC58CC"><b>CRITICAL</b></font> **: <font color="#0039AA">12:10:03.208</font>: g_main_loop_unref: assertion &apos;loop != NULL&apos; failed
<font color="#4CE64C"><b>ubuntu@bionic-xfce</b></font>:<font color="#295FCC"><b>~/gstwebrtc-demos/sendrecv/gst</b></font>$</pre>

Our pipeline settings are as follows:
 pipe1 =
      gst_parse_launch ("webrtcbin bundle-policy=max-bundle name=sendrecv " STUN_SERVER
      "v4l2src ! video/x-raw,format=YUY2,width=320,height=240 ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "
      "queue ! " RTP_CAPS_VP8 "96 ! sendrecv. ",
      &error);

**Comment by tono12** [comment]
WebRTC's data channel is for data transmission and is not a media channel (for audio/video).
Your error is not related to data channel. It seems to be in the pipeline.

Anyway, you need gst 1.15 version to use data channels.

**Comment by ystreet** [comment]
You need GStreamer >= 1.16 to be able to use data channels and the examples in the default code.

We cannot provide support for every modification you make to these programs.  Sorry.
