### ISSUE TITLE
How to set pipe to send video and audio and receive audio only?

### ISSUE THREAD

**Issue by turtlebond** [centricular/gstwebrtc-demos#96]
Hi,
How can I set the pipe in the gst for the following case:
audio: send and recv
video: send only

I tried something like this:

> pipe1 = gst_parse_launch ("webrtcbin name=sendrecv " STUN_SERVER
> "videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "
> "queue ! " RTP_CAPS_VP8 "96 ! sendonly. "
> "audiotestsrc wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay ! "
> "queue ! " RTP_CAPS_OPUS "97 ! sendrecv. ",
> &error);
> 

I am certain its not the correct way and ran into error:

> ERROR           GST_PIPELINE grammar.y:1255:priv_gst_parse_launch: No sink-element named "(null)" - omitting link
> Failed to parse launch: No sink-element named "(null)" - omitting link

Any pointers will be good.

Thank you

**Comment by turtlebond** [comment]
For trial i use :
   pipe1=get_launch_launch( "videotestsrc ! video/x-raw,framerate=1/1 ! queue ! vp8enc ! rtpvp8pay ! queue !  application/x-rtp,media=video,payload=96,encoding-name=VP8 ! "
      "webrtcbin name=send",NULL);

the offer always use a=sendrecv . 
Not sure how to set the pipe to to use a=sendonly

**Comment by turtlebond** [comment]
Will look into this fix by @a-morales
https://github.com/centricular/gstwebrtc-demos/compare/master...a-morales:figure-out-transceivers?expand=1

**Comment by turtlebond** [comment]
I was doing some experiment using add-transceiver. 

```
        pipe1 = gst_pipeline_new("test-pipeline");
        g_assert_nonnull(pipe1);

            webrtc1 = gst_element_factory_make("webrtcbin", NULL);
            g_object_set(webrtc1, "stun-server", "stun://stun.l.google.com:19302", NULL);

            GstElement *videotestsrc = gst_element_factory_make("videotestsrc", NULL);
            g_object_set(videotestsrc, "pattern", 10, NULL);


            GstElement *capsfilter1 = gst_element_factory_make("capsfilter",NULL);
            GstCaps *caps1 = gst_caps_from_string ("video/x-raw ,format=YUY2,width=640,height=480,framerate=30/1");
            g_object_set ( G_OBJECT(capsfilter1), "caps", caps1, NULL);

            GstElement *queue = gst_element_factory_make("queue",NULL);
            GstElement *videoconvert = gst_element_factory_make("videoconvert",NULL);

            GstElement *vp8enc = gst_element_factory_make("vp8enc",NULL);
            g_object_set(G_OBJECT(vp8enc), "deadline", 1, "buffer-size",10000,NULL); 

            GstElement *capsfilter2 = gst_element_factory_make("capsfilter",NULL);
            GstCaps *caps2 = gst_caps_from_string ("video/x-raw ,framerate=30/1");
            g_object_set ( G_OBJECT(capsfilter2), "caps", caps2, NULL);

            GstElement *rtpvp8pay = gst_element_factory_make("rtpvp8pay",NULL);
            GstElement *xvimagesink = gst_element_factory_make("xvimagesink",NULL);

            GstElement *audiotestsrc = gst_element_factory_make("audiotestsrc", NULL);
            g_object_set(videotestsrc, "wave", 10, NULL);    
            GstElement *audioconvert = gst_element_factory_make("audioconvert",NULL);

            GstElement *audioresample = gst_element_factory_make("audioresample", NULL);
            GstElement *opusenc = gst_element_factory_make("opusenc", NULL);            
            GstElement *rtpopuspay = gst_element_factory_make("rtpopuspay", NULL);
     
  g_print("setting video transceiver\n");
  direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;
  caps = gst_caps_from_string(RTP_CAPS_VP8 );
  g_signal_emit_by_name(webrtc1, "add-transceiver", direction, caps, &trans);

  gst_caps_unref(caps);

  g_print("setting audio transceiver\n");
  direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV;
  caps = gst_caps_from_string(RTP_CAPS_OPUS );
  g_signal_emit_by_name(webrtc1, "add-transceiver", direction, caps, &trans);

  gst_caps_unref(caps);

gst_bin_add_many(GST_BIN (pipe1), webrtc1,videotestsrc,videoconvert,queue,vp8enc, rtpvp8pay,audiotestsrc,audioconvert,audioresample,opusenc,rtpopuspay,NULL);
gst_element_link_many( webrtc1,videotestsrc,videoconvert,queue,vp8enc, rtpvp8pay, queue, audiotestsrc,audioconvert, audioresample, queue, opusenc,rtpopuspay,queue, webrtc1,NULL);
  gst_element_sync_state_with_parent(webrtc1);
```

and this is the offer sent:

> RECEIVED: {"type":"offer","sdp":"v=0\r\no=- 687536781469950957 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:eqKjN34K8oHP5mVua+UpoRuvqXNGcx1y\r\na=ice-pwd:aVsHMm/mjokAUjNeTt2FY49cYWcDWnc8\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 nack pli\r\na=mid:video0\r\na=fingerprint:sha-256 3D:0F:A5:57:83:E8:4E:34:04:0F:3A:6C:70:8D:D1:ED:27:86:A2:07:DA:79:42:51:36:5F:66:13:D3:F1:5D:E9\r\nm=audio 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:a2ROyRUOAOdcS7MSzLPu2PPX5q72W5oE\r\na=ice-pwd:qpknyBNJsy+rKMAnLN5G/0xIF7d/xnAX\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:97 OPUS/-200830888\r\na=rtcp-fb:97 nack pli\r\na=mid:audio1\r\na=fingerprint:sha-256 3D:0F:A5:57:83:E8:4E:34:04:0F:3A:6C:70:8D:D1:ED:27:86:A2:07:DA:79:42:51:36:5F:66:13:D3:F1:5D:E9\r\n"}

This is the offer sent when using the working example.

> RECEIVED: {"type":"offer","sdp":"v=0\r\no=- 7356890844542364874 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:1RBG3whgLxRYpbnqqvqQAOHWIfCBRz2F\r\na=ice-pwd:OrSQVx0JvLAqQ1+qqfitGRYvee87Qdc9\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 nack pli\r\na=framerate:30\r\na=ssrc:368025592 msid:user1240689907@host-bf2fc37a webrtctransceiver0\r\na=ssrc:368025592 cname:user1240689907@host-bf2fc37a\r\na=mid:video0\r\na=fingerprint:sha-256 FA:59:0E:25:51:65:A0:D8:1B:78:C9:A0:D9:32:09:A6:E4:BD:15:30:0F:6A:89:C3:BE:26:5F:69:66:5B:C9:C8\r\nm=audio 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:7CgazmyoOK0Pt9oMAPyDcp834a4hj9Qv\r\na=ice-pwd:lww97lVt1ZX1HtfxVpOz+2N4tjHyFhQr\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendrecv\r\na=rtpmap:97 OPUS/48000/2\r\na=rtcp-fb:97 nack pli\r\na=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0\r\na=ssrc:173655711 msid:user1240689907@host-bf2fc37a webrtctransceiver1\r\na=ssrc:173655711 cname:user1240689907@host-bf2fc37a\r\na=mid:audio1\r\na=fingerprint:sha-256 FA:59:0E:25:51:65:A0:D8:1B:78:C9:A0:D9:32:09:A6:E4:BD:15:30:0F:6A:89:C3:BE:26:5F:69:66:5B:C9:C8\r\n"}

```
            pipe1 = gst_parse_launch ("webrtcbin name=sendrecv " STUN_SERVER
            "videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay ! "
            "queue ! " RTP_CAPS_VP8 "96 ! sendrecv. "
           "audiotestsrc wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay ! "
           "queue ! " RTP_CAPS_OPUS "97 ! sendrecv. ",
            &error);

          
            if (error) {
                g_printerr ("Failed to parse launch: %s\n", error->message);
                g_error_free (error);
            }

   
            webrtc1 = gst_bin_get_by_name (GST_BIN (pipe1), "sendrecv");
            g_assert_nonnull (webrtc1);
```

Noticed that when using add-transceiver method, following info is missing in the offer when compared with working example.

> a=ssrc:368025592 msid:user1240689907@host-bf2fc37a webrtctransceiver0\r\na=ssrc:368025592 cname:user1240689907@host-bf2fc37a\r\

Any idea on how this can be included when creating the offer?

**Comment by turtlebond** [comment]
This code includes the missing info which was missing earlier. However, the add-transceiver signal is not included in the code
```
        pipe1 = gst_pipeline_new("test-pipeline");
        g_assert_nonnull(pipe1);

        webrtc1 = gst_element_factory_make("webrtcbin", NULL);
        GstElement *videotestsrc = gst_element_factory_make("videotestsrc", NULL);
        GstElement *videoconvert = gst_element_factory_make("videoconvert",NULL);
        GstElement *vp8enc = gst_element_factory_make("vp8enc",NULL);
        GstElement *rtpvp8pay = gst_element_factory_make("rtpvp8pay",NULL);
        GstElement *xvimagesink = gst_element_factory_make("xvimagesink",NULL);
        GstElement *sink = gst_element_factory_make ("autovideosink", "sink");
        GstElement *queue0 = gst_element_factory_make("queue",NULL);
        GstElement *queue1 = gst_element_factory_make("queue",NULL);
        GstElement *queue2 = gst_element_factory_make("queue",NULL);
        GstElement *queue3 = gst_element_factory_make("queue",NULL);
        GstElement *audiotestsrc = gst_element_factory_make("audiotestsrc", NULL);
        GstElement *audioconvert = gst_element_factory_make("audioconvert",NULL);
        GstElement *audioresample = gst_element_factory_make("audioresample", NULL);
        GstElement *opusenc = gst_element_factory_make("opusenc", NULL);  
        GstElement *rtpopuspay = gst_element_factory_make("rtpopuspay", NULL);


//            g_object_set(webrtc1, "bundle-policy", 3, "stun-server", "stun://stun.l.google.com:19302", NULL);
        g_object_set(webrtc1, "stun-server", "stun://stun.l.google.com:19302", NULL);
        g_object_set(videotestsrc, "pattern", 10, NULL);
        g_object_set(G_OBJECT(vp8enc), "deadline", 1, "buffer-size",10000,NULL); 
        g_object_set(audiotestsrc, "wave", 8, NULL);    

gst_bin_add_many(GST_BIN (pipe1), webrtc1,videotestsrc, videoconvert,queue0,vp8enc, rtpvp8pay,queue1,NULL);
gst_element_link_many( videotestsrc,videoconvert,queue0,vp8enc, rtpvp8pay, queue1,webrtc1,NULL);
gst_bin_add_many(GST_BIN (pipe1), webrtc1,audiotestsrc, audioconvert,queue2,opusenc, rtpopuspay,queue3,NULL);
gst_element_link_many( audiotestsrc,audioconvert,queue2,opusenc, rtpopuspay, queue3,webrtc1,NULL);
```

When I include the add-transceiver to the above code, there are 2 video and audio in the offer. 
Example for audio:
```
#define RTP_CAPS_OPUS "application/x-rtp,media=audio,encoding-name=OPUS,payload=96,clock-rate=48000"
gst_bin_add_many(GST_BIN (pipe1), audiotestsrc, audioconvert,queue2,opusenc, rtpopuspay,queue3,webrtc1,NULL);
gst_element_link_many( audiotestsrc,audioconvert,queue2,opusenc, rtpopuspay,queue3,webrtc1,NULL);

  g_print("setting audio transceiver\n");
  direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;
  caps = gst_caps_from_string(RTP_CAPS_OPUS);
  g_signal_emit_by_name(webrtc1, "add-transceiver", direction, caps, &trans);
```

>  SEND: {"type":"answer","sdp":"v=0\r\no=- 4605476359901274690 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS QMn63pXPkFudhHRGKY1oYHiiL9kCXqIpAL52\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:0rZQ\r\na=ice-pwd:srBdq1xNLfMuidUGVgERi6n0\r\na=ice-options:trickle\r\na=fingerprint:sha-256 66:81:7F:03:7C:52:30:AD:FB:FD:FD:92:EA:11:1C:9C:D2:4B:3D:98:9C:F1:39:15:F4:0A:58:6D:2C:99:41:92\r\na=setup:active\r\na=mid:audio0\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:96 OPUS/48000/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\na=ssrc:415431539 cname:fd0FXtFWEk0TjC2S\r\na=ssrc:415431539 msid:QMn63pXPkFudhHRGKY1oYHiiL9kCXqIpAL52 25ba29ac-c41c-47ee-a691-f4c2cac9eac3\r\na=ssrc:415431539 mslabel:QMn63pXPkFudhHRGKY1oYHiiL9kCXqIpAL52\r\na=ssrc:415431539 label:25ba29ac-c41c-47ee-a691-f4c2cac9eac3\r\nm=audio 9 UDP/TLS/RTP/SAVPF 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Gqw7\r\na=ice-pwd:QUqt2zZVd65IDbowEvdGOimp\r\na=ice-options:trickle\r\na=fingerprint:sha-256 66:81:7F:03:7C:52:30:AD:FB:FD:FD:92:EA:11:1C:9C:D2:4B:3D:98:9C:F1:39:15:F4:0A:58:6D:2C:99:41:92\r\na=setup:active\r\na=mid:audio1\r\na=recvonly\r\na=rtcp-mux\r\n"}

Removed webrtcbin from the gst_element_link_many and set the add-transceiver signal's cap to null. This sets the direction and only send the audio once. but this method keeps sending the offer in a loop. 

```
gst_bin_add_many(GST_BIN (pipe1), audiotestsrc, audioconvert,queue2,opusenc, rtpopuspay,queue3,webrtc1,NULL);
gst_element_link_many( audiotestsrc,audioconvert,queue2,opusenc, rtpopuspay,queue3,NULL);

  direction = GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY;
  g_signal_emit_by_name(webrtc1, "add-transceiver", direction, NULL, &trans);

gst_element_link_many(queue3,webrtc1,NULL); 
```
Any tips would be helpful. 
thank you

**Comment by ystreet** [comment]
For support requests, please use the GStreamer mailing list or the IRC channel.
