### ISSUE TITLE
Sendrecv : Does not work on chrome when audio is AAC

### ISSUE THREAD

**Issue by jagadishkamathk** [centricular/gstwebrtc-demos#97]
I have modified the sendrecv/gst/webrtc-sendrecv.c to support AAC. Replaced Opusenc with avenc_aac and also modified caps and corresponding rtp payloder. I get the following error on chrome

**Status: InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote audio description send parameters.**

I presume AAC should be supported by chrome since it is natively supported otherwise in mp4

**Comment by ystreet** [comment]
The webrtc stack chrome does not support AAC as it entirely different from the stack used by the other media stack in browsers used by e.g `<video>` tags

**Comment by jagadishkamathk** [comment]
Got it. Found out opus is the only supported codec as per https://tools.ietf.org/html/rfc7874 

Just curious. Are there other browsers which support codecs apart from Opus/speech codecs? Any known implementation of aac codec in webrtc implementation?

**Comment by ystreet** [comment]
No, all the major webrtc implementations in browsers are based on the webrtc.org codebase which doesn't support other audio codecs.

**Comment by jagadishkamathk** [comment]
Thanks for that valuable info :) Couldn't find that information anywhere. I would like to dig into Kurento and Janus to see what they do
