### ISSUE TITLE
webrtc-sendrecv.c with h264 does not work in Safari

### ISSUE THREAD

**Issue by ykazakov** [centricular/gstwebrtc-demos#98]
I have problems running the C version of the sendrecv in Safari.

I am aware that Safari does not support the vp8 codec, so I made a quick change replacing vp8 with h264:

https://github.com/ykazakov/gstwebrtc-demos/blob/h264/sendrecv/gst/webrtc-sendrecv.c

here is the diff:

https://github.com/ykazakov/gstwebrtc-demos/commit/a18baca95b31c27f920d1b6ea4b4c74721686c44#diff-fd3b884d5cb774c8e68a4b88c67a39ac

After the changes, the demo works fine in Chrome (v. 73.0.3683.86) and Firefox (v. 66.0.2), but not in Safari, neither on MacOS (10.14.4 v. 12.1) nor in iOS (v. 12.2).

Debugging javascript in Safari reveals this error:

https://github.com/centricular/gstwebrtc-demos/blob/725b8cbaf9c415a87db9ba2dd16abc3465c37a20/sendrecv/js/webrtc.js#L230

That is, the remote stream appears to contain no video tracks. But the audio track appears to be fine (which can be also seen in the debugger).

Interestingly, when I remove the audio source from the pipeline, i.e., the following two lines from webrtc-sendrecv.c, then the video comes through fine:
```
 "audiotestsrc is-live=true wave=red-noise ! audioconvert ! audioresample ! queue ! opusenc ! rtpopuspay ! "
      "queue ! " RTP_CAPS_OPUS "97 ! sendrecv. ",
```

Any help with diagnostic of this issue is appreciated.

The problem appears both for gstreamer v.1.14.4 on MacOS installed using Homebrew as mentioned in #40 and for gstreamer v.1.15.2 installed on raspberry pi using this script:
https://gist.github.com/ykazakov/472a46e3838bf9259921b273ca8a0173

**Comment by ykazakov** [comment]
Actually the video tracks appear to be empty also with the original demo (with the VP8) codec.

**Comment by ykazakov** [comment]
It looks like the stream is fine: if I comment out the check on video tracks, everything works fine:
https://github.com/centricular/gstwebrtc-demos/blob/725b8cbaf9c415a87db9ba2dd16abc3465c37a20/sendrecv/js/webrtc.js#L226

So it seems to be that the reported number of video tracks is not correct. Maybe a problem with the WebRTC adapter?
I noticed that [RTCPeerConnection demos](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) do not use the `onaddstream` callback but use `ontrack`:

https://github.com/webrtc/samples/blob/3092af4a7b136fb5d5d536a7d99b8006b779c8c2/src/content/peerconnection/pc1/js/main.js#L102

Perhaps this demo should be changed accordingly?

**Comment by nirbheek** [comment]
> I noticed that [RTCPeerConnection demos](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) do not use the `onaddstream` callback but use `ontrack`:

`ontrack` is indeed the new way, but it didn't work very well on all browsers back when these examples were written. We'd be happy to merge a pull request that makes that change as long as you're able to test it on Chrome, Firefox, and Safari :)

**Comment by ykazakov** [comment]
@nirbheek I think I can prepare a PR. Would you mind if I replace vp8 with h264? Otherwise Safari will clearly not work. Or do you have a hint of how one can choose the codec dynamically as a part of the negotiation?

**Comment by ykazakov** [comment]
Actually it [appears](https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes) that the newest Safari does support vp8. Just tested on MacOS and it works! So no need to change the codec.

**Comment by ykazakov** [comment]
Just a note: RTCPeerConnection.onaddstream is indeed [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream).
